# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['EscalationPathBetaArgs', 'EscalationPathBeta']

@pulumi.input_type
class EscalationPathBetaArgs:
    def __init__(__self__, *,
                 sequences: pulumi.Input[Mapping[str, pulumi.Input['EscalationPathBetaSequencesArgs']]],
                 start: pulumi.Input[_builtins.str],
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 repeat_config: pulumi.Input[Optional['EscalationPathBetaRepeatConfigArgs']] = None,
                 team_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 working_hours: pulumi.Input[Optional[Sequence[pulumi.Input['EscalationPathBetaWorkingHourArgs']]]] = None):
        """
        The set of arguments for constructing a EscalationPathBeta resource.

        :param pulumi.Input[Mapping[str, pulumi.Input['EscalationPathBetaSequencesArgs']]] sequences: Named sequences of nodes, keyed by a name you choose. Each sequence either ends with a `branch` node or runs off the end of the escalation path. Branches reference other sequences by key.
        :param pulumi.Input[_builtins.str] start: The key of the sequence this escalation path begins with.
        :param pulumi.Input[_builtins.str] name: The name of this escalation path, for the user's reference.
        :param pulumi.Input['EscalationPathBetaRepeatConfigArgs'] repeat_config: Controls if an escalation will repeat after acknowledgement, when the alert is unresolved. When configured, it will repeat after the specified delay.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] team_ids: IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required.
        :param pulumi.Input[Sequence[pulumi.Input['EscalationPathBetaWorkingHourArgs']]] working_hours: The working hours for this escalation path.
        """
        pulumi.set(__self__, "sequences", sequences)
        pulumi.set(__self__, "start", start)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if repeat_config is not None:
            pulumi.set(__self__, "repeat_config", repeat_config)
        if team_ids is not None:
            pulumi.set(__self__, "team_ids", team_ids)
        if working_hours is not None:
            pulumi.set(__self__, "working_hours", working_hours)

    @_builtins.property
    @pulumi.getter
    def sequences(self) -> pulumi.Input[Mapping[str, pulumi.Input['EscalationPathBetaSequencesArgs']]]:
        """
        Named sequences of nodes, keyed by a name you choose. Each sequence either ends with a `branch` node or runs off the end of the escalation path. Branches reference other sequences by key.
        """
        return pulumi.get(self, "sequences")

    @sequences.setter
    def sequences(self, value: pulumi.Input[Mapping[str, pulumi.Input['EscalationPathBetaSequencesArgs']]]):
        pulumi.set(self, "sequences", value)

    @_builtins.property
    @pulumi.getter
    def start(self) -> pulumi.Input[_builtins.str]:
        """
        The key of the sequence this escalation path begins with.
        """
        return pulumi.get(self, "start")

    @start.setter
    def start(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "start", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of this escalation path, for the user's reference.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="repeatConfig")
    def repeat_config(self) -> pulumi.Input[Optional['EscalationPathBetaRepeatConfigArgs']]:
        """
        Controls if an escalation will repeat after acknowledgement, when the alert is unresolved. When configured, it will repeat after the specified delay.
        """
        return pulumi.get(self, "repeat_config")

    @repeat_config.setter
    def repeat_config(self, value: pulumi.Input[Optional['EscalationPathBetaRepeatConfigArgs']]):
        pulumi.set(self, "repeat_config", value)

    @_builtins.property
    @pulumi.getter(name="teamIds")
    def team_ids(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required.
        """
        return pulumi.get(self, "team_ids")

    @team_ids.setter
    def team_ids(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "team_ids", value)

    @_builtins.property
    @pulumi.getter(name="workingHours")
    def working_hours(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['EscalationPathBetaWorkingHourArgs']]]]:
        """
        The working hours for this escalation path.
        """
        return pulumi.get(self, "working_hours")

    @working_hours.setter
    def working_hours(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['EscalationPathBetaWorkingHourArgs']]]]):
        pulumi.set(self, "working_hours", value)


@pulumi.input_type
class _EscalationPathBetaState:
    def __init__(__self__, *,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 repeat_config: pulumi.Input[Optional['EscalationPathBetaRepeatConfigArgs']] = None,
                 sequences: pulumi.Input[Optional[Mapping[str, pulumi.Input['EscalationPathBetaSequencesArgs']]]] = None,
                 start: pulumi.Input[Optional[_builtins.str]] = None,
                 team_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 working_hours: pulumi.Input[Optional[Sequence[pulumi.Input['EscalationPathBetaWorkingHourArgs']]]] = None):
        """
        Input properties used for looking up and filtering EscalationPathBeta resources.

        :param pulumi.Input[_builtins.str] name: The name of this escalation path, for the user's reference.
        :param pulumi.Input['EscalationPathBetaRepeatConfigArgs'] repeat_config: Controls if an escalation will repeat after acknowledgement, when the alert is unresolved. When configured, it will repeat after the specified delay.
        :param pulumi.Input[Mapping[str, pulumi.Input['EscalationPathBetaSequencesArgs']]] sequences: Named sequences of nodes, keyed by a name you choose. Each sequence either ends with a `branch` node or runs off the end of the escalation path. Branches reference other sequences by key.
        :param pulumi.Input[_builtins.str] start: The key of the sequence this escalation path begins with.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] team_ids: IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required.
        :param pulumi.Input[Sequence[pulumi.Input['EscalationPathBetaWorkingHourArgs']]] working_hours: The working hours for this escalation path.
        """
        if name is not None:
            pulumi.set(__self__, "name", name)
        if repeat_config is not None:
            pulumi.set(__self__, "repeat_config", repeat_config)
        if sequences is not None:
            pulumi.set(__self__, "sequences", sequences)
        if start is not None:
            pulumi.set(__self__, "start", start)
        if team_ids is not None:
            pulumi.set(__self__, "team_ids", team_ids)
        if working_hours is not None:
            pulumi.set(__self__, "working_hours", working_hours)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of this escalation path, for the user's reference.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="repeatConfig")
    def repeat_config(self) -> pulumi.Input[Optional['EscalationPathBetaRepeatConfigArgs']]:
        """
        Controls if an escalation will repeat after acknowledgement, when the alert is unresolved. When configured, it will repeat after the specified delay.
        """
        return pulumi.get(self, "repeat_config")

    @repeat_config.setter
    def repeat_config(self, value: pulumi.Input[Optional['EscalationPathBetaRepeatConfigArgs']]):
        pulumi.set(self, "repeat_config", value)

    @_builtins.property
    @pulumi.getter
    def sequences(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input['EscalationPathBetaSequencesArgs']]]]:
        """
        Named sequences of nodes, keyed by a name you choose. Each sequence either ends with a `branch` node or runs off the end of the escalation path. Branches reference other sequences by key.
        """
        return pulumi.get(self, "sequences")

    @sequences.setter
    def sequences(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input['EscalationPathBetaSequencesArgs']]]]):
        pulumi.set(self, "sequences", value)

    @_builtins.property
    @pulumi.getter
    def start(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The key of the sequence this escalation path begins with.
        """
        return pulumi.get(self, "start")

    @start.setter
    def start(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "start", value)

    @_builtins.property
    @pulumi.getter(name="teamIds")
    def team_ids(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required.
        """
        return pulumi.get(self, "team_ids")

    @team_ids.setter
    def team_ids(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "team_ids", value)

    @_builtins.property
    @pulumi.getter(name="workingHours")
    def working_hours(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['EscalationPathBetaWorkingHourArgs']]]]:
        """
        The working hours for this escalation path.
        """
        return pulumi.get(self, "working_hours")

    @working_hours.setter
    def working_hours(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['EscalationPathBetaWorkingHourArgs']]]]):
        pulumi.set(self, "working_hours", value)


@pulumi.type_token("incident:index/escalationPathBeta:EscalationPathBeta")
class EscalationPathBeta(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 repeat_config: pulumi.Input[Optional[Union['EscalationPathBetaRepeatConfigArgs', 'EscalationPathBetaRepeatConfigArgsDict']]] = None,
                 sequences: pulumi.Input[Optional[Mapping[str, pulumi.Input[Union['EscalationPathBetaSequencesArgs', 'EscalationPathBetaSequencesArgsDict']]]]] = None,
                 start: pulumi.Input[Optional[_builtins.str]] = None,
                 team_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 working_hours: pulumi.Input[Optional[Sequence[pulumi.Input[Union['EscalationPathBetaWorkingHourArgs', 'EscalationPathBetaWorkingHourArgsDict']]]]] = None,
                 __props__=None):
        """
        Create and manage escalation paths, written as a flat map of named node sequences.

        Each sequence runs its nodes in order and either ends with a `branch`, which names the sequences to continue down, or falls off the end of the escalation path.

        We'd generally recommend building escalation paths in our [web dashboard](https://app.incident.io/~/on-call/escalation-paths) and using the 'Export' flow to generate your Terraform.

        ## How this differs from `EscalationPath`

        `EscalationPath` nests a branch's nodes inside it, as `if_else.then_path` and
        `if_else.else_path`. Terraform schemas can't recurse indefinitely, so that resource stops at
        five levels of branching, and a path that branches more than that can't be written at all.

        This resource names its sequences instead. A `branch` says which sequence to continue down
        rather than holding its nodes, so every sequence sits at the same depth in the config and
        there's no nesting limit. It also swaps `repeat` for `loop`, which names the node to go back
        to, and replaces the raw engine `conditions` on a branch with a `branch.if` block holding one
        attribute per thing an escalation can be tested on.

        ## Beta, and what happens next

        This resource is in beta. Its schema may still change in ways that are not backwards
        compatible, so pin the provider version if that matters to you.

        `EscalationPath` is not deprecated, and there is no need to move anything yet. The
        two resources manage the same escalation paths through the same API, so don't point both at
        one path: they'd each plan to undo the other's changes.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_incident as incident

        # Look up a user to page. Escalation path targets can also be schedules or
        # Slack/Teams channels; see the `type` attribute on each target.
        on_call = incident.get_user(email="on-call@example.com")
        # A last resort path, which the path below hands over to out of hours.
        fallback = incident.EscalationPath("fallback",
            name="Fallback",
            paths=[{
                "type": "level",
                "level": {
                    "targets": [{
                        "type": "user",
                        "id": on_call.id,
                        "urgency": "high",
                    }],
                    "time_to_ack_seconds": 300,
                },
            }])
        # The same escalation path as the incident_escalation_path example, written as a
        # flat map of sequences: if in working hours, page with high urgency; otherwise
        # page with low urgency.
        urgent_support = incident.EscalationPathBeta("urgent_support",
            name="Urgent support",
            start="main",
            sequences={
                "main": {
                    "nodes": [{
                        "id": "start",
                        "branch": {
                            "if_": {
                                "working_hours_active": "UK",
                            },
                            "then": "in_hours",
                            "else_": "out_of_hours",
                        },
                    }],
                },
                "in_hours": {
                    "nodes": [
                        {
                            "level": {
                                "targets": [{
                                    "type": "user",
                                    "id": on_call.id,
                                    "urgency": "high",
                                }],
                                "time_to_ack_seconds": 300,
                            },
                        },
                        {
                            "delay": {
                                "delay_seconds": 120,
                            },
                        },
                        {
                            "loop": {
                                "back_to": "start",
                                "times": 3,
                            },
                        },
                    ],
                },
                "out_of_hours": {
                    "nodes": [
                        {
                            "level": {
                                "targets": [{
                                    "type": "user",
                                    "id": on_call.id,
                                    "urgency": "low",
                                }],
                                "time_to_ack_seconds": 300,
                            },
                        },
                        {
                            "escalation_path": {
                                "escalation_path_id": fallback.id,
                            },
                        },
                    ],
                },
            },
            working_hours=[{
                "id": "UK",
                "name": "UK",
                "timezone": "Europe/London",
                "weekday_intervals": [{
                    "weekday": "monday",
                    "start_time": "09:00",
                    "end_time": "17:00",
                }],
            }])
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        !/bin/bash

        Import an escalation path using its ID
        Replace the ID with a real ID from your incident.io organization

        ```sh
        $ pulumi import incident:index/escalationPathBeta:EscalationPathBeta urgent_support 01ABC123DEF456GHI789JKL
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] name: The name of this escalation path, for the user's reference.
        :param pulumi.Input[Union['EscalationPathBetaRepeatConfigArgs', 'EscalationPathBetaRepeatConfigArgsDict']] repeat_config: Controls if an escalation will repeat after acknowledgement, when the alert is unresolved. When configured, it will repeat after the specified delay.
        :param pulumi.Input[Mapping[str, pulumi.Input[Union['EscalationPathBetaSequencesArgs', 'EscalationPathBetaSequencesArgsDict']]]] sequences: Named sequences of nodes, keyed by a name you choose. Each sequence either ends with a `branch` node or runs off the end of the escalation path. Branches reference other sequences by key.
        :param pulumi.Input[_builtins.str] start: The key of the sequence this escalation path begins with.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] team_ids: IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required.
        :param pulumi.Input[Sequence[pulumi.Input[Union['EscalationPathBetaWorkingHourArgs', 'EscalationPathBetaWorkingHourArgsDict']]]] working_hours: The working hours for this escalation path.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: EscalationPathBetaArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create and manage escalation paths, written as a flat map of named node sequences.

        Each sequence runs its nodes in order and either ends with a `branch`, which names the sequences to continue down, or falls off the end of the escalation path.

        We'd generally recommend building escalation paths in our [web dashboard](https://app.incident.io/~/on-call/escalation-paths) and using the 'Export' flow to generate your Terraform.

        ## How this differs from `EscalationPath`

        `EscalationPath` nests a branch's nodes inside it, as `if_else.then_path` and
        `if_else.else_path`. Terraform schemas can't recurse indefinitely, so that resource stops at
        five levels of branching, and a path that branches more than that can't be written at all.

        This resource names its sequences instead. A `branch` says which sequence to continue down
        rather than holding its nodes, so every sequence sits at the same depth in the config and
        there's no nesting limit. It also swaps `repeat` for `loop`, which names the node to go back
        to, and replaces the raw engine `conditions` on a branch with a `branch.if` block holding one
        attribute per thing an escalation can be tested on.

        ## Beta, and what happens next

        This resource is in beta. Its schema may still change in ways that are not backwards
        compatible, so pin the provider version if that matters to you.

        `EscalationPath` is not deprecated, and there is no need to move anything yet. The
        two resources manage the same escalation paths through the same API, so don't point both at
        one path: they'd each plan to undo the other's changes.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_incident as incident

        # Look up a user to page. Escalation path targets can also be schedules or
        # Slack/Teams channels; see the `type` attribute on each target.
        on_call = incident.get_user(email="on-call@example.com")
        # A last resort path, which the path below hands over to out of hours.
        fallback = incident.EscalationPath("fallback",
            name="Fallback",
            paths=[{
                "type": "level",
                "level": {
                    "targets": [{
                        "type": "user",
                        "id": on_call.id,
                        "urgency": "high",
                    }],
                    "time_to_ack_seconds": 300,
                },
            }])
        # The same escalation path as the incident_escalation_path example, written as a
        # flat map of sequences: if in working hours, page with high urgency; otherwise
        # page with low urgency.
        urgent_support = incident.EscalationPathBeta("urgent_support",
            name="Urgent support",
            start="main",
            sequences={
                "main": {
                    "nodes": [{
                        "id": "start",
                        "branch": {
                            "if_": {
                                "working_hours_active": "UK",
                            },
                            "then": "in_hours",
                            "else_": "out_of_hours",
                        },
                    }],
                },
                "in_hours": {
                    "nodes": [
                        {
                            "level": {
                                "targets": [{
                                    "type": "user",
                                    "id": on_call.id,
                                    "urgency": "high",
                                }],
                                "time_to_ack_seconds": 300,
                            },
                        },
                        {
                            "delay": {
                                "delay_seconds": 120,
                            },
                        },
                        {
                            "loop": {
                                "back_to": "start",
                                "times": 3,
                            },
                        },
                    ],
                },
                "out_of_hours": {
                    "nodes": [
                        {
                            "level": {
                                "targets": [{
                                    "type": "user",
                                    "id": on_call.id,
                                    "urgency": "low",
                                }],
                                "time_to_ack_seconds": 300,
                            },
                        },
                        {
                            "escalation_path": {
                                "escalation_path_id": fallback.id,
                            },
                        },
                    ],
                },
            },
            working_hours=[{
                "id": "UK",
                "name": "UK",
                "timezone": "Europe/London",
                "weekday_intervals": [{
                    "weekday": "monday",
                    "start_time": "09:00",
                    "end_time": "17:00",
                }],
            }])
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        !/bin/bash

        Import an escalation path using its ID
        Replace the ID with a real ID from your incident.io organization

        ```sh
        $ pulumi import incident:index/escalationPathBeta:EscalationPathBeta urgent_support 01ABC123DEF456GHI789JKL
        ```


        :param str resource_name: The name of the resource.
        :param EscalationPathBetaArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(EscalationPathBetaArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 repeat_config: pulumi.Input[Optional[Union['EscalationPathBetaRepeatConfigArgs', 'EscalationPathBetaRepeatConfigArgsDict']]] = None,
                 sequences: pulumi.Input[Optional[Mapping[str, pulumi.Input[Union['EscalationPathBetaSequencesArgs', 'EscalationPathBetaSequencesArgsDict']]]]] = None,
                 start: pulumi.Input[Optional[_builtins.str]] = None,
                 team_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 working_hours: pulumi.Input[Optional[Sequence[pulumi.Input[Union['EscalationPathBetaWorkingHourArgs', 'EscalationPathBetaWorkingHourArgsDict']]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = EscalationPathBetaArgs.__new__(EscalationPathBetaArgs)

            __props__.__dict__["name"] = name
            __props__.__dict__["repeat_config"] = repeat_config
            if sequences is None and not opts.urn:
                raise TypeError("Missing required property 'sequences'")
            __props__.__dict__["sequences"] = sequences
            if start is None and not opts.urn:
                raise TypeError("Missing required property 'start'")
            __props__.__dict__["start"] = start
            __props__.__dict__["team_ids"] = team_ids
            __props__.__dict__["working_hours"] = working_hours
        super(EscalationPathBeta, __self__).__init__(
            'incident:index/escalationPathBeta:EscalationPathBeta',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            repeat_config: pulumi.Input[Optional[Union['EscalationPathBetaRepeatConfigArgs', 'EscalationPathBetaRepeatConfigArgsDict']]] = None,
            sequences: pulumi.Input[Optional[Mapping[str, pulumi.Input[Union['EscalationPathBetaSequencesArgs', 'EscalationPathBetaSequencesArgsDict']]]]] = None,
            start: pulumi.Input[Optional[_builtins.str]] = None,
            team_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            working_hours: pulumi.Input[Optional[Sequence[pulumi.Input[Union['EscalationPathBetaWorkingHourArgs', 'EscalationPathBetaWorkingHourArgsDict']]]]] = None) -> 'EscalationPathBeta':
        """
        Get an existing EscalationPathBeta resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] name: The name of this escalation path, for the user's reference.
        :param pulumi.Input[Union['EscalationPathBetaRepeatConfigArgs', 'EscalationPathBetaRepeatConfigArgsDict']] repeat_config: Controls if an escalation will repeat after acknowledgement, when the alert is unresolved. When configured, it will repeat after the specified delay.
        :param pulumi.Input[Mapping[str, pulumi.Input[Union['EscalationPathBetaSequencesArgs', 'EscalationPathBetaSequencesArgsDict']]]] sequences: Named sequences of nodes, keyed by a name you choose. Each sequence either ends with a `branch` node or runs off the end of the escalation path. Branches reference other sequences by key.
        :param pulumi.Input[_builtins.str] start: The key of the sequence this escalation path begins with.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] team_ids: IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required.
        :param pulumi.Input[Sequence[pulumi.Input[Union['EscalationPathBetaWorkingHourArgs', 'EscalationPathBetaWorkingHourArgsDict']]]] working_hours: The working hours for this escalation path.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _EscalationPathBetaState.__new__(_EscalationPathBetaState)

        __props__.__dict__["name"] = name
        __props__.__dict__["repeat_config"] = repeat_config
        __props__.__dict__["sequences"] = sequences
        __props__.__dict__["start"] = start
        __props__.__dict__["team_ids"] = team_ids
        __props__.__dict__["working_hours"] = working_hours
        return EscalationPathBeta(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of this escalation path, for the user's reference.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="repeatConfig")
    def repeat_config(self) -> pulumi.Output[Optional['outputs.EscalationPathBetaRepeatConfig']]:
        """
        Controls if an escalation will repeat after acknowledgement, when the alert is unresolved. When configured, it will repeat after the specified delay.
        """
        return pulumi.get(self, "repeat_config")

    @_builtins.property
    @pulumi.getter
    def sequences(self) -> pulumi.Output[Mapping[str, 'outputs.EscalationPathBetaSequences']]:
        """
        Named sequences of nodes, keyed by a name you choose. Each sequence either ends with a `branch` node or runs off the end of the escalation path. Branches reference other sequences by key.
        """
        return pulumi.get(self, "sequences")

    @_builtins.property
    @pulumi.getter
    def start(self) -> pulumi.Output[_builtins.str]:
        """
        The key of the sequence this escalation path begins with.
        """
        return pulumi.get(self, "start")

    @_builtins.property
    @pulumi.getter(name="teamIds")
    def team_ids(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required.
        """
        return pulumi.get(self, "team_ids")

    @_builtins.property
    @pulumi.getter(name="workingHours")
    def working_hours(self) -> pulumi.Output[Optional[Sequence['outputs.EscalationPathBetaWorkingHour']]]:
        """
        The working hours for this escalation path.
        """
        return pulumi.get(self, "working_hours")

