# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetIpAllowlistResult',
    'AwaitableGetIpAllowlistResult',
    'get_ip_allowlist',
    'get_ip_allowlist_output',
]

@pulumi.output_type
class GetIpAllowlistResult:
    """
    A collection of values returned by getIpAllowlist.
    """
    def __init__(__self__, allowlists=None, enabled=None, updated_at=None, version=None):
        if allowlists and not isinstance(allowlists, list):
            raise TypeError("Expected argument 'allowlists' to be a list")
        pulumi.set(__self__, "allowlists", allowlists)
        if enabled and not isinstance(enabled, bool):
            raise TypeError("Expected argument 'enabled' to be a bool")
        pulumi.set(__self__, "enabled", enabled)
        if updated_at and not isinstance(updated_at, str):
            raise TypeError("Expected argument 'updated_at' to be a str")
        pulumi.set(__self__, "updated_at", updated_at)
        if version and not isinstance(version, int):
            raise TypeError("Expected argument 'version' to be a int")
        pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    def allowlists(self) -> Sequence['outputs.GetIpAllowlistAllowlistResult']:
        """
        A list of IP addresses or CIDR prefixes to allow
        """
        return pulumi.get(self, "allowlists")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        """
        Whether this IP allowlist is enabled or not
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> _builtins.str:
        """
        The time this allowlist was last updated
        """
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter
    def version(self) -> _builtins.int:
        """
        The version of this IP allowlist
        """
        return pulumi.get(self, "version")


class AwaitableGetIpAllowlistResult(GetIpAllowlistResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetIpAllowlistResult(
            allowlists=self.allowlists,
            enabled=self.enabled,
            updated_at=self.updated_at,
            version=self.version)


def get_ip_allowlist(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetIpAllowlistResult:
    """
    Manage the IP allowlist.

    When enabled, the IP allowlist restricts authenticated traffic from the dashboard, public API and mobile app.

    Use this data source to read the organisation's IP allowlist: whether it is enabled, and the IP addresses or CIDR prefixes that are allowed to reach the dashboard, public API and mobile app.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_incident as incident

    # Read the organisation's IP allowlist.
    current = incident.get_ip_allowlist()
    pulumi.export("allowedAddresses", [item.value for item in current.allowlists])
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('incident:index/getIpAllowlist:getIpAllowlist', __args__, opts=opts, typ=GetIpAllowlistResult).value

    return AwaitableGetIpAllowlistResult(
        allowlists=pulumi.get(__ret__, 'allowlists'),
        enabled=pulumi.get(__ret__, 'enabled'),
        updated_at=pulumi.get(__ret__, 'updated_at'),
        version=pulumi.get(__ret__, 'version'))
def get_ip_allowlist_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetIpAllowlistResult]:
    """
    Manage the IP allowlist.

    When enabled, the IP allowlist restricts authenticated traffic from the dashboard, public API and mobile app.

    Use this data source to read the organisation's IP allowlist: whether it is enabled, and the IP addresses or CIDR prefixes that are allowed to reach the dashboard, public API and mobile app.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_incident as incident

    # Read the organisation's IP allowlist.
    current = incident.get_ip_allowlist()
    pulumi.export("allowedAddresses", [item.value for item in current.allowlists])
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('incident:index/getIpAllowlist:getIpAllowlist', __args__, opts=opts, typ=GetIpAllowlistResult)
    return __ret__.apply(lambda __response__: GetIpAllowlistResult(
        allowlists=pulumi.get(__response__, 'allowlists'),
        enabled=pulumi.get(__response__, 'enabled'),
        updated_at=pulumi.get(__response__, 'updated_at'),
        version=pulumi.get(__response__, 'version')))
