# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetAlertSourceAttributeResult',
    'AwaitableGetAlertSourceAttributeResult',
    'get_alert_source_attribute',
    'get_alert_source_attribute_output',
]

@pulumi.output_type
class GetAlertSourceAttributeResult:
    """
    A collection of values returned by getAlertSourceAttribute.
    """
    def __init__(__self__, alert_attribute_id=None, alert_source_id=None, array_values=None, expression=None, expression_ref=None, merge_strategy=None, named_expressions=None, value=None, value_literal=None, value_reference=None, values=None):
        if alert_attribute_id and not isinstance(alert_attribute_id, str):
            raise TypeError("Expected argument 'alert_attribute_id' to be a str")
        pulumi.set(__self__, "alert_attribute_id", alert_attribute_id)
        if alert_source_id and not isinstance(alert_source_id, str):
            raise TypeError("Expected argument 'alert_source_id' to be a str")
        pulumi.set(__self__, "alert_source_id", alert_source_id)
        if array_values and not isinstance(array_values, list):
            raise TypeError("Expected argument 'array_values' to be a list")
        pulumi.set(__self__, "array_values", array_values)
        if expression and not isinstance(expression, dict):
            raise TypeError("Expected argument 'expression' to be a dict")
        pulumi.set(__self__, "expression", expression)
        if expression_ref and not isinstance(expression_ref, str):
            raise TypeError("Expected argument 'expression_ref' to be a str")
        pulumi.set(__self__, "expression_ref", expression_ref)
        if merge_strategy and not isinstance(merge_strategy, str):
            raise TypeError("Expected argument 'merge_strategy' to be a str")
        pulumi.set(__self__, "merge_strategy", merge_strategy)
        if named_expressions and not isinstance(named_expressions, list):
            raise TypeError("Expected argument 'named_expressions' to be a list")
        pulumi.set(__self__, "named_expressions", named_expressions)
        if value and not isinstance(value, dict):
            raise TypeError("Expected argument 'value' to be a dict")
        pulumi.set(__self__, "value", value)
        if value_literal and not isinstance(value_literal, str):
            raise TypeError("Expected argument 'value_literal' to be a str")
        pulumi.set(__self__, "value_literal", value_literal)
        if value_reference and not isinstance(value_reference, str):
            raise TypeError("Expected argument 'value_reference' to be a str")
        pulumi.set(__self__, "value_reference", value_reference)
        if values and not isinstance(values, list):
            raise TypeError("Expected argument 'values' to be a list")
        pulumi.set(__self__, "values", values)

    @_builtins.property
    @pulumi.getter(name="alertAttributeId")
    def alert_attribute_id(self) -> _builtins.str:
        """
        The alert attribute being bound. This also identifies the binding: an attribute can be bound at most once per source.
        """
        return pulumi.get(self, "alert_attribute_id")

    @_builtins.property
    @pulumi.getter(name="alertSourceId")
    def alert_source_id(self) -> _builtins.str:
        """
        The alert source this binding belongs to
        """
        return pulumi.get(self, "alert_source_id")

    @_builtins.property
    @pulumi.getter(name="arrayValues")
    def array_values(self) -> Sequence['outputs.GetAlertSourceAttributeArrayValueResult']:
        """
        Several values, spelled out. Needed when they mix fixed values and references.
        """
        return pulumi.get(self, "array_values")

    @_builtins.property
    @pulumi.getter
    def expression(self) -> Optional['outputs.GetAlertSourceAttributeExpressionResult']:
        """
        The expression this field is bound to. Declaring it binds its result.
        """
        return pulumi.get(self, "expression")

    @_builtins.property
    @pulumi.getter(name="expressionRef")
    def expression_ref(self) -> _builtins.str:
        """
        The name of a named_expression in this resource, whose result becomes the value.
        """
        return pulumi.get(self, "expression_ref")

    @_builtins.property
    @pulumi.getter(name="mergeStrategy")
    def merge_strategy(self) -> _builtins.str:
        """
        How values are combined when an alert is updated. Possible values are: `first_wins`, `last_wins`, `append`, `max`, `min`.
        """
        return pulumi.get(self, "merge_strategy")

    @_builtins.property
    @pulumi.getter(name="namedExpressions")
    def named_expressions(self) -> Optional[Sequence['outputs.GetAlertSourceAttributeNamedExpressionResult']]:
        """
        An expression this resource owns, addressed by name.
        """
        return pulumi.get(self, "named_expressions")

    @_builtins.property
    @pulumi.getter
    def value(self) -> 'outputs.GetAlertSourceAttributeValueResult':
        """
        One value, spelled out. `value_literal` and `value_reference` are shorthand for this.
        """
        return pulumi.get(self, "value")

    @_builtins.property
    @pulumi.getter(name="valueLiteral")
    def value_literal(self) -> _builtins.str:
        """
        A fixed value. A catalog entry ID is a literal, not a reference.
        """
        return pulumi.get(self, "value_literal")

    @_builtins.property
    @pulumi.getter(name="valueReference")
    def value_reference(self) -> _builtins.str:
        """
        A reference into the scope, such as `payload.team`.
        """
        return pulumi.get(self, "value_reference")

    @_builtins.property
    @pulumi.getter
    def values(self) -> Sequence[_builtins.str]:
        """
        Several fixed values. For a mix of fixed values and references, use array_value.
        """
        return pulumi.get(self, "values")


class AwaitableGetAlertSourceAttributeResult(GetAlertSourceAttributeResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetAlertSourceAttributeResult(
            alert_attribute_id=self.alert_attribute_id,
            alert_source_id=self.alert_source_id,
            array_values=self.array_values,
            expression=self.expression,
            expression_ref=self.expression_ref,
            merge_strategy=self.merge_strategy,
            named_expressions=self.named_expressions,
            value=self.value,
            value_literal=self.value_literal,
            value_reference=self.value_reference,
            values=self.values)


def get_alert_source_attribute(alert_attribute_id: Optional[_builtins.str] = None,
                               alert_source_id: Optional[_builtins.str] = None,
                               expression: Optional[Union['GetAlertSourceAttributeExpressionArgs', 'GetAlertSourceAttributeExpressionArgsDict']] = None,
                               named_expressions: Optional[Sequence[Union['GetAlertSourceAttributeNamedExpressionArgs', 'GetAlertSourceAttributeNamedExpressionArgsDict']]] = None,
                               opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetAlertSourceAttributeResult:
    """
    Look up one attribute binding on an alert source by `alert_source_id` and `alert_attribute_id`.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_incident as incident

    # Look up one attribute binding on an alert source.
    environment = incident.get_alert_source_attribute(alert_source_id="01FCNDV6P870EA6S7TK1DSYDG0",
        alert_attribute_id="01GW2G3V0S59R238FAHPDS1R66")
    pulumi.export("environmentMergeStrategy", environment.merge_strategy)
    ```


    :param _builtins.str alert_attribute_id: The alert attribute being bound. This also identifies the binding: an attribute can be bound at most once per source.
    :param _builtins.str alert_source_id: The alert source this binding belongs to
    :param Union['GetAlertSourceAttributeExpressionArgs', 'GetAlertSourceAttributeExpressionArgsDict'] expression: The expression this field is bound to. Declaring it binds its result.
    :param Sequence[Union['GetAlertSourceAttributeNamedExpressionArgs', 'GetAlertSourceAttributeNamedExpressionArgsDict']] named_expressions: An expression this resource owns, addressed by name.
    """
    __args__ = dict()
    __args__['alertAttributeId'] = alert_attribute_id
    __args__['alertSourceId'] = alert_source_id
    __args__['expression'] = expression
    __args__['namedExpressions'] = named_expressions
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('incident:index/getAlertSourceAttribute:getAlertSourceAttribute', __args__, opts=opts, typ=GetAlertSourceAttributeResult).value

    return AwaitableGetAlertSourceAttributeResult(
        alert_attribute_id=pulumi.get(__ret__, 'alert_attribute_id'),
        alert_source_id=pulumi.get(__ret__, 'alert_source_id'),
        array_values=pulumi.get(__ret__, 'array_values'),
        expression=pulumi.get(__ret__, 'expression'),
        expression_ref=pulumi.get(__ret__, 'expression_ref'),
        merge_strategy=pulumi.get(__ret__, 'merge_strategy'),
        named_expressions=pulumi.get(__ret__, 'named_expressions'),
        value=pulumi.get(__ret__, 'value'),
        value_literal=pulumi.get(__ret__, 'value_literal'),
        value_reference=pulumi.get(__ret__, 'value_reference'),
        values=pulumi.get(__ret__, 'values'))
def get_alert_source_attribute_output(alert_attribute_id: pulumi.Input[Optional[_builtins.str]] = None,
                                      alert_source_id: pulumi.Input[Optional[_builtins.str]] = None,
                                      expression: pulumi.Input[Optional[Optional[Union['GetAlertSourceAttributeExpressionArgs', 'GetAlertSourceAttributeExpressionArgsDict']]]] = None,
                                      named_expressions: pulumi.Input[Optional[Optional[Sequence[Union['GetAlertSourceAttributeNamedExpressionArgs', 'GetAlertSourceAttributeNamedExpressionArgsDict']]]]] = None,
                                      opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetAlertSourceAttributeResult]:
    """
    Look up one attribute binding on an alert source by `alert_source_id` and `alert_attribute_id`.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_incident as incident

    # Look up one attribute binding on an alert source.
    environment = incident.get_alert_source_attribute(alert_source_id="01FCNDV6P870EA6S7TK1DSYDG0",
        alert_attribute_id="01GW2G3V0S59R238FAHPDS1R66")
    pulumi.export("environmentMergeStrategy", environment.merge_strategy)
    ```


    :param _builtins.str alert_attribute_id: The alert attribute being bound. This also identifies the binding: an attribute can be bound at most once per source.
    :param _builtins.str alert_source_id: The alert source this binding belongs to
    :param Union['GetAlertSourceAttributeExpressionArgs', 'GetAlertSourceAttributeExpressionArgsDict'] expression: The expression this field is bound to. Declaring it binds its result.
    :param Sequence[Union['GetAlertSourceAttributeNamedExpressionArgs', 'GetAlertSourceAttributeNamedExpressionArgsDict']] named_expressions: An expression this resource owns, addressed by name.
    """
    __args__ = dict()
    __args__['alertAttributeId'] = alert_attribute_id
    __args__['alertSourceId'] = alert_source_id
    __args__['expression'] = expression
    __args__['namedExpressions'] = named_expressions
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('incident:index/getAlertSourceAttribute:getAlertSourceAttribute', __args__, opts=opts, typ=GetAlertSourceAttributeResult)
    return __ret__.apply(lambda __response__: GetAlertSourceAttributeResult(
        alert_attribute_id=pulumi.get(__response__, 'alert_attribute_id'),
        alert_source_id=pulumi.get(__response__, 'alert_source_id'),
        array_values=pulumi.get(__response__, 'array_values'),
        expression=pulumi.get(__response__, 'expression'),
        expression_ref=pulumi.get(__response__, 'expression_ref'),
        merge_strategy=pulumi.get(__response__, 'merge_strategy'),
        named_expressions=pulumi.get(__response__, 'named_expressions'),
        value=pulumi.get(__response__, 'value'),
        value_literal=pulumi.get(__response__, 'value_literal'),
        value_reference=pulumi.get(__response__, 'value_reference'),
        values=pulumi.get(__response__, 'values')))
