# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetWorkflowResult',
    'AwaitableGetWorkflowResult',
    'get_workflow',
    'get_workflow_output',
]

@pulumi.output_type
class GetWorkflowResult:
    """
    A collection of values returned by getWorkflow.
    """
    def __init__(__self__, condition_groups=None, continue_on_step_error=None, delay=None, expressions=None, folder=None, form_fields=None, id=None, include_private_escalations=None, include_private_incidents=None, name=None, once_fors=None, owning_team_ids=None, private_incident_scope=None, runs_on_incident_modes=None, runs_on_incidents=None, shortform=None, state=None, steps=None, trigger=None):
        if condition_groups and not isinstance(condition_groups, list):
            raise TypeError("Expected argument 'condition_groups' to be a list")
        pulumi.set(__self__, "condition_groups", condition_groups)
        if continue_on_step_error and not isinstance(continue_on_step_error, bool):
            raise TypeError("Expected argument 'continue_on_step_error' to be a bool")
        pulumi.set(__self__, "continue_on_step_error", continue_on_step_error)
        if delay and not isinstance(delay, dict):
            raise TypeError("Expected argument 'delay' to be a dict")
        pulumi.set(__self__, "delay", delay)
        if expressions and not isinstance(expressions, list):
            raise TypeError("Expected argument 'expressions' to be a list")
        pulumi.set(__self__, "expressions", expressions)
        if folder and not isinstance(folder, str):
            raise TypeError("Expected argument 'folder' to be a str")
        pulumi.set(__self__, "folder", folder)
        if form_fields and not isinstance(form_fields, list):
            raise TypeError("Expected argument 'form_fields' to be a list")
        pulumi.set(__self__, "form_fields", form_fields)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if include_private_escalations and not isinstance(include_private_escalations, bool):
            raise TypeError("Expected argument 'include_private_escalations' to be a bool")
        pulumi.set(__self__, "include_private_escalations", include_private_escalations)
        if include_private_incidents and not isinstance(include_private_incidents, bool):
            raise TypeError("Expected argument 'include_private_incidents' to be a bool")
        pulumi.set(__self__, "include_private_incidents", include_private_incidents)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if once_fors and not isinstance(once_fors, list):
            raise TypeError("Expected argument 'once_fors' to be a list")
        pulumi.set(__self__, "once_fors", once_fors)
        if owning_team_ids and not isinstance(owning_team_ids, list):
            raise TypeError("Expected argument 'owning_team_ids' to be a list")
        pulumi.set(__self__, "owning_team_ids", owning_team_ids)
        if private_incident_scope and not isinstance(private_incident_scope, str):
            raise TypeError("Expected argument 'private_incident_scope' to be a str")
        pulumi.set(__self__, "private_incident_scope", private_incident_scope)
        if runs_on_incident_modes and not isinstance(runs_on_incident_modes, list):
            raise TypeError("Expected argument 'runs_on_incident_modes' to be a list")
        pulumi.set(__self__, "runs_on_incident_modes", runs_on_incident_modes)
        if runs_on_incidents and not isinstance(runs_on_incidents, str):
            raise TypeError("Expected argument 'runs_on_incidents' to be a str")
        pulumi.set(__self__, "runs_on_incidents", runs_on_incidents)
        if shortform and not isinstance(shortform, str):
            raise TypeError("Expected argument 'shortform' to be a str")
        pulumi.set(__self__, "shortform", shortform)
        if state and not isinstance(state, str):
            raise TypeError("Expected argument 'state' to be a str")
        pulumi.set(__self__, "state", state)
        if steps and not isinstance(steps, list):
            raise TypeError("Expected argument 'steps' to be a list")
        pulumi.set(__self__, "steps", steps)
        if trigger and not isinstance(trigger, str):
            raise TypeError("Expected argument 'trigger' to be a str")
        pulumi.set(__self__, "trigger", trigger)

    @_builtins.property
    @pulumi.getter(name="conditionGroups")
    def condition_groups(self) -> Sequence['outputs.GetWorkflowConditionGroupResult']:
        """
        The condition groups to apply in this filter. Only one group needs to be satisfied for the filter to pass.
        """
        return pulumi.get(self, "condition_groups")

    @_builtins.property
    @pulumi.getter(name="continueOnStepError")
    def continue_on_step_error(self) -> _builtins.bool:
        """
        Whether to continue executing the workflow if a step fails
        """
        return pulumi.get(self, "continue_on_step_error")

    @_builtins.property
    @pulumi.getter
    def delay(self) -> 'outputs.GetWorkflowDelayResult':
        """
        Configuration controlling workflow delay behaviour
        """
        return pulumi.get(self, "delay")

    @_builtins.property
    @pulumi.getter
    def expressions(self) -> Sequence['outputs.GetWorkflowExpressionResult']:
        """
        Expressions that make variables available in the scope
        """
        return pulumi.get(self, "expressions")

    @_builtins.property
    @pulumi.getter
    def folder(self) -> _builtins.str:
        """
        Folder to display the workflow in
        """
        return pulumi.get(self, "folder")

    @_builtins.property
    @pulumi.getter(name="formFields")
    def form_fields(self) -> Sequence['outputs.GetWorkflowFormFieldResult']:
        """
        User-configured form fields available in the workflow scope (manual triggers only)
        """
        return pulumi.get(self, "form_fields")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        Unique identifier for the workflow
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="includePrivateEscalations")
    def include_private_escalations(self) -> _builtins.bool:
        return pulumi.get(self, "include_private_escalations")

    @_builtins.property
    @pulumi.getter(name="includePrivateIncidents")
    @_utilities.deprecated("""Use `private_incident_scope` instead.""")
    def include_private_incidents(self) -> _builtins.bool:
        return pulumi.get(self, "include_private_incidents")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="onceFors")
    def once_fors(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "once_fors")

    @_builtins.property
    @pulumi.getter(name="owningTeamIds")
    def owning_team_ids(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "owning_team_ids")

    @_builtins.property
    @pulumi.getter(name="privateIncidentScope")
    def private_incident_scope(self) -> _builtins.str:
        return pulumi.get(self, "private_incident_scope")

    @_builtins.property
    @pulumi.getter(name="runsOnIncidentModes")
    def runs_on_incident_modes(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "runs_on_incident_modes")

    @_builtins.property
    @pulumi.getter(name="runsOnIncidents")
    def runs_on_incidents(self) -> _builtins.str:
        return pulumi.get(self, "runs_on_incidents")

    @_builtins.property
    @pulumi.getter
    def shortform(self) -> _builtins.str:
        return pulumi.get(self, "shortform")

    @_builtins.property
    @pulumi.getter
    def state(self) -> _builtins.str:
        return pulumi.get(self, "state")

    @_builtins.property
    @pulumi.getter
    def steps(self) -> Sequence['outputs.GetWorkflowStepResult']:
        return pulumi.get(self, "steps")

    @_builtins.property
    @pulumi.getter
    def trigger(self) -> _builtins.str:
        return pulumi.get(self, "trigger")


class AwaitableGetWorkflowResult(GetWorkflowResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetWorkflowResult(
            condition_groups=self.condition_groups,
            continue_on_step_error=self.continue_on_step_error,
            delay=self.delay,
            expressions=self.expressions,
            folder=self.folder,
            form_fields=self.form_fields,
            id=self.id,
            include_private_escalations=self.include_private_escalations,
            include_private_incidents=self.include_private_incidents,
            name=self.name,
            once_fors=self.once_fors,
            owning_team_ids=self.owning_team_ids,
            private_incident_scope=self.private_incident_scope,
            runs_on_incident_modes=self.runs_on_incident_modes,
            runs_on_incidents=self.runs_on_incidents,
            shortform=self.shortform,
            state=self.state,
            steps=self.steps,
            trigger=self.trigger)


def get_workflow(id: Optional[_builtins.str] = None,
                 opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetWorkflowResult:
    """
    Use this data source to retrieve the full configuration of an existing workflow by ID.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_incident as incident

    # Reference an existing workflow by its ID, to read back its full configuration.
    autoassign_incident_lead = incident.get_workflow(id="01HY0QGB4M1XKGQGKQD0N9MHKG")
    pulumi.export("autoassignIncidentLeadSteps", autoassign_incident_lead.steps)
    ```


    :param _builtins.str id: Unique identifier for the workflow
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('incident:index/getWorkflow:getWorkflow', __args__, opts=opts, typ=GetWorkflowResult).value

    return AwaitableGetWorkflowResult(
        condition_groups=pulumi.get(__ret__, 'condition_groups'),
        continue_on_step_error=pulumi.get(__ret__, 'continue_on_step_error'),
        delay=pulumi.get(__ret__, 'delay'),
        expressions=pulumi.get(__ret__, 'expressions'),
        folder=pulumi.get(__ret__, 'folder'),
        form_fields=pulumi.get(__ret__, 'form_fields'),
        id=pulumi.get(__ret__, 'id'),
        include_private_escalations=pulumi.get(__ret__, 'include_private_escalations'),
        include_private_incidents=pulumi.get(__ret__, 'include_private_incidents'),
        name=pulumi.get(__ret__, 'name'),
        once_fors=pulumi.get(__ret__, 'once_fors'),
        owning_team_ids=pulumi.get(__ret__, 'owning_team_ids'),
        private_incident_scope=pulumi.get(__ret__, 'private_incident_scope'),
        runs_on_incident_modes=pulumi.get(__ret__, 'runs_on_incident_modes'),
        runs_on_incidents=pulumi.get(__ret__, 'runs_on_incidents'),
        shortform=pulumi.get(__ret__, 'shortform'),
        state=pulumi.get(__ret__, 'state'),
        steps=pulumi.get(__ret__, 'steps'),
        trigger=pulumi.get(__ret__, 'trigger'))
def get_workflow_output(id: pulumi.Input[Optional[_builtins.str]] = None,
                        opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetWorkflowResult]:
    """
    Use this data source to retrieve the full configuration of an existing workflow by ID.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_incident as incident

    # Reference an existing workflow by its ID, to read back its full configuration.
    autoassign_incident_lead = incident.get_workflow(id="01HY0QGB4M1XKGQGKQD0N9MHKG")
    pulumi.export("autoassignIncidentLeadSteps", autoassign_incident_lead.steps)
    ```


    :param _builtins.str id: Unique identifier for the workflow
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('incident:index/getWorkflow:getWorkflow', __args__, opts=opts, typ=GetWorkflowResult)
    return __ret__.apply(lambda __response__: GetWorkflowResult(
        condition_groups=pulumi.get(__response__, 'condition_groups'),
        continue_on_step_error=pulumi.get(__response__, 'continue_on_step_error'),
        delay=pulumi.get(__response__, 'delay'),
        expressions=pulumi.get(__response__, 'expressions'),
        folder=pulumi.get(__response__, 'folder'),
        form_fields=pulumi.get(__response__, 'form_fields'),
        id=pulumi.get(__response__, 'id'),
        include_private_escalations=pulumi.get(__response__, 'include_private_escalations'),
        include_private_incidents=pulumi.get(__response__, 'include_private_incidents'),
        name=pulumi.get(__response__, 'name'),
        once_fors=pulumi.get(__response__, 'once_fors'),
        owning_team_ids=pulumi.get(__response__, 'owning_team_ids'),
        private_incident_scope=pulumi.get(__response__, 'private_incident_scope'),
        runs_on_incident_modes=pulumi.get(__response__, 'runs_on_incident_modes'),
        runs_on_incidents=pulumi.get(__response__, 'runs_on_incidents'),
        shortform=pulumi.get(__response__, 'shortform'),
        state=pulumi.get(__response__, 'state'),
        steps=pulumi.get(__response__, 'steps'),
        trigger=pulumi.get(__response__, 'trigger')))
