# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetRichTextResult',
    'AwaitableGetRichTextResult',
    'get_rich_text',
    'get_rich_text_output',
]

@pulumi.output_type
class GetRichTextResult:
    """
    A collection of values returned by getRichText.
    """
    def __init__(__self__, dropped_contents=None, feature_set=None, json=None, markdown=None):
        if dropped_contents and not isinstance(dropped_contents, list):
            raise TypeError("Expected argument 'dropped_contents' to be a list")
        pulumi.set(__self__, "dropped_contents", dropped_contents)
        if feature_set and not isinstance(feature_set, str):
            raise TypeError("Expected argument 'feature_set' to be a str")
        pulumi.set(__self__, "feature_set", feature_set)
        if json and not isinstance(json, str):
            raise TypeError("Expected argument 'json' to be a str")
        pulumi.set(__self__, "json", json)
        if markdown and not isinstance(markdown, str):
            raise TypeError("Expected argument 'markdown' to be a str")
        pulumi.set(__self__, "markdown", markdown)

    @_builtins.property
    @pulumi.getter(name="droppedContents")
    def dropped_contents(self) -> Sequence[_builtins.str]:
        """
        Node and mark types dropped because the feature set doesn't permit them. Empty when nothing was dropped.
        """
        return pulumi.get(self, "dropped_contents")

    @_builtins.property
    @pulumi.getter(name="featureSet")
    def feature_set(self) -> _builtins.str:
        """
        The feature set of the field this document is destined for. Content the feature set doesn't permit is dropped, and reported in dropped_content. Possible values are: `plain_single_line`, `plain_single_line_with_secrets`, `plain_multi_line`, `mrkdwn`, `rich`, `rich_with_images`, `slack_rich_text`, `slack_rich_text_with_headings`, `basic`, `basic_no_links`, `jira`.
        """
        return pulumi.get(self, "feature_set")

    @_builtins.property
    @pulumi.getter
    def json(self) -> _builtins.str:
        """
        The document, encoded as JSON. Assign it to the rich text field you built it for, such as an alert source template's `title` or `description` literal.
        """
        return pulumi.get(self, "json")

    @_builtins.property
    @pulumi.getter
    def markdown(self) -> _builtins.str:
        """
        The markdown to parse. Template variables written as {{ name }} become variable placeholders, and support the omit*if*unset and truncate filters.
        """
        return pulumi.get(self, "markdown")


class AwaitableGetRichTextResult(GetRichTextResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetRichTextResult(
            dropped_contents=self.dropped_contents,
            feature_set=self.feature_set,
            json=self.json,
            markdown=self.markdown)


def get_rich_text(feature_set: Optional[_builtins.str] = None,
                  markdown: Optional[_builtins.str] = None,
                  opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetRichTextResult:
    """
    Build a rich text document from markdown, for fields that store a document rather than a string. Use it where formatting — bold, links, lists — can't be expressed by writing the template inline. One-way: markdown in, document out.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_incident as incident

    # Build a rich text document from markdown, for a field that stores a document rather
    # than a "{{ }}" template. feature_set must match the field it's going into.
    alert_description = incident.get_rich_text(markdown=\"\"\"**Alert**: {{payload.summary}}

    Runbook: {{payload.annotations.runbook_url}}\"\"\",
        feature_set="rich")
    prometheus = incident.AlertSourceBeta("prometheus",
        name="Prometheus",
        source_type="http",
        title={
            "literal": "{{payload.labels.alertname}}",
        },
        description={
            "literal": alert_description.json,
        })
    pulumi.export("droppedContent", alert_description.dropped_contents)
    ```


    :param _builtins.str feature_set: The feature set of the field this document is destined for. Content the feature set doesn't permit is dropped, and reported in dropped_content. Possible values are: `plain_single_line`, `plain_single_line_with_secrets`, `plain_multi_line`, `mrkdwn`, `rich`, `rich_with_images`, `slack_rich_text`, `slack_rich_text_with_headings`, `basic`, `basic_no_links`, `jira`.
    :param _builtins.str markdown: The markdown to parse. Template variables written as {{ name }} become variable placeholders, and support the omit*if*unset and truncate filters.
    """
    __args__ = dict()
    __args__['featureSet'] = feature_set
    __args__['markdown'] = markdown
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('incident:index/getRichText:getRichText', __args__, opts=opts, typ=GetRichTextResult).value

    return AwaitableGetRichTextResult(
        dropped_contents=pulumi.get(__ret__, 'dropped_contents'),
        feature_set=pulumi.get(__ret__, 'feature_set'),
        json=pulumi.get(__ret__, 'json'),
        markdown=pulumi.get(__ret__, 'markdown'))
def get_rich_text_output(feature_set: pulumi.Input[Optional[_builtins.str]] = None,
                         markdown: pulumi.Input[Optional[_builtins.str]] = None,
                         opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetRichTextResult]:
    """
    Build a rich text document from markdown, for fields that store a document rather than a string. Use it where formatting — bold, links, lists — can't be expressed by writing the template inline. One-way: markdown in, document out.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_incident as incident

    # Build a rich text document from markdown, for a field that stores a document rather
    # than a "{{ }}" template. feature_set must match the field it's going into.
    alert_description = incident.get_rich_text(markdown=\"\"\"**Alert**: {{payload.summary}}

    Runbook: {{payload.annotations.runbook_url}}\"\"\",
        feature_set="rich")
    prometheus = incident.AlertSourceBeta("prometheus",
        name="Prometheus",
        source_type="http",
        title={
            "literal": "{{payload.labels.alertname}}",
        },
        description={
            "literal": alert_description.json,
        })
    pulumi.export("droppedContent", alert_description.dropped_contents)
    ```


    :param _builtins.str feature_set: The feature set of the field this document is destined for. Content the feature set doesn't permit is dropped, and reported in dropped_content. Possible values are: `plain_single_line`, `plain_single_line_with_secrets`, `plain_multi_line`, `mrkdwn`, `rich`, `rich_with_images`, `slack_rich_text`, `slack_rich_text_with_headings`, `basic`, `basic_no_links`, `jira`.
    :param _builtins.str markdown: The markdown to parse. Template variables written as {{ name }} become variable placeholders, and support the omit*if*unset and truncate filters.
    """
    __args__ = dict()
    __args__['featureSet'] = feature_set
    __args__['markdown'] = markdown
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('incident:index/getRichText:getRichText', __args__, opts=opts, typ=GetRichTextResult)
    return __ret__.apply(lambda __response__: GetRichTextResult(
        dropped_contents=pulumi.get(__response__, 'dropped_contents'),
        feature_set=pulumi.get(__response__, 'feature_set'),
        json=pulumi.get(__response__, 'json'),
        markdown=pulumi.get(__response__, 'markdown')))
