# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetScheduleResult',
    'AwaitableGetScheduleResult',
    'get_schedule',
    'get_schedule_output',
]

@pulumi.output_type
class GetScheduleResult:
    """
    A collection of values returned by getSchedule.
    """
    def __init__(__self__, id=None, name=None, team_ids=None, timezone=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if team_ids and not isinstance(team_ids, list):
            raise TypeError("Expected argument 'team_ids' to be a list")
        pulumi.set(__self__, "team_ids", team_ids)
        if timezone and not isinstance(timezone, str):
            raise TypeError("Expected argument 'timezone' to be a str")
        pulumi.set(__self__, "timezone", timezone)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        Look up the schedule by ID.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        Look up the schedule by name. Names aren't unique, so this fails if more than one schedule matches.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="teamIds")
    def team_ids(self) -> Sequence[_builtins.str]:
        """
        IDs of teams that own this schedule
        """
        return pulumi.get(self, "team_ids")

    @_builtins.property
    @pulumi.getter
    def timezone(self) -> _builtins.str:
        """
        Timezone the schedule's rotations are anchored to, as an IANA name
        """
        return pulumi.get(self, "timezone")


class AwaitableGetScheduleResult(GetScheduleResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetScheduleResult(
            id=self.id,
            name=self.name,
            team_ids=self.team_ids,
            timezone=self.timezone)


def get_schedule(id: Optional[_builtins.str] = None,
                 name: Optional[_builtins.str] = None,
                 opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetScheduleResult:
    """
    Look up a schedule by `id` or `name`. Exactly one lookup field should be set.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_incident as incident

    # Look up a schedule by name...
    platform = incident.get_schedule(name="Platform on-call")
    # ...or by ID, which is what you want if several schedules share a name.
    platform_by_id = incident.get_schedule(id="01ABC123DEF456GHI789JKL")
    ```


    :param _builtins.str id: Look up the schedule by ID.
    :param _builtins.str name: Look up the schedule by name. Names aren't unique, so this fails if more than one schedule matches.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('incident:index/getSchedule:getSchedule', __args__, opts=opts, typ=GetScheduleResult).value

    return AwaitableGetScheduleResult(
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        team_ids=pulumi.get(__ret__, 'team_ids'),
        timezone=pulumi.get(__ret__, 'timezone'))
def get_schedule_output(id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                        name: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                        opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetScheduleResult]:
    """
    Look up a schedule by `id` or `name`. Exactly one lookup field should be set.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_incident as incident

    # Look up a schedule by name...
    platform = incident.get_schedule(name="Platform on-call")
    # ...or by ID, which is what you want if several schedules share a name.
    platform_by_id = incident.get_schedule(id="01ABC123DEF456GHI789JKL")
    ```


    :param _builtins.str id: Look up the schedule by ID.
    :param _builtins.str name: Look up the schedule by name. Names aren't unique, so this fails if more than one schedule matches.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('incident:index/getSchedule:getSchedule', __args__, opts=opts, typ=GetScheduleResult)
    return __ret__.apply(lambda __response__: GetScheduleResult(
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        team_ids=pulumi.get(__response__, 'team_ids'),
        timezone=pulumi.get(__response__, 'timezone')))
