# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['IncidentFormArgs', 'IncidentForm']

@pulumi.input_type
class IncidentFormArgs:
    def __init__(__self__, *,
                 form_type: pulumi.Input[_builtins.str],
                 expressions: pulumi.Input[Optional[Sequence[pulumi.Input['IncidentFormExpressionArgs']]]] = None,
                 incident_type_id: pulumi.Input[Optional[_builtins.str]] = None,
                 lifecycle_elements: pulumi.Input[Optional[Sequence[pulumi.Input['IncidentFormLifecycleElementArgs']]]] = None,
                 unlock_in_dashboard: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        The set of arguments for constructing a IncidentForm resource.

        :param pulumi.Input[_builtins.str] form_type: Which form this is. Escalate forms are not part of this API. Possible values are: `declare`, `accept`, `update`, `resolve`, `retrospective`, `custom-fields`. A form's type cannot change, so changing this replaces the form.
        :param pulumi.Input[Sequence[pulumi.Input['IncidentFormExpressionArgs']]] expressions: Expressions available to every element's conditions and defaults. Referenced by reference, not by ID.
        :param pulumi.Input[_builtins.str] incident_type_id: The incident type this form belongs to. Unset for the organisation's default form of this type. A form cannot move to another incident type, so changing this replaces the form.
        :param pulumi.Input[Sequence[pulumi.Input['IncidentFormLifecycleElementArgs']]] lifecycle_elements: Elements on this form, in display order. List position is the order: there is no separate rank.
        :param pulumi.Input[_builtins.bool] unlock_in_dashboard: Whether to leave this resource unlocked in the incident.io dashboard, so people can edit it there. Defaults to `false`: Terraform claims what it manages, and a claimed resource cannot be edited in the dashboard. Set it to `true` to leave the resource unclaimed — pair that with `lifecycle { ignore_changes = [...] }` naming the attributes people edit, or the next apply reverts them. Setting it on a resource Terraform already claimed hands that resource back, and someone disconnecting one in the dashboard shows as no change.
        """
        pulumi.set(__self__, "form_type", form_type)
        if expressions is not None:
            pulumi.set(__self__, "expressions", expressions)
        if incident_type_id is not None:
            pulumi.set(__self__, "incident_type_id", incident_type_id)
        if lifecycle_elements is not None:
            pulumi.set(__self__, "lifecycle_elements", lifecycle_elements)
        if unlock_in_dashboard is not None:
            pulumi.set(__self__, "unlock_in_dashboard", unlock_in_dashboard)

    @_builtins.property
    @pulumi.getter(name="formType")
    def form_type(self) -> pulumi.Input[_builtins.str]:
        """
        Which form this is. Escalate forms are not part of this API. Possible values are: `declare`, `accept`, `update`, `resolve`, `retrospective`, `custom-fields`. A form's type cannot change, so changing this replaces the form.
        """
        return pulumi.get(self, "form_type")

    @form_type.setter
    def form_type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "form_type", value)

    @_builtins.property
    @pulumi.getter
    def expressions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['IncidentFormExpressionArgs']]]]:
        """
        Expressions available to every element's conditions and defaults. Referenced by reference, not by ID.
        """
        return pulumi.get(self, "expressions")

    @expressions.setter
    def expressions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['IncidentFormExpressionArgs']]]]):
        pulumi.set(self, "expressions", value)

    @_builtins.property
    @pulumi.getter(name="incidentTypeId")
    def incident_type_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The incident type this form belongs to. Unset for the organisation's default form of this type. A form cannot move to another incident type, so changing this replaces the form.
        """
        return pulumi.get(self, "incident_type_id")

    @incident_type_id.setter
    def incident_type_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "incident_type_id", value)

    @_builtins.property
    @pulumi.getter(name="lifecycleElements")
    def lifecycle_elements(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['IncidentFormLifecycleElementArgs']]]]:
        """
        Elements on this form, in display order. List position is the order: there is no separate rank.
        """
        return pulumi.get(self, "lifecycle_elements")

    @lifecycle_elements.setter
    def lifecycle_elements(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['IncidentFormLifecycleElementArgs']]]]):
        pulumi.set(self, "lifecycle_elements", value)

    @_builtins.property
    @pulumi.getter(name="unlockInDashboard")
    def unlock_in_dashboard(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to leave this resource unlocked in the incident.io dashboard, so people can edit it there. Defaults to `false`: Terraform claims what it manages, and a claimed resource cannot be edited in the dashboard. Set it to `true` to leave the resource unclaimed — pair that with `lifecycle { ignore_changes = [...] }` naming the attributes people edit, or the next apply reverts them. Setting it on a resource Terraform already claimed hands that resource back, and someone disconnecting one in the dashboard shows as no change.
        """
        return pulumi.get(self, "unlock_in_dashboard")

    @unlock_in_dashboard.setter
    def unlock_in_dashboard(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "unlock_in_dashboard", value)


@pulumi.input_type
class _IncidentFormState:
    def __init__(__self__, *,
                 expressions: pulumi.Input[Optional[Sequence[pulumi.Input['IncidentFormExpressionArgs']]]] = None,
                 form_type: pulumi.Input[Optional[_builtins.str]] = None,
                 incident_type_id: pulumi.Input[Optional[_builtins.str]] = None,
                 lifecycle_elements: pulumi.Input[Optional[Sequence[pulumi.Input['IncidentFormLifecycleElementArgs']]]] = None,
                 unlock_in_dashboard: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        Input properties used for looking up and filtering IncidentForm resources.

        :param pulumi.Input[Sequence[pulumi.Input['IncidentFormExpressionArgs']]] expressions: Expressions available to every element's conditions and defaults. Referenced by reference, not by ID.
        :param pulumi.Input[_builtins.str] form_type: Which form this is. Escalate forms are not part of this API. Possible values are: `declare`, `accept`, `update`, `resolve`, `retrospective`, `custom-fields`. A form's type cannot change, so changing this replaces the form.
        :param pulumi.Input[_builtins.str] incident_type_id: The incident type this form belongs to. Unset for the organisation's default form of this type. A form cannot move to another incident type, so changing this replaces the form.
        :param pulumi.Input[Sequence[pulumi.Input['IncidentFormLifecycleElementArgs']]] lifecycle_elements: Elements on this form, in display order. List position is the order: there is no separate rank.
        :param pulumi.Input[_builtins.bool] unlock_in_dashboard: Whether to leave this resource unlocked in the incident.io dashboard, so people can edit it there. Defaults to `false`: Terraform claims what it manages, and a claimed resource cannot be edited in the dashboard. Set it to `true` to leave the resource unclaimed — pair that with `lifecycle { ignore_changes = [...] }` naming the attributes people edit, or the next apply reverts them. Setting it on a resource Terraform already claimed hands that resource back, and someone disconnecting one in the dashboard shows as no change.
        """
        if expressions is not None:
            pulumi.set(__self__, "expressions", expressions)
        if form_type is not None:
            pulumi.set(__self__, "form_type", form_type)
        if incident_type_id is not None:
            pulumi.set(__self__, "incident_type_id", incident_type_id)
        if lifecycle_elements is not None:
            pulumi.set(__self__, "lifecycle_elements", lifecycle_elements)
        if unlock_in_dashboard is not None:
            pulumi.set(__self__, "unlock_in_dashboard", unlock_in_dashboard)

    @_builtins.property
    @pulumi.getter
    def expressions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['IncidentFormExpressionArgs']]]]:
        """
        Expressions available to every element's conditions and defaults. Referenced by reference, not by ID.
        """
        return pulumi.get(self, "expressions")

    @expressions.setter
    def expressions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['IncidentFormExpressionArgs']]]]):
        pulumi.set(self, "expressions", value)

    @_builtins.property
    @pulumi.getter(name="formType")
    def form_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Which form this is. Escalate forms are not part of this API. Possible values are: `declare`, `accept`, `update`, `resolve`, `retrospective`, `custom-fields`. A form's type cannot change, so changing this replaces the form.
        """
        return pulumi.get(self, "form_type")

    @form_type.setter
    def form_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "form_type", value)

    @_builtins.property
    @pulumi.getter(name="incidentTypeId")
    def incident_type_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The incident type this form belongs to. Unset for the organisation's default form of this type. A form cannot move to another incident type, so changing this replaces the form.
        """
        return pulumi.get(self, "incident_type_id")

    @incident_type_id.setter
    def incident_type_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "incident_type_id", value)

    @_builtins.property
    @pulumi.getter(name="lifecycleElements")
    def lifecycle_elements(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['IncidentFormLifecycleElementArgs']]]]:
        """
        Elements on this form, in display order. List position is the order: there is no separate rank.
        """
        return pulumi.get(self, "lifecycle_elements")

    @lifecycle_elements.setter
    def lifecycle_elements(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['IncidentFormLifecycleElementArgs']]]]):
        pulumi.set(self, "lifecycle_elements", value)

    @_builtins.property
    @pulumi.getter(name="unlockInDashboard")
    def unlock_in_dashboard(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to leave this resource unlocked in the incident.io dashboard, so people can edit it there. Defaults to `false`: Terraform claims what it manages, and a claimed resource cannot be edited in the dashboard. Set it to `true` to leave the resource unclaimed — pair that with `lifecycle { ignore_changes = [...] }` naming the attributes people edit, or the next apply reverts them. Setting it on a resource Terraform already claimed hands that resource back, and someone disconnecting one in the dashboard shows as no change.
        """
        return pulumi.get(self, "unlock_in_dashboard")

    @unlock_in_dashboard.setter
    def unlock_in_dashboard(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "unlock_in_dashboard", value)


@pulumi.type_token("incident:index/incidentForm:IncidentForm")
class IncidentForm(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 expressions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['IncidentFormExpressionArgs', 'IncidentFormExpressionArgsDict']]]]] = None,
                 form_type: pulumi.Input[Optional[_builtins.str]] = None,
                 incident_type_id: pulumi.Input[Optional[_builtins.str]] = None,
                 lifecycle_elements: pulumi.Input[Optional[Sequence[pulumi.Input[Union['IncidentFormLifecycleElementArgs', 'IncidentFormLifecycleElementArgsDict']]]]] = None,
                 unlock_in_dashboard: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        """
        Configure the forms used to declare, accept, update, and resolve incidents.

        Each form carries its elements and the expressions those elements can reference.
        Escalate forms are not part of this API.

        A form is one resource: its elements and the expressions they reference are written together, in
        display order, and reconciled server-side on every apply.

        Every organisation already has a default form of each lifecycle type (`declare`, `accept`, `update`, `resolve`
        and `retrospective`), which can be neither created nor deleted. To manage one, import it by ID. Destroying
        it afterwards removes it from state and hands it back to the dashboard, but the form itself remains. A form
        for a specific incident type is created and deleted like any other resource. A `custom-fields` form has no
        default, so one with no `incident_type_id` is created and deleted normally too.

        The saved form always lists the `name`, `incident_type` and `status` elements first, in that order, whatever
        order the configuration gives them. List them first, or state keeps your order while the form shows theirs.

        ## Example - A declare form for one incident type

        ```python
        import pulumi
        import pulumi_incident as incident

        # A declare form for one incident type. Elements appear in the order listed. The
        # form is reconciled as a whole on every apply, so an element dropped from this
        # list is removed from the form.
        security = incident.get_incident_type(name="Security")
        incident_lead = incident.get_incident_role(name="Incident Lead")
        affected_system = incident.CustomField("affected_system",
            name="Affected system",
            description="The system this incident affects.",
            field_type="text")
        security_declare = incident.IncidentForm("security_declare",
            form_type="declare",
            incident_type_id=security.id,
            lifecycle_elements=[
                {
                    "element_type": "name",
                },
                {
                    "element_type": "severity",
                    "required_if": "always_require",
                },
                {
                    "element_type": "incident_role",
                    "incident_role_id": incident_lead.id,
                },
                {
                    "element_type": "text",
                    "description": "**Security incidents are private by default.** Only add people who need to know.",
                },
                {
                    "element_type": "custom_field",
                    "custom_field_id": affected_system.id,
                    "placeholder": "Which system is affected?",
                    "description": "Name the service or data store, not the team.",
                    "default_value": {
                        "value_literal": "Unknown",
                    },
                },
                {
                    "element_type": "divider",
                },
                {
                    "element_type": "summary",
                    "placeholder": "What do we know so far?",
                },
            ])
        ```

        ## Example - An accept form for one incident type

        ```python
        import pulumi
        import pulumi_incident as incident

        # An accept form for one incident type: what responders fill in when they accept
        # a triage incident as real. Everything a declare form asks for is available here
        # too, except triage and visibility, which the accepted incident already has.
        customer_report = incident.get_incident_type(name="Customer report")
        comms_lead = incident.get_incident_role(name="Communications Lead")
        impact_started = incident.get_incident_timestamp(name="Impact started")
        customer_report_accept = incident.IncidentForm("customer_report_accept",
            form_type="accept",
            incident_type_id=customer_report.id,
            lifecycle_elements=[
                {
                    "element_type": "name",
                },
                {
                    "element_type": "severity",
                    "required_if": "always_require",
                },
                {
                    "element_type": "incident_role",
                    "incident_role_id": comms_lead.id,
                    "description": "Customer reports need someone owning the reply.",
                },
                {
                    "element_type": "timestamp",
                    "incident_timestamp_id": impact_started.id,
                    "description": "When the customer first saw the problem, if they said.",
                },
                {
                    "element_type": "summary",
                },
            ])
        ```

        ## Example - A resolve form with investigation feedback

        ```python
        import pulumi
        import pulumi_incident as incident

        # A resolve form for one incident type. It collects what is only known at the
        # end: when the fix landed, and feedback on the investigation.
        production_outage = incident.get_incident_type(name="Production Outage")
        fixed = incident.get_incident_timestamp(name="Fixed")
        root_cause = incident.CustomField("root_cause",
            name="Root cause",
            description="One line on what went wrong.",
            field_type="text")
        production_outage_resolve = incident.IncidentForm("production_outage_resolve",
            form_type="resolve",
            incident_type_id=production_outage.id,
            lifecycle_elements=[
                {
                    "element_type": "timestamp",
                    "incident_timestamp_id": fixed.id,
                    "required_if": "always_require",
                },
                {
                    "element_type": "custom_field",
                    "custom_field_id": root_cause.id,
                    "required_if": "always_require",
                    "placeholder": "What went wrong?",
                },
                {
                    "element_type": "summary",
                    "description": "Update the summary to say how it was resolved.",
                },
                {
                    "element_type": "investigation_feedback",
                    "config": {
                        "require_comment": True,
                    },
                },
            ])
        ```

        ## Example - A retrospective form

        ```python
        import pulumi
        import pulumi_incident as incident

        # A retrospective form for one incident type: the form for logging an incident
        # after the fact. It has elements no other form has, for the channel to create
        # and the post-incident flow to start.
        near_miss = incident.get_incident_type(name="Near miss")
        impact_started = incident.get_incident_timestamp(name="Impact started")
        impact_ended = incident.get_incident_timestamp(name="Impact ended")
        near_miss_retrospective = incident.IncidentForm("near_miss_retrospective",
            form_type="retrospective",
            incident_type_id=near_miss.id,
            lifecycle_elements=[
                {
                    "element_type": "name",
                },
                {
                    "element_type": "incident_type",
                },
                {
                    "element_type": "severity",
                },
                {
                    "element_type": "timestamp",
                    "incident_timestamp_id": impact_started.id,
                    "required_if": "always_require",
                },
                {
                    "element_type": "timestamp",
                    "incident_timestamp_id": impact_ended.id,
                    "required_if": "always_require",
                },
                {
                    "element_type": "summary",
                },
                {
                    "element_type": "divider",
                },
                {
                    "element_type": "slack_channel",
                },
                {
                    "element_type": "announce_retro_incident",
                },
                {
                    "element_type": "enter_post_incident_flow",
                    "description": "Near misses skip the post-incident flow unless something needs following up.",
                },
            ])
        ```

        ## Example - A custom-fields form with conditional requirements

        ```python
        import pulumi
        import pulumi_incident as incident

        # A custom-fields form holds the fields shown in the incident sidebar. It is the
        # one lifecycle form with no default. This one has no incident_type_id, so it
        # applies to every incident type without a form of its own.
        ticket = incident.CustomField("ticket",
            name="Ticket",
            description="The ticket tracking this incident.",
            field_type="link")
        customer_impact = incident.CustomField("customer_impact",
            name="Customer impact",
            description="How customers were affected.",
            field_type="single_select")
        customer_impact_none = incident.CustomFieldOption("customer_impact_none",
            custom_field_id=customer_impact.id,
            value="None")
        custom_fields = incident.IncidentForm("custom_fields",
            form_type="custom-fields",
            lifecycle_elements=[
                {
                    "element_type": "custom_field",
                    "custom_field_id": ticket.id,
                },
                {
                    "element_type": "custom_field",
                    "custom_field_id": customer_impact.id,
                    "required_if": "check_engine_config",
                    "required_if_condition_groups": [{
                        "conditions": [{
                            "subject": "incident.status.category",
                            "operation": "one_of",
                            "param_bindings": [{
                                "array_value": [{
                                    "literal": "closed",
                                }],
                            }],
                        }],
                    }],
                    "default_value": {
                        "value_literal": customer_impact_none.id,
                    },
                    "can_select_no_value": True,
                },
            ])
        ```

        ## Example - A custom-fields form for one incident type

        ```python
        import pulumi
        import pulumi_incident as incident

        # A custom-fields form for one incident type, overriding the organisation-wide
        # one: security incidents show a different set of fields in the sidebar.
        security = incident.get_incident_type(name="Security")
        data_exposed = incident.CustomField("data_exposed",
            name="Data exposed",
            description="Whether customer data was exposed.",
            field_type="bool")
        cve = incident.CustomField("cve",
            name="CVE",
            description="The CVE this incident relates to, if any.",
            field_type="text")
        security_custom_fields = incident.IncidentForm("security_custom_fields",
            form_type="custom-fields",
            incident_type_id=security.id,
            lifecycle_elements=[
                {
                    "element_type": "custom_field",
                    "custom_field_id": data_exposed.id,
                    "required_if": "always_require",
                },
                {
                    "element_type": "custom_field",
                    "custom_field_id": cve.id,
                    "placeholder": "CVE-2026-...",
                },
            ])
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Union['IncidentFormExpressionArgs', 'IncidentFormExpressionArgsDict']]]] expressions: Expressions available to every element's conditions and defaults. Referenced by reference, not by ID.
        :param pulumi.Input[_builtins.str] form_type: Which form this is. Escalate forms are not part of this API. Possible values are: `declare`, `accept`, `update`, `resolve`, `retrospective`, `custom-fields`. A form's type cannot change, so changing this replaces the form.
        :param pulumi.Input[_builtins.str] incident_type_id: The incident type this form belongs to. Unset for the organisation's default form of this type. A form cannot move to another incident type, so changing this replaces the form.
        :param pulumi.Input[Sequence[pulumi.Input[Union['IncidentFormLifecycleElementArgs', 'IncidentFormLifecycleElementArgsDict']]]] lifecycle_elements: Elements on this form, in display order. List position is the order: there is no separate rank.
        :param pulumi.Input[_builtins.bool] unlock_in_dashboard: Whether to leave this resource unlocked in the incident.io dashboard, so people can edit it there. Defaults to `false`: Terraform claims what it manages, and a claimed resource cannot be edited in the dashboard. Set it to `true` to leave the resource unclaimed — pair that with `lifecycle { ignore_changes = [...] }` naming the attributes people edit, or the next apply reverts them. Setting it on a resource Terraform already claimed hands that resource back, and someone disconnecting one in the dashboard shows as no change.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: IncidentFormArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Configure the forms used to declare, accept, update, and resolve incidents.

        Each form carries its elements and the expressions those elements can reference.
        Escalate forms are not part of this API.

        A form is one resource: its elements and the expressions they reference are written together, in
        display order, and reconciled server-side on every apply.

        Every organisation already has a default form of each lifecycle type (`declare`, `accept`, `update`, `resolve`
        and `retrospective`), which can be neither created nor deleted. To manage one, import it by ID. Destroying
        it afterwards removes it from state and hands it back to the dashboard, but the form itself remains. A form
        for a specific incident type is created and deleted like any other resource. A `custom-fields` form has no
        default, so one with no `incident_type_id` is created and deleted normally too.

        The saved form always lists the `name`, `incident_type` and `status` elements first, in that order, whatever
        order the configuration gives them. List them first, or state keeps your order while the form shows theirs.

        ## Example - A declare form for one incident type

        ```python
        import pulumi
        import pulumi_incident as incident

        # A declare form for one incident type. Elements appear in the order listed. The
        # form is reconciled as a whole on every apply, so an element dropped from this
        # list is removed from the form.
        security = incident.get_incident_type(name="Security")
        incident_lead = incident.get_incident_role(name="Incident Lead")
        affected_system = incident.CustomField("affected_system",
            name="Affected system",
            description="The system this incident affects.",
            field_type="text")
        security_declare = incident.IncidentForm("security_declare",
            form_type="declare",
            incident_type_id=security.id,
            lifecycle_elements=[
                {
                    "element_type": "name",
                },
                {
                    "element_type": "severity",
                    "required_if": "always_require",
                },
                {
                    "element_type": "incident_role",
                    "incident_role_id": incident_lead.id,
                },
                {
                    "element_type": "text",
                    "description": "**Security incidents are private by default.** Only add people who need to know.",
                },
                {
                    "element_type": "custom_field",
                    "custom_field_id": affected_system.id,
                    "placeholder": "Which system is affected?",
                    "description": "Name the service or data store, not the team.",
                    "default_value": {
                        "value_literal": "Unknown",
                    },
                },
                {
                    "element_type": "divider",
                },
                {
                    "element_type": "summary",
                    "placeholder": "What do we know so far?",
                },
            ])
        ```

        ## Example - An accept form for one incident type

        ```python
        import pulumi
        import pulumi_incident as incident

        # An accept form for one incident type: what responders fill in when they accept
        # a triage incident as real. Everything a declare form asks for is available here
        # too, except triage and visibility, which the accepted incident already has.
        customer_report = incident.get_incident_type(name="Customer report")
        comms_lead = incident.get_incident_role(name="Communications Lead")
        impact_started = incident.get_incident_timestamp(name="Impact started")
        customer_report_accept = incident.IncidentForm("customer_report_accept",
            form_type="accept",
            incident_type_id=customer_report.id,
            lifecycle_elements=[
                {
                    "element_type": "name",
                },
                {
                    "element_type": "severity",
                    "required_if": "always_require",
                },
                {
                    "element_type": "incident_role",
                    "incident_role_id": comms_lead.id,
                    "description": "Customer reports need someone owning the reply.",
                },
                {
                    "element_type": "timestamp",
                    "incident_timestamp_id": impact_started.id,
                    "description": "When the customer first saw the problem, if they said.",
                },
                {
                    "element_type": "summary",
                },
            ])
        ```

        ## Example - A resolve form with investigation feedback

        ```python
        import pulumi
        import pulumi_incident as incident

        # A resolve form for one incident type. It collects what is only known at the
        # end: when the fix landed, and feedback on the investigation.
        production_outage = incident.get_incident_type(name="Production Outage")
        fixed = incident.get_incident_timestamp(name="Fixed")
        root_cause = incident.CustomField("root_cause",
            name="Root cause",
            description="One line on what went wrong.",
            field_type="text")
        production_outage_resolve = incident.IncidentForm("production_outage_resolve",
            form_type="resolve",
            incident_type_id=production_outage.id,
            lifecycle_elements=[
                {
                    "element_type": "timestamp",
                    "incident_timestamp_id": fixed.id,
                    "required_if": "always_require",
                },
                {
                    "element_type": "custom_field",
                    "custom_field_id": root_cause.id,
                    "required_if": "always_require",
                    "placeholder": "What went wrong?",
                },
                {
                    "element_type": "summary",
                    "description": "Update the summary to say how it was resolved.",
                },
                {
                    "element_type": "investigation_feedback",
                    "config": {
                        "require_comment": True,
                    },
                },
            ])
        ```

        ## Example - A retrospective form

        ```python
        import pulumi
        import pulumi_incident as incident

        # A retrospective form for one incident type: the form for logging an incident
        # after the fact. It has elements no other form has, for the channel to create
        # and the post-incident flow to start.
        near_miss = incident.get_incident_type(name="Near miss")
        impact_started = incident.get_incident_timestamp(name="Impact started")
        impact_ended = incident.get_incident_timestamp(name="Impact ended")
        near_miss_retrospective = incident.IncidentForm("near_miss_retrospective",
            form_type="retrospective",
            incident_type_id=near_miss.id,
            lifecycle_elements=[
                {
                    "element_type": "name",
                },
                {
                    "element_type": "incident_type",
                },
                {
                    "element_type": "severity",
                },
                {
                    "element_type": "timestamp",
                    "incident_timestamp_id": impact_started.id,
                    "required_if": "always_require",
                },
                {
                    "element_type": "timestamp",
                    "incident_timestamp_id": impact_ended.id,
                    "required_if": "always_require",
                },
                {
                    "element_type": "summary",
                },
                {
                    "element_type": "divider",
                },
                {
                    "element_type": "slack_channel",
                },
                {
                    "element_type": "announce_retro_incident",
                },
                {
                    "element_type": "enter_post_incident_flow",
                    "description": "Near misses skip the post-incident flow unless something needs following up.",
                },
            ])
        ```

        ## Example - A custom-fields form with conditional requirements

        ```python
        import pulumi
        import pulumi_incident as incident

        # A custom-fields form holds the fields shown in the incident sidebar. It is the
        # one lifecycle form with no default. This one has no incident_type_id, so it
        # applies to every incident type without a form of its own.
        ticket = incident.CustomField("ticket",
            name="Ticket",
            description="The ticket tracking this incident.",
            field_type="link")
        customer_impact = incident.CustomField("customer_impact",
            name="Customer impact",
            description="How customers were affected.",
            field_type="single_select")
        customer_impact_none = incident.CustomFieldOption("customer_impact_none",
            custom_field_id=customer_impact.id,
            value="None")
        custom_fields = incident.IncidentForm("custom_fields",
            form_type="custom-fields",
            lifecycle_elements=[
                {
                    "element_type": "custom_field",
                    "custom_field_id": ticket.id,
                },
                {
                    "element_type": "custom_field",
                    "custom_field_id": customer_impact.id,
                    "required_if": "check_engine_config",
                    "required_if_condition_groups": [{
                        "conditions": [{
                            "subject": "incident.status.category",
                            "operation": "one_of",
                            "param_bindings": [{
                                "array_value": [{
                                    "literal": "closed",
                                }],
                            }],
                        }],
                    }],
                    "default_value": {
                        "value_literal": customer_impact_none.id,
                    },
                    "can_select_no_value": True,
                },
            ])
        ```

        ## Example - A custom-fields form for one incident type

        ```python
        import pulumi
        import pulumi_incident as incident

        # A custom-fields form for one incident type, overriding the organisation-wide
        # one: security incidents show a different set of fields in the sidebar.
        security = incident.get_incident_type(name="Security")
        data_exposed = incident.CustomField("data_exposed",
            name="Data exposed",
            description="Whether customer data was exposed.",
            field_type="bool")
        cve = incident.CustomField("cve",
            name="CVE",
            description="The CVE this incident relates to, if any.",
            field_type="text")
        security_custom_fields = incident.IncidentForm("security_custom_fields",
            form_type="custom-fields",
            incident_type_id=security.id,
            lifecycle_elements=[
                {
                    "element_type": "custom_field",
                    "custom_field_id": data_exposed.id,
                    "required_if": "always_require",
                },
                {
                    "element_type": "custom_field",
                    "custom_field_id": cve.id,
                    "placeholder": "CVE-2026-...",
                },
            ])
        ```


        :param str resource_name: The name of the resource.
        :param IncidentFormArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(IncidentFormArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 expressions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['IncidentFormExpressionArgs', 'IncidentFormExpressionArgsDict']]]]] = None,
                 form_type: pulumi.Input[Optional[_builtins.str]] = None,
                 incident_type_id: pulumi.Input[Optional[_builtins.str]] = None,
                 lifecycle_elements: pulumi.Input[Optional[Sequence[pulumi.Input[Union['IncidentFormLifecycleElementArgs', 'IncidentFormLifecycleElementArgsDict']]]]] = None,
                 unlock_in_dashboard: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = IncidentFormArgs.__new__(IncidentFormArgs)

            __props__.__dict__["expressions"] = expressions
            if form_type is None and not opts.urn:
                raise TypeError("Missing required property 'form_type'")
            __props__.__dict__["form_type"] = form_type
            __props__.__dict__["incident_type_id"] = incident_type_id
            __props__.__dict__["lifecycle_elements"] = lifecycle_elements
            __props__.__dict__["unlock_in_dashboard"] = unlock_in_dashboard
        super(IncidentForm, __self__).__init__(
            'incident:index/incidentForm:IncidentForm',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            expressions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['IncidentFormExpressionArgs', 'IncidentFormExpressionArgsDict']]]]] = None,
            form_type: pulumi.Input[Optional[_builtins.str]] = None,
            incident_type_id: pulumi.Input[Optional[_builtins.str]] = None,
            lifecycle_elements: pulumi.Input[Optional[Sequence[pulumi.Input[Union['IncidentFormLifecycleElementArgs', 'IncidentFormLifecycleElementArgsDict']]]]] = None,
            unlock_in_dashboard: pulumi.Input[Optional[_builtins.bool]] = None) -> 'IncidentForm':
        """
        Get an existing IncidentForm resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Union['IncidentFormExpressionArgs', 'IncidentFormExpressionArgsDict']]]] expressions: Expressions available to every element's conditions and defaults. Referenced by reference, not by ID.
        :param pulumi.Input[_builtins.str] form_type: Which form this is. Escalate forms are not part of this API. Possible values are: `declare`, `accept`, `update`, `resolve`, `retrospective`, `custom-fields`. A form's type cannot change, so changing this replaces the form.
        :param pulumi.Input[_builtins.str] incident_type_id: The incident type this form belongs to. Unset for the organisation's default form of this type. A form cannot move to another incident type, so changing this replaces the form.
        :param pulumi.Input[Sequence[pulumi.Input[Union['IncidentFormLifecycleElementArgs', 'IncidentFormLifecycleElementArgsDict']]]] lifecycle_elements: Elements on this form, in display order. List position is the order: there is no separate rank.
        :param pulumi.Input[_builtins.bool] unlock_in_dashboard: Whether to leave this resource unlocked in the incident.io dashboard, so people can edit it there. Defaults to `false`: Terraform claims what it manages, and a claimed resource cannot be edited in the dashboard. Set it to `true` to leave the resource unclaimed — pair that with `lifecycle { ignore_changes = [...] }` naming the attributes people edit, or the next apply reverts them. Setting it on a resource Terraform already claimed hands that resource back, and someone disconnecting one in the dashboard shows as no change.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _IncidentFormState.__new__(_IncidentFormState)

        __props__.__dict__["expressions"] = expressions
        __props__.__dict__["form_type"] = form_type
        __props__.__dict__["incident_type_id"] = incident_type_id
        __props__.__dict__["lifecycle_elements"] = lifecycle_elements
        __props__.__dict__["unlock_in_dashboard"] = unlock_in_dashboard
        return IncidentForm(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def expressions(self) -> pulumi.Output[Optional[Sequence['outputs.IncidentFormExpression']]]:
        """
        Expressions available to every element's conditions and defaults. Referenced by reference, not by ID.
        """
        return pulumi.get(self, "expressions")

    @_builtins.property
    @pulumi.getter(name="formType")
    def form_type(self) -> pulumi.Output[_builtins.str]:
        """
        Which form this is. Escalate forms are not part of this API. Possible values are: `declare`, `accept`, `update`, `resolve`, `retrospective`, `custom-fields`. A form's type cannot change, so changing this replaces the form.
        """
        return pulumi.get(self, "form_type")

    @_builtins.property
    @pulumi.getter(name="incidentTypeId")
    def incident_type_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The incident type this form belongs to. Unset for the organisation's default form of this type. A form cannot move to another incident type, so changing this replaces the form.
        """
        return pulumi.get(self, "incident_type_id")

    @_builtins.property
    @pulumi.getter(name="lifecycleElements")
    def lifecycle_elements(self) -> pulumi.Output[Optional[Sequence['outputs.IncidentFormLifecycleElement']]]:
        """
        Elements on this form, in display order. List position is the order: there is no separate rank.
        """
        return pulumi.get(self, "lifecycle_elements")

    @_builtins.property
    @pulumi.getter(name="unlockInDashboard")
    def unlock_in_dashboard(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether to leave this resource unlocked in the incident.io dashboard, so people can edit it there. Defaults to `false`: Terraform claims what it manages, and a claimed resource cannot be edited in the dashboard. Set it to `true` to leave the resource unclaimed — pair that with `lifecycle { ignore_changes = [...] }` naming the attributes people edit, or the next apply reverts them. Setting it on a resource Terraform already claimed hands that resource back, and someone disconnecting one in the dashboard shows as no change.
        """
        return pulumi.get(self, "unlock_in_dashboard")

