# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ScheduleArgs', 'Schedule']

@pulumi.input_type
class ScheduleArgs:
    def __init__(__self__, *,
                 rotations: pulumi.Input[Sequence[pulumi.Input['ScheduleRotationArgs']]],
                 timezone: pulumi.Input[_builtins.str],
                 holidays_public_config: pulumi.Input[Optional['ScheduleHolidaysPublicConfigArgs']] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 team_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a Schedule resource.

        :param pulumi.Input[_builtins.str] name: Human readable name synced from external provider
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] team_ids: IDs of teams that own this schedule
        """
        pulumi.set(__self__, "rotations", rotations)
        pulumi.set(__self__, "timezone", timezone)
        if holidays_public_config is not None:
            pulumi.set(__self__, "holidays_public_config", holidays_public_config)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if team_ids is not None:
            pulumi.set(__self__, "team_ids", team_ids)

    @_builtins.property
    @pulumi.getter
    def rotations(self) -> pulumi.Input[Sequence[pulumi.Input['ScheduleRotationArgs']]]:
        return pulumi.get(self, "rotations")

    @rotations.setter
    def rotations(self, value: pulumi.Input[Sequence[pulumi.Input['ScheduleRotationArgs']]]):
        pulumi.set(self, "rotations", value)

    @_builtins.property
    @pulumi.getter
    def timezone(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "timezone")

    @timezone.setter
    def timezone(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "timezone", value)

    @_builtins.property
    @pulumi.getter(name="holidaysPublicConfig")
    def holidays_public_config(self) -> pulumi.Input[Optional['ScheduleHolidaysPublicConfigArgs']]:
        return pulumi.get(self, "holidays_public_config")

    @holidays_public_config.setter
    def holidays_public_config(self, value: pulumi.Input[Optional['ScheduleHolidaysPublicConfigArgs']]):
        pulumi.set(self, "holidays_public_config", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human readable name synced from external provider
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="teamIds")
    def team_ids(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        IDs of teams that own this schedule
        """
        return pulumi.get(self, "team_ids")

    @team_ids.setter
    def team_ids(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "team_ids", value)


@pulumi.input_type
class _ScheduleState:
    def __init__(__self__, *,
                 holidays_public_config: pulumi.Input[Optional['ScheduleHolidaysPublicConfigArgs']] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 rotations: pulumi.Input[Optional[Sequence[pulumi.Input['ScheduleRotationArgs']]]] = None,
                 team_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 timezone: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Schedule resources.

        :param pulumi.Input[_builtins.str] name: Human readable name synced from external provider
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] team_ids: IDs of teams that own this schedule
        """
        if holidays_public_config is not None:
            pulumi.set(__self__, "holidays_public_config", holidays_public_config)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if rotations is not None:
            pulumi.set(__self__, "rotations", rotations)
        if team_ids is not None:
            pulumi.set(__self__, "team_ids", team_ids)
        if timezone is not None:
            pulumi.set(__self__, "timezone", timezone)

    @_builtins.property
    @pulumi.getter(name="holidaysPublicConfig")
    def holidays_public_config(self) -> pulumi.Input[Optional['ScheduleHolidaysPublicConfigArgs']]:
        return pulumi.get(self, "holidays_public_config")

    @holidays_public_config.setter
    def holidays_public_config(self, value: pulumi.Input[Optional['ScheduleHolidaysPublicConfigArgs']]):
        pulumi.set(self, "holidays_public_config", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human readable name synced from external provider
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def rotations(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['ScheduleRotationArgs']]]]:
        return pulumi.get(self, "rotations")

    @rotations.setter
    def rotations(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['ScheduleRotationArgs']]]]):
        pulumi.set(self, "rotations", value)

    @_builtins.property
    @pulumi.getter(name="teamIds")
    def team_ids(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        IDs of teams that own this schedule
        """
        return pulumi.get(self, "team_ids")

    @team_ids.setter
    def team_ids(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "team_ids", value)

    @_builtins.property
    @pulumi.getter
    def timezone(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "timezone")

    @timezone.setter
    def timezone(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "timezone", value)


@pulumi.type_token("incident:index/schedule:Schedule")
class Schedule(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 holidays_public_config: pulumi.Input[Optional[Union['ScheduleHolidaysPublicConfigArgs', 'ScheduleHolidaysPublicConfigArgsDict']]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 rotations: pulumi.Input[Optional[Sequence[pulumi.Input[Union['ScheduleRotationArgs', 'ScheduleRotationArgsDict']]]]] = None,
                 team_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 timezone: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        View and manage schedules.
        Manage your full schedule of on-call rotations, including the users and rotation configuration.

        We'd generally recommend building schedules in our [web dashboard](https://app.incident.io/~/on-call/schedules), and using the 'Export' flow to generate your Terraform, as it's easier to see what you've configured. You can also make changes to an existing schedule and copy the resulting Terraform without persisting it.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_incident as incident

        rory = incident.get_user(id="01HPFH8T92MPGSQS5C1SPAF4V0")
        martha = incident.get_user(slack_user_id="U01HJ1J2Z6Z")
        # This allows lookups by email, slack user ID, or user ID
        roryb = incident.get_user(email="rory@incident.io")
        # This is exportable from the incident.io dashboard as a Terraform configuration
        primary_on_call = incident.Schedule("primary_on_call",
            name="Primary On-call",
            timezone="Europe/London",
            rotations=[{
                "id": "testing-terraform",
                "name": "Testing Terraform",
                "versions": [
                    {
                        "handover_start_at": "2024-05-01T12:54:13Z",
                        "users": [martha.id],
                        "layers": [{
                            "id": "primary",
                            "name": "Primary",
                        }],
                        "handovers": [{
                            "interval_type": "daily",
                            "interval": 1,
                        }],
                    },
                    {
                        "effective_from": "2024-05-14T12:54:13Z",
                        "handover_start_at": "2024-05-01T12:54:13Z",
                        "users": [
                            martha.id,
                            rory.id,
                        ],
                        "layers": [{
                            "id": "primary",
                            "name": "Primary",
                        }],
                        "handovers": [{
                            "interval_type": "weekly",
                            "interval": 1,
                        }],
                    },
                ],
            }],
            holidays_public_config={
                "country_codes": [
                    "GB",
                    "FR",
                ],
            })
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        !/bin/bash

        Import a schedule using its ID
        Replace the ID with a real ID from your incident.io organization

        ```sh
        $ pulumi import incident:index/schedule:Schedule example 01ABC123DEF456GHI789JKL
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] name: Human readable name synced from external provider
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] team_ids: IDs of teams that own this schedule
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ScheduleArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        View and manage schedules.
        Manage your full schedule of on-call rotations, including the users and rotation configuration.

        We'd generally recommend building schedules in our [web dashboard](https://app.incident.io/~/on-call/schedules), and using the 'Export' flow to generate your Terraform, as it's easier to see what you've configured. You can also make changes to an existing schedule and copy the resulting Terraform without persisting it.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_incident as incident

        rory = incident.get_user(id="01HPFH8T92MPGSQS5C1SPAF4V0")
        martha = incident.get_user(slack_user_id="U01HJ1J2Z6Z")
        # This allows lookups by email, slack user ID, or user ID
        roryb = incident.get_user(email="rory@incident.io")
        # This is exportable from the incident.io dashboard as a Terraform configuration
        primary_on_call = incident.Schedule("primary_on_call",
            name="Primary On-call",
            timezone="Europe/London",
            rotations=[{
                "id": "testing-terraform",
                "name": "Testing Terraform",
                "versions": [
                    {
                        "handover_start_at": "2024-05-01T12:54:13Z",
                        "users": [martha.id],
                        "layers": [{
                            "id": "primary",
                            "name": "Primary",
                        }],
                        "handovers": [{
                            "interval_type": "daily",
                            "interval": 1,
                        }],
                    },
                    {
                        "effective_from": "2024-05-14T12:54:13Z",
                        "handover_start_at": "2024-05-01T12:54:13Z",
                        "users": [
                            martha.id,
                            rory.id,
                        ],
                        "layers": [{
                            "id": "primary",
                            "name": "Primary",
                        }],
                        "handovers": [{
                            "interval_type": "weekly",
                            "interval": 1,
                        }],
                    },
                ],
            }],
            holidays_public_config={
                "country_codes": [
                    "GB",
                    "FR",
                ],
            })
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        !/bin/bash

        Import a schedule using its ID
        Replace the ID with a real ID from your incident.io organization

        ```sh
        $ pulumi import incident:index/schedule:Schedule example 01ABC123DEF456GHI789JKL
        ```


        :param str resource_name: The name of the resource.
        :param ScheduleArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ScheduleArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 holidays_public_config: pulumi.Input[Optional[Union['ScheduleHolidaysPublicConfigArgs', 'ScheduleHolidaysPublicConfigArgsDict']]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 rotations: pulumi.Input[Optional[Sequence[pulumi.Input[Union['ScheduleRotationArgs', 'ScheduleRotationArgsDict']]]]] = None,
                 team_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 timezone: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ScheduleArgs.__new__(ScheduleArgs)

            __props__.__dict__["holidays_public_config"] = holidays_public_config
            __props__.__dict__["name"] = name
            if rotations is None and not opts.urn:
                raise TypeError("Missing required property 'rotations'")
            __props__.__dict__["rotations"] = rotations
            __props__.__dict__["team_ids"] = team_ids
            if timezone is None and not opts.urn:
                raise TypeError("Missing required property 'timezone'")
            __props__.__dict__["timezone"] = timezone
        super(Schedule, __self__).__init__(
            'incident:index/schedule:Schedule',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            holidays_public_config: pulumi.Input[Optional[Union['ScheduleHolidaysPublicConfigArgs', 'ScheduleHolidaysPublicConfigArgsDict']]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            rotations: pulumi.Input[Optional[Sequence[pulumi.Input[Union['ScheduleRotationArgs', 'ScheduleRotationArgsDict']]]]] = None,
            team_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            timezone: pulumi.Input[Optional[_builtins.str]] = None) -> 'Schedule':
        """
        Get an existing Schedule resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] name: Human readable name synced from external provider
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] team_ids: IDs of teams that own this schedule
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ScheduleState.__new__(_ScheduleState)

        __props__.__dict__["holidays_public_config"] = holidays_public_config
        __props__.__dict__["name"] = name
        __props__.__dict__["rotations"] = rotations
        __props__.__dict__["team_ids"] = team_ids
        __props__.__dict__["timezone"] = timezone
        return Schedule(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="holidaysPublicConfig")
    def holidays_public_config(self) -> pulumi.Output[Optional['outputs.ScheduleHolidaysPublicConfig']]:
        return pulumi.get(self, "holidays_public_config")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Human readable name synced from external provider
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def rotations(self) -> pulumi.Output[Sequence['outputs.ScheduleRotation']]:
        return pulumi.get(self, "rotations")

    @_builtins.property
    @pulumi.getter(name="teamIds")
    def team_ids(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        IDs of teams that own this schedule
        """
        return pulumi.get(self, "team_ids")

    @_builtins.property
    @pulumi.getter
    def timezone(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "timezone")

