# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ScheduleArgs', 'Schedule']

@pulumi.input_type
class ScheduleArgs:
    def __init__(__self__, *,
                 timezone: pulumi.Input[_builtins.str],
                 holidays_public_config: pulumi.Input[Optional['ScheduleHolidaysPublicConfigArgs']] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 team_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a Schedule resource.

        :param pulumi.Input[_builtins.str] timezone: Timezone the schedule's rotations are anchored to, as an IANA name. Changing this replaces the schedule: a timezone is what its rotations are anchored to, and we don't support moving an existing schedule to another one.
        :param pulumi.Input['ScheduleHolidaysPublicConfigArgs'] holidays_public_config: Public holidays to show on this schedule. Omit the block entirely to show none.
        :param pulumi.Input[_builtins.str] name: Human readable name for the schedule
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] team_ids: IDs of teams that own this schedule
        """
        pulumi.set(__self__, "timezone", timezone)
        if holidays_public_config is not None:
            pulumi.set(__self__, "holidays_public_config", holidays_public_config)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if team_ids is not None:
            pulumi.set(__self__, "team_ids", team_ids)

    @_builtins.property
    @pulumi.getter
    def timezone(self) -> pulumi.Input[_builtins.str]:
        """
        Timezone the schedule's rotations are anchored to, as an IANA name. Changing this replaces the schedule: a timezone is what its rotations are anchored to, and we don't support moving an existing schedule to another one.
        """
        return pulumi.get(self, "timezone")

    @timezone.setter
    def timezone(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "timezone", value)

    @_builtins.property
    @pulumi.getter(name="holidaysPublicConfig")
    def holidays_public_config(self) -> pulumi.Input[Optional['ScheduleHolidaysPublicConfigArgs']]:
        """
        Public holidays to show on this schedule. Omit the block entirely to show none.
        """
        return pulumi.get(self, "holidays_public_config")

    @holidays_public_config.setter
    def holidays_public_config(self, value: pulumi.Input[Optional['ScheduleHolidaysPublicConfigArgs']]):
        pulumi.set(self, "holidays_public_config", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human readable name for the schedule
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="teamIds")
    def team_ids(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        IDs of teams that own this schedule
        """
        return pulumi.get(self, "team_ids")

    @team_ids.setter
    def team_ids(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "team_ids", value)


@pulumi.input_type
class _ScheduleState:
    def __init__(__self__, *,
                 holidays_public_config: pulumi.Input[Optional['ScheduleHolidaysPublicConfigArgs']] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 team_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 timezone: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Schedule resources.

        :param pulumi.Input['ScheduleHolidaysPublicConfigArgs'] holidays_public_config: Public holidays to show on this schedule. Omit the block entirely to show none.
        :param pulumi.Input[_builtins.str] name: Human readable name for the schedule
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] team_ids: IDs of teams that own this schedule
        :param pulumi.Input[_builtins.str] timezone: Timezone the schedule's rotations are anchored to, as an IANA name. Changing this replaces the schedule: a timezone is what its rotations are anchored to, and we don't support moving an existing schedule to another one.
        """
        if holidays_public_config is not None:
            pulumi.set(__self__, "holidays_public_config", holidays_public_config)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if team_ids is not None:
            pulumi.set(__self__, "team_ids", team_ids)
        if timezone is not None:
            pulumi.set(__self__, "timezone", timezone)

    @_builtins.property
    @pulumi.getter(name="holidaysPublicConfig")
    def holidays_public_config(self) -> pulumi.Input[Optional['ScheduleHolidaysPublicConfigArgs']]:
        """
        Public holidays to show on this schedule. Omit the block entirely to show none.
        """
        return pulumi.get(self, "holidays_public_config")

    @holidays_public_config.setter
    def holidays_public_config(self, value: pulumi.Input[Optional['ScheduleHolidaysPublicConfigArgs']]):
        pulumi.set(self, "holidays_public_config", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human readable name for the schedule
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="teamIds")
    def team_ids(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        IDs of teams that own this schedule
        """
        return pulumi.get(self, "team_ids")

    @team_ids.setter
    def team_ids(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "team_ids", value)

    @_builtins.property
    @pulumi.getter
    def timezone(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Timezone the schedule's rotations are anchored to, as an IANA name. Changing this replaces the schedule: a timezone is what its rotations are anchored to, and we don't support moving an existing schedule to another one.
        """
        return pulumi.get(self, "timezone")

    @timezone.setter
    def timezone(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "timezone", value)


@pulumi.type_token("incident:index/schedule:Schedule")
class Schedule(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 holidays_public_config: pulumi.Input[Optional[Union['ScheduleHolidaysPublicConfigArgs', 'ScheduleHolidaysPublicConfigArgsDict']]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 team_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 timezone: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Manage an on-call schedule.

        A schedule holds the rotations that decide who is on call. This resource manages
        only the schedule itself — its name, timezone, owning teams and public holidays.
        Rotations are managed separately, as `ScheduleRotation`, so
        adding or editing one never means rewriting the whole schedule.

        A schedule created here starts with no rotations, and nobody is on call until one
        is added.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_incident as incident

        # A schedule holds the rotations that decide who is on call. This resource covers
        # the schedule itself; rotations are managed separately, so a schedule created
        # here has none and nobody is on call until one is added.
        platform = incident.Schedule("platform",
            name="Platform on-call",
            timezone="Europe/London",
            team_ids=[platform_team["id"]],
            holidays_public_config={
                "country_codes": [
                    "GB",
                    "FR",
                ],
            })
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['ScheduleHolidaysPublicConfigArgs', 'ScheduleHolidaysPublicConfigArgsDict']] holidays_public_config: Public holidays to show on this schedule. Omit the block entirely to show none.
        :param pulumi.Input[_builtins.str] name: Human readable name for the schedule
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] team_ids: IDs of teams that own this schedule
        :param pulumi.Input[_builtins.str] timezone: Timezone the schedule's rotations are anchored to, as an IANA name. Changing this replaces the schedule: a timezone is what its rotations are anchored to, and we don't support moving an existing schedule to another one.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ScheduleArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manage an on-call schedule.

        A schedule holds the rotations that decide who is on call. This resource manages
        only the schedule itself — its name, timezone, owning teams and public holidays.
        Rotations are managed separately, as `ScheduleRotation`, so
        adding or editing one never means rewriting the whole schedule.

        A schedule created here starts with no rotations, and nobody is on call until one
        is added.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_incident as incident

        # A schedule holds the rotations that decide who is on call. This resource covers
        # the schedule itself; rotations are managed separately, so a schedule created
        # here has none and nobody is on call until one is added.
        platform = incident.Schedule("platform",
            name="Platform on-call",
            timezone="Europe/London",
            team_ids=[platform_team["id"]],
            holidays_public_config={
                "country_codes": [
                    "GB",
                    "FR",
                ],
            })
        ```


        :param str resource_name: The name of the resource.
        :param ScheduleArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ScheduleArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 holidays_public_config: pulumi.Input[Optional[Union['ScheduleHolidaysPublicConfigArgs', 'ScheduleHolidaysPublicConfigArgsDict']]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 team_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 timezone: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ScheduleArgs.__new__(ScheduleArgs)

            __props__.__dict__["holidays_public_config"] = holidays_public_config
            __props__.__dict__["name"] = name
            __props__.__dict__["team_ids"] = team_ids
            if timezone is None and not opts.urn:
                raise TypeError("Missing required property 'timezone'")
            __props__.__dict__["timezone"] = timezone
        super(Schedule, __self__).__init__(
            'incident:index/schedule:Schedule',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            holidays_public_config: pulumi.Input[Optional[Union['ScheduleHolidaysPublicConfigArgs', 'ScheduleHolidaysPublicConfigArgsDict']]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            team_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            timezone: pulumi.Input[Optional[_builtins.str]] = None) -> 'Schedule':
        """
        Get an existing Schedule resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['ScheduleHolidaysPublicConfigArgs', 'ScheduleHolidaysPublicConfigArgsDict']] holidays_public_config: Public holidays to show on this schedule. Omit the block entirely to show none.
        :param pulumi.Input[_builtins.str] name: Human readable name for the schedule
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] team_ids: IDs of teams that own this schedule
        :param pulumi.Input[_builtins.str] timezone: Timezone the schedule's rotations are anchored to, as an IANA name. Changing this replaces the schedule: a timezone is what its rotations are anchored to, and we don't support moving an existing schedule to another one.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ScheduleState.__new__(_ScheduleState)

        __props__.__dict__["holidays_public_config"] = holidays_public_config
        __props__.__dict__["name"] = name
        __props__.__dict__["team_ids"] = team_ids
        __props__.__dict__["timezone"] = timezone
        return Schedule(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="holidaysPublicConfig")
    def holidays_public_config(self) -> pulumi.Output[Optional['outputs.ScheduleHolidaysPublicConfig']]:
        """
        Public holidays to show on this schedule. Omit the block entirely to show none.
        """
        return pulumi.get(self, "holidays_public_config")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Human readable name for the schedule
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="teamIds")
    def team_ids(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        IDs of teams that own this schedule
        """
        return pulumi.get(self, "team_ids")

    @_builtins.property
    @pulumi.getter
    def timezone(self) -> pulumi.Output[_builtins.str]:
        """
        Timezone the schedule's rotations are anchored to, as an IANA name. Changing this replaces the schedule: a timezone is what its rotations are anchored to, and we don't support moving an existing schedule to another one.
        """
        return pulumi.get(self, "timezone")

