// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident
{
    /// <summary>
    /// Configure your alert sources, separately from the attributes they populate.
    /// 
    /// An alert source, without the attributes it populates — each of those is an `incident.AlertSourceAttributeBeta` resource. Editing one attribute therefore doesn't mean rewriting the source, and two people editing different attributes don't race each other.
    /// 
    /// ## How this differs from `incident.AlertSource`
    /// 
    /// `incident.AlertSource` declares a source and every attribute it populates together, under
    /// one `template.attributes` list. Filling in one more attribute means rewriting that whole
    /// list, and two people editing different attributes are editing the same resource.
    /// 
    /// This resource splits the two apart: the source holds its own configuration — name, type,
    /// title, description, priority — and each attribute binding is its own
    /// `incident.AlertSourceAttributeBeta` resource with its own lifecycle.
    /// 
    /// ## Beta, and what happens next
    /// 
    /// This resource is in beta. Its schema may still change in ways that are not backwards
    /// compatible, so pin the provider version if that matters to you.
    /// 
    /// `incident.AlertSource` is not deprecated, and there is no need to move anything yet.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Incident = IncidentIO.Incident;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var prometheusAlert = Incident.GetRichText.Invoke(new()
    ///     {
    ///         FeatureSet = "rich",
    ///         Markdown = @"Fired by the **Prometheus alertmanager**.
    /// 
    /// Runbook: {{payload.annotations.runbook_url}}
    /// ",
    ///     });
    /// 
    ///     // An alert source, without the attributes it populates. Each of those is its own
    ///     // incident_alert_source_attribute_beta resource, so editing one attribute doesn't
    ///     // mean rewriting the source.
    ///     var prometheus = new Incident.AlertSourceBeta("prometheus", new()
    ///     {
    ///         NamedExpressions = new[]
    ///         {
    ///             new Incident.Inputs.AlertSourceBetaNamedExpressionArgs
    ///             {
    ///                 Fallback = new Incident.Inputs.AlertSourceBetaNamedExpressionFallbackArgs
    ///                 {
    ///                     Result = new Incident.Inputs.AlertSourceBetaNamedExpressionFallbackResultArgs
    ///                     {
    ///                         ValueLiteral = "low",
    ///                     },
    ///                 },
    ///                 Operations = new[]
    ///                 {
    ///                     new Incident.Inputs.AlertSourceBetaNamedExpressionOperationArgs
    ///                     {
    ///                         Branches = new Incident.Inputs.AlertSourceBetaNamedExpressionOperationBranchesArgs
    ///                         {
    ///                             If = new Incident.Inputs.AlertSourceBetaNamedExpressionOperationBranchesIfArgs
    ///                             {
    ///                                 Conditions = new[]
    ///                                 {
    ///                                     new Incident.Inputs.AlertSourceBetaNamedExpressionOperationBranchesIfConditionArgs
    ///                                     {
    ///                                         Subject = "payload.labels.severity",
    ///                                         Operation = "one_of",
    ///                                         Params = new[]
    ///                                         {
    ///                                             new Incident.Inputs.AlertSourceBetaNamedExpressionOperationBranchesIfConditionParamArgs
    ///                                             {
    ///                                                 Values = new[]
    ///                                                 {
    ///                                                     "critical",
    ///                                                     "page",
    ///                                                 },
    ///                                             },
    ///                                         },
    ///                                     },
    ///                                 },
    ///                                 Result = new Incident.Inputs.AlertSourceBetaNamedExpressionOperationBranchesIfResultArgs
    ///                                 {
    ///                                     ValueLiteral = "high",
    ///                                 },
    ///                             },
    ///                             As = severity.Type,
    ///                         },
    ///                     },
    ///                 },
    ///                 Name = "severity_lookup",
    ///                 StartFrom = ".",
    ///             },
    ///         },
    ///         Name = "Prometheus",
    ///         SourceType = "http",
    ///         OwningTeamIds = new[]
    ///         {
    ///             platformTeam.Id,
    ///         },
    ///         Title = new Incident.Inputs.AlertSourceBetaTitleArgs
    ///         {
    ///             Literal = "{{payload.labels.alertname}} on {{payload.labels.service}}",
    ///         },
    ///         Description = new Incident.Inputs.AlertSourceBetaDescriptionArgs
    ///         {
    ///             Literal = prometheusAlert.Apply(getRichTextResult =&gt; getRichTextResult.Json),
    ///         },
    ///         Priority = new Incident.Inputs.AlertSourceBetaPriorityArgs
    ///         {
    ///             ExpressionRef = "severity_lookup",
    ///         },
    ///     });
    /// 
    ///     // A heartbeat source writes its own title and description, and needs the interval a
    ///     // ping is expected within.
    ///     var nightlyBackup = new Incident.AlertSourceBeta("nightly_backup", new()
    ///     {
    ///         Name = "Nightly backup",
    ///         SourceType = "heartbeat",
    ///         HeartbeatOptions = new Incident.Inputs.AlertSourceBetaHeartbeatOptionsArgs
    ///         {
    ///             IntervalSeconds = 86400,
    ///             FailureThreshold = 1,
    ///             GracePeriodSeconds = 3600,
    ///         },
    ///     });
    /// 
    ///     // A private source's alerts are visible to nobody until you say which teams can
    ///     // see them.
    ///     var securityScanner = new Incident.AlertSourceBeta("security_scanner", new()
    ///     {
    ///         Name = "Security scanner",
    ///         SourceType = "http",
    ///         IsPrivate = true,
    ///         VisibleToTeams = new Incident.Inputs.AlertSourceBetaVisibleToTeamsArgs
    ///         {
    ///             Values = new[]
    ///             {
    ///                 securityTeam.Id,
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// The `pulumi import` command can be used, for example:
    /// 
    /// !/bin/bash
    /// 
    /// Import an alert source using its ID
    /// Replace the ID with a real ID from your incident.io organization
    /// 
    /// ```sh
    /// $ pulumi import incident:index/alertSourceBeta:AlertSourceBeta example 01ABC123DEF456GHI789JKL
    /// ```
    /// </summary>
    [IncidentResourceType("incident:index/alertSourceBeta:AlertSourceBeta")]
    public partial class AlertSourceBeta : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The URL to send alert events to
        /// </summary>
        [Output("alertEventsUrl")]
        public Output<string> AlertEventsUrl { get; private set; } = null!;

        /// <summary>
        /// Whether alerts from this source keep counting down to auto-resolve while attached to an incident. Defaults to true. Has no effect without auto*resolve*timeout_minutes.
        /// </summary>
        [Output("autoResolveIncidentAlerts")]
        public Output<bool> AutoResolveIncidentAlerts { get; private set; } = null!;

        /// <summary>
        /// How long to wait before automatically resolving alerts from this source
        /// </summary>
        [Output("autoResolveTimeoutMinutes")]
        public Output<int?> AutoResolveTimeoutMinutes { get; private set; } = null!;

        [Output("description")]
        public Output<Outputs.AlertSourceBetaDescription?> Description { get; private set; } = null!;

        /// <summary>
        /// Email address this alert source receives alerts to
        /// </summary>
        [Output("emailAddress")]
        public Output<string> EmailAddress { get; private set; } = null!;

        [Output("emailOptions")]
        public Output<Outputs.AlertSourceBetaEmailOptions?> EmailOptions { get; private set; } = null!;

        [Output("heartbeatOptions")]
        public Output<Outputs.AlertSourceBetaHeartbeatOptions?> HeartbeatOptions { get; private set; } = null!;

        [Output("httpCustomOptions")]
        public Output<Outputs.AlertSourceBetaHttpCustomOptions?> HttpCustomOptions { get; private set; } = null!;

        /// <summary>
        /// Whether alerts from this source are private
        /// </summary>
        [Output("isPrivate")]
        public Output<bool> IsPrivate { get; private set; } = null!;

        [Output("jiraOptions")]
        public Output<Outputs.AlertSourceBetaJiraOptions?> JiraOptions { get; private set; } = null!;

        /// <summary>
        /// The name of this alert source, for the user's reference
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// An expression this resource owns, addressed by name.
        /// </summary>
        [Output("namedExpressions")]
        public Output<ImmutableArray<Outputs.AlertSourceBetaNamedExpression>> NamedExpressions { get; private set; } = null!;

        /// <summary>
        /// IDs of the teams that own this alert source
        /// </summary>
        [Output("owningTeamIds")]
        public Output<ImmutableArray<string>> OwningTeamIds { get; private set; } = null!;

        [Output("priority")]
        public Output<Outputs.AlertSourceBetaPriority?> Priority { get; private set; } = null!;

        /// <summary>
        /// Controls how this source's ingest rate limit is split into buckets.
        /// </summary>
        [Output("rateLimitSharding")]
        public Output<Outputs.AlertSourceBetaRateLimitSharding?> RateLimitSharding { get; private set; } = null!;

        /// <summary>
        /// The token to use when sending alerts to this source. Only returned to callers with permission to update the source.
        /// </summary>
        [Output("secretToken")]
        public Output<string> SecretToken { get; private set; } = null!;

        /// <summary>
        /// Type of alert source. Possible values are: `Alertmanager`, `AppOptics`, `AzureMonitor`, `AzureDevops`, `BigPanda`, `Bugsnag`, `Checkly`, `Chronosphere`, `Cloudwatch`, `Cloudflare`, `Coralogix`, `Cronitor`, `CrowdstrikeFalcon`, `Dash0`, `Datadog`, `Dynatrace`, `Elasticsearch`, `Email`, `Expel`, `GithubIssue`, `GoogleCloud`, `Grafana`, `Heartbeat`, `Http`, `HttpCustom`, `Honeycomb`, `Icinga2`, `IncomingCalls`, `Jira`, `Jsm`, `MonteCarlo`, `Nagios`, `NewRelic`, `Opsgenie`, `Prtg`, `PagerDuty`, `Panther`, `Pingdom`, `Runscope`, `Sns`, `Sentry`, `SentryMetric`, `ServiceNow`, `Splunk`, `StatusCake`, `StatusPageViews`, `SumoLogic`, `Uptime`, `Vercel`, `Wiz`, `Zendesk`.
        /// </summary>
        [Output("sourceType")]
        public Output<string> SourceType { get; private set; } = null!;

        [Output("title")]
        public Output<Outputs.AlertSourceBetaTitle?> Title { get; private set; } = null!;

        /// <summary>
        /// The source's current version, which increments on every write. Pass it back as ExpectedVersion to reject a write built from a stale read.
        /// </summary>
        [Output("version")]
        public Output<int> Version { get; private set; } = null!;

        [Output("visibleToTeams")]
        public Output<Outputs.AlertSourceBetaVisibleToTeams?> VisibleToTeams { get; private set; } = null!;


        /// <summary>
        /// Create a AlertSourceBeta resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AlertSourceBeta(string name, AlertSourceBetaArgs args, CustomResourceOptions? options = null)
            : base("incident:index/alertSourceBeta:AlertSourceBeta", name, args ?? new AlertSourceBetaArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AlertSourceBeta(string name, Input<string> id, AlertSourceBetaState? state = null, CustomResourceOptions? options = null)
            : base("incident:index/alertSourceBeta:AlertSourceBeta", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/incident-io/pulumi-incident",
                AdditionalSecretOutputs =
                {
                    "secretToken",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AlertSourceBeta resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AlertSourceBeta Get(string name, Input<string> id, AlertSourceBetaState? state = null, CustomResourceOptions? options = null)
        {
            return new AlertSourceBeta(name, id, state, options);
        }
    }

    public sealed class AlertSourceBetaArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether alerts from this source keep counting down to auto-resolve while attached to an incident. Defaults to true. Has no effect without auto*resolve*timeout_minutes.
        /// </summary>
        [Input("autoResolveIncidentAlerts")]
        public Input<bool>? AutoResolveIncidentAlerts { get; set; }

        /// <summary>
        /// How long to wait before automatically resolving alerts from this source
        /// </summary>
        [Input("autoResolveTimeoutMinutes")]
        public Input<int>? AutoResolveTimeoutMinutes { get; set; }

        [Input("description")]
        public Input<Inputs.AlertSourceBetaDescriptionArgs>? Description { get; set; }

        [Input("emailOptions")]
        public Input<Inputs.AlertSourceBetaEmailOptionsArgs>? EmailOptions { get; set; }

        [Input("heartbeatOptions")]
        public Input<Inputs.AlertSourceBetaHeartbeatOptionsArgs>? HeartbeatOptions { get; set; }

        [Input("httpCustomOptions")]
        public Input<Inputs.AlertSourceBetaHttpCustomOptionsArgs>? HttpCustomOptions { get; set; }

        /// <summary>
        /// Whether alerts from this source are private
        /// </summary>
        [Input("isPrivate")]
        public Input<bool>? IsPrivate { get; set; }

        [Input("jiraOptions")]
        public Input<Inputs.AlertSourceBetaJiraOptionsArgs>? JiraOptions { get; set; }

        /// <summary>
        /// The name of this alert source, for the user's reference
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("namedExpressions")]
        private InputList<Inputs.AlertSourceBetaNamedExpressionArgs>? _namedExpressions;

        /// <summary>
        /// An expression this resource owns, addressed by name.
        /// </summary>
        public InputList<Inputs.AlertSourceBetaNamedExpressionArgs> NamedExpressions
        {
            get => _namedExpressions ?? (_namedExpressions = new InputList<Inputs.AlertSourceBetaNamedExpressionArgs>());
            set => _namedExpressions = value;
        }

        [Input("owningTeamIds")]
        private InputList<string>? _owningTeamIds;

        /// <summary>
        /// IDs of the teams that own this alert source
        /// </summary>
        public InputList<string> OwningTeamIds
        {
            get => _owningTeamIds ?? (_owningTeamIds = new InputList<string>());
            set => _owningTeamIds = value;
        }

        [Input("priority")]
        public Input<Inputs.AlertSourceBetaPriorityArgs>? Priority { get; set; }

        /// <summary>
        /// Controls how this source's ingest rate limit is split into buckets.
        /// </summary>
        [Input("rateLimitSharding")]
        public Input<Inputs.AlertSourceBetaRateLimitShardingArgs>? RateLimitSharding { get; set; }

        /// <summary>
        /// Type of alert source. Possible values are: `Alertmanager`, `AppOptics`, `AzureMonitor`, `AzureDevops`, `BigPanda`, `Bugsnag`, `Checkly`, `Chronosphere`, `Cloudwatch`, `Cloudflare`, `Coralogix`, `Cronitor`, `CrowdstrikeFalcon`, `Dash0`, `Datadog`, `Dynatrace`, `Elasticsearch`, `Email`, `Expel`, `GithubIssue`, `GoogleCloud`, `Grafana`, `Heartbeat`, `Http`, `HttpCustom`, `Honeycomb`, `Icinga2`, `IncomingCalls`, `Jira`, `Jsm`, `MonteCarlo`, `Nagios`, `NewRelic`, `Opsgenie`, `Prtg`, `PagerDuty`, `Panther`, `Pingdom`, `Runscope`, `Sns`, `Sentry`, `SentryMetric`, `ServiceNow`, `Splunk`, `StatusCake`, `StatusPageViews`, `SumoLogic`, `Uptime`, `Vercel`, `Wiz`, `Zendesk`.
        /// </summary>
        [Input("sourceType", required: true)]
        public Input<string> SourceType { get; set; } = null!;

        [Input("title")]
        public Input<Inputs.AlertSourceBetaTitleArgs>? Title { get; set; }

        [Input("visibleToTeams")]
        public Input<Inputs.AlertSourceBetaVisibleToTeamsArgs>? VisibleToTeams { get; set; }

        public AlertSourceBetaArgs()
        {
        }
        public static new AlertSourceBetaArgs Empty => new AlertSourceBetaArgs();
    }

    public sealed class AlertSourceBetaState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The URL to send alert events to
        /// </summary>
        [Input("alertEventsUrl")]
        public Input<string>? AlertEventsUrl { get; set; }

        /// <summary>
        /// Whether alerts from this source keep counting down to auto-resolve while attached to an incident. Defaults to true. Has no effect without auto*resolve*timeout_minutes.
        /// </summary>
        [Input("autoResolveIncidentAlerts")]
        public Input<bool>? AutoResolveIncidentAlerts { get; set; }

        /// <summary>
        /// How long to wait before automatically resolving alerts from this source
        /// </summary>
        [Input("autoResolveTimeoutMinutes")]
        public Input<int>? AutoResolveTimeoutMinutes { get; set; }

        [Input("description")]
        public Input<Inputs.AlertSourceBetaDescriptionGetArgs>? Description { get; set; }

        /// <summary>
        /// Email address this alert source receives alerts to
        /// </summary>
        [Input("emailAddress")]
        public Input<string>? EmailAddress { get; set; }

        [Input("emailOptions")]
        public Input<Inputs.AlertSourceBetaEmailOptionsGetArgs>? EmailOptions { get; set; }

        [Input("heartbeatOptions")]
        public Input<Inputs.AlertSourceBetaHeartbeatOptionsGetArgs>? HeartbeatOptions { get; set; }

        [Input("httpCustomOptions")]
        public Input<Inputs.AlertSourceBetaHttpCustomOptionsGetArgs>? HttpCustomOptions { get; set; }

        /// <summary>
        /// Whether alerts from this source are private
        /// </summary>
        [Input("isPrivate")]
        public Input<bool>? IsPrivate { get; set; }

        [Input("jiraOptions")]
        public Input<Inputs.AlertSourceBetaJiraOptionsGetArgs>? JiraOptions { get; set; }

        /// <summary>
        /// The name of this alert source, for the user's reference
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("namedExpressions")]
        private InputList<Inputs.AlertSourceBetaNamedExpressionGetArgs>? _namedExpressions;

        /// <summary>
        /// An expression this resource owns, addressed by name.
        /// </summary>
        public InputList<Inputs.AlertSourceBetaNamedExpressionGetArgs> NamedExpressions
        {
            get => _namedExpressions ?? (_namedExpressions = new InputList<Inputs.AlertSourceBetaNamedExpressionGetArgs>());
            set => _namedExpressions = value;
        }

        [Input("owningTeamIds")]
        private InputList<string>? _owningTeamIds;

        /// <summary>
        /// IDs of the teams that own this alert source
        /// </summary>
        public InputList<string> OwningTeamIds
        {
            get => _owningTeamIds ?? (_owningTeamIds = new InputList<string>());
            set => _owningTeamIds = value;
        }

        [Input("priority")]
        public Input<Inputs.AlertSourceBetaPriorityGetArgs>? Priority { get; set; }

        /// <summary>
        /// Controls how this source's ingest rate limit is split into buckets.
        /// </summary>
        [Input("rateLimitSharding")]
        public Input<Inputs.AlertSourceBetaRateLimitShardingGetArgs>? RateLimitSharding { get; set; }

        [Input("secretToken")]
        private Input<string>? _secretToken;

        /// <summary>
        /// The token to use when sending alerts to this source. Only returned to callers with permission to update the source.
        /// </summary>
        public Input<string>? SecretToken
        {
            get => _secretToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _secretToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Type of alert source. Possible values are: `Alertmanager`, `AppOptics`, `AzureMonitor`, `AzureDevops`, `BigPanda`, `Bugsnag`, `Checkly`, `Chronosphere`, `Cloudwatch`, `Cloudflare`, `Coralogix`, `Cronitor`, `CrowdstrikeFalcon`, `Dash0`, `Datadog`, `Dynatrace`, `Elasticsearch`, `Email`, `Expel`, `GithubIssue`, `GoogleCloud`, `Grafana`, `Heartbeat`, `Http`, `HttpCustom`, `Honeycomb`, `Icinga2`, `IncomingCalls`, `Jira`, `Jsm`, `MonteCarlo`, `Nagios`, `NewRelic`, `Opsgenie`, `Prtg`, `PagerDuty`, `Panther`, `Pingdom`, `Runscope`, `Sns`, `Sentry`, `SentryMetric`, `ServiceNow`, `Splunk`, `StatusCake`, `StatusPageViews`, `SumoLogic`, `Uptime`, `Vercel`, `Wiz`, `Zendesk`.
        /// </summary>
        [Input("sourceType")]
        public Input<string>? SourceType { get; set; }

        [Input("title")]
        public Input<Inputs.AlertSourceBetaTitleGetArgs>? Title { get; set; }

        /// <summary>
        /// The source's current version, which increments on every write. Pass it back as ExpectedVersion to reject a write built from a stale read.
        /// </summary>
        [Input("version")]
        public Input<int>? Version { get; set; }

        [Input("visibleToTeams")]
        public Input<Inputs.AlertSourceBetaVisibleToTeamsGetArgs>? VisibleToTeams { get; set; }

        public AlertSourceBetaState()
        {
        }
        public static new AlertSourceBetaState Empty => new AlertSourceBetaState();
    }
}
