// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident
{
    /// <summary>
    /// Manage custom fields.
    /// 
    /// Custom fields are used to attach metadata to incidents, which you can use when searching
    /// for incidents in the dashboard, triggering workflows, building announcement rules or for
    /// your own data needs.
    /// 
    /// Each field has a type:
    /// 
    /// - Single-select, single value selected from a predefined list of options (e.g. Detection Method)
    /// - Multi-select, as above but you can pick more than one option (e.g. Affected Teams)
    /// - Text, freeform text field (e.g. Customer ID)
    /// - Link, link URL that is synced to Slack bookmarks on the incident channel (e.g. External Status Page)
    /// - Number, integer or fractional numbers (e.g. # Customers Affected)
    /// 
    /// We may add more custom field types in the future - we'd love to hear any other types you'd like to use!
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Incident = IncidentIO.Incident;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Create an Affected Teams multi-select field, required always, shown at all
    ///     // opportunities.
    ///     var affectedTeams = new Incident.CustomField("affected_teams", new()
    ///     {
    ///         Name = "Affected Teams",
    ///         Description = "The teams that are affected by this incident.",
    ///         FieldType = "multi_select",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// The `pulumi import` command can be used, for example:
    /// 
    /// !/bin/bash
    /// 
    /// Import a custom field using its ID
    /// Replace the ID with a real ID from your incident.io organization
    /// 
    /// ```sh
    /// $ pulumi import incident:index/customField:CustomField example 01ABC123DEF456GHI789JKL
    /// ```
    /// </summary>
    [IncidentResourceType("incident:index/customField:CustomField")]
    public partial class CustomField : global::Pulumi.CustomResource
    {
        /// <summary>
        /// For catalog fields, the ID of the associated catalog type
        /// </summary>
        [Output("catalogTypeId")]
        public Output<string?> CatalogTypeId { get; private set; } = null!;

        /// <summary>
        /// Description of the custom field
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// Type of custom field. Possible values are: `SingleSelect`, `MultiSelect`, `Text`, `Link`, `Numeric`.
        /// </summary>
        [Output("fieldType")]
        public Output<string> FieldType { get; private set; } = null!;

        [Output("filterBy")]
        public Output<Outputs.CustomFieldFilterBy?> FilterBy { get; private set; } = null!;

        /// <summary>
        /// For catalog fields, the ID of the attribute used to group catalog entries (if applicable)
        /// </summary>
        [Output("groupByCatalogAttributeId")]
        public Output<string?> GroupByCatalogAttributeId { get; private set; } = null!;

        /// <summary>
        /// Which catalog attribute provides helptext for the options
        /// </summary>
        [Output("helptextCatalogAttributeId")]
        public Output<string?> HelptextCatalogAttributeId { get; private set; } = null!;

        /// <summary>
        /// Human readable name for the custom field
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;


        /// <summary>
        /// Create a CustomField resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public CustomField(string name, CustomFieldArgs args, CustomResourceOptions? options = null)
            : base("incident:index/customField:CustomField", name, args ?? new CustomFieldArgs(), MakeResourceOptions(options, ""))
        {
        }

        private CustomField(string name, Input<string> id, CustomFieldState? state = null, CustomResourceOptions? options = null)
            : base("incident:index/customField:CustomField", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/incident-io/pulumi-incident",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing CustomField resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static CustomField Get(string name, Input<string> id, CustomFieldState? state = null, CustomResourceOptions? options = null)
        {
            return new CustomField(name, id, state, options);
        }
    }

    public sealed class CustomFieldArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// For catalog fields, the ID of the associated catalog type
        /// </summary>
        [Input("catalogTypeId")]
        public Input<string>? CatalogTypeId { get; set; }

        /// <summary>
        /// Description of the custom field
        /// </summary>
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        /// <summary>
        /// Type of custom field. Possible values are: `SingleSelect`, `MultiSelect`, `Text`, `Link`, `Numeric`.
        /// </summary>
        [Input("fieldType", required: true)]
        public Input<string> FieldType { get; set; } = null!;

        [Input("filterBy")]
        public Input<Inputs.CustomFieldFilterByArgs>? FilterBy { get; set; }

        /// <summary>
        /// For catalog fields, the ID of the attribute used to group catalog entries (if applicable)
        /// </summary>
        [Input("groupByCatalogAttributeId")]
        public Input<string>? GroupByCatalogAttributeId { get; set; }

        /// <summary>
        /// Which catalog attribute provides helptext for the options
        /// </summary>
        [Input("helptextCatalogAttributeId")]
        public Input<string>? HelptextCatalogAttributeId { get; set; }

        /// <summary>
        /// Human readable name for the custom field
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public CustomFieldArgs()
        {
        }
        public static new CustomFieldArgs Empty => new CustomFieldArgs();
    }

    public sealed class CustomFieldState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// For catalog fields, the ID of the associated catalog type
        /// </summary>
        [Input("catalogTypeId")]
        public Input<string>? CatalogTypeId { get; set; }

        /// <summary>
        /// Description of the custom field
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Type of custom field. Possible values are: `SingleSelect`, `MultiSelect`, `Text`, `Link`, `Numeric`.
        /// </summary>
        [Input("fieldType")]
        public Input<string>? FieldType { get; set; }

        [Input("filterBy")]
        public Input<Inputs.CustomFieldFilterByGetArgs>? FilterBy { get; set; }

        /// <summary>
        /// For catalog fields, the ID of the attribute used to group catalog entries (if applicable)
        /// </summary>
        [Input("groupByCatalogAttributeId")]
        public Input<string>? GroupByCatalogAttributeId { get; set; }

        /// <summary>
        /// Which catalog attribute provides helptext for the options
        /// </summary>
        [Input("helptextCatalogAttributeId")]
        public Input<string>? HelptextCatalogAttributeId { get; set; }

        /// <summary>
        /// Human readable name for the custom field
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public CustomFieldState()
        {
        }
        public static new CustomFieldState Empty => new CustomFieldState();
    }
}
