// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident
{
    /// <summary>
    /// Create and manage escalation paths, written as a flat map of named node sequences.
    /// 
    /// Each sequence runs its nodes in order and either ends with a `Branch`, which names the sequences to continue down, or falls off the end of the escalation path.
    /// 
    /// We'd generally recommend building escalation paths in our [web dashboard](https://app.incident.io/~/on-call/escalation-paths) and using the 'Export' flow to generate your Terraform.
    /// 
    /// ## How this differs from `incident.EscalationPath`
    /// 
    /// `incident.EscalationPath` nests a branch's nodes inside it, as `if_else.then_path` and
    /// `if_else.else_path`. Terraform schemas can't recurse indefinitely, so that resource stops at
    /// five levels of branching, and a path that branches more than that can't be written at all.
    /// 
    /// This resource names its sequences instead. A `Branch` says which sequence to continue down
    /// rather than holding its nodes, so every sequence sits at the same depth in the config and
    /// there's no nesting limit. It also swaps `Repeat` for `Loop`, which names the node to go back
    /// to, and replaces the raw engine `Conditions` on a branch with a `branch.if` block holding one
    /// attribute per thing an escalation can be tested on.
    /// 
    /// ## Beta, and what happens next
    /// 
    /// This resource is in beta. Its schema may still change in ways that are not backwards
    /// compatible, so pin the provider version if that matters to you.
    /// 
    /// `incident.EscalationPath` is not deprecated, and there is no need to move anything yet. The
    /// two resources manage the same escalation paths through the same API, so don't point both at
    /// one path: they'd each plan to undo the other's changes.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Incident = IncidentIO.Incident;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Look up a user to page. Escalation path targets can also be schedules or
    ///     // Slack/Teams channels; see the `type` attribute on each target.
    ///     var onCall = Incident.GetUser.Invoke(new()
    ///     {
    ///         Email = "on-call@example.com",
    ///     });
    /// 
    ///     // A last resort path, which the path below hands over to out of hours.
    ///     var fallback = new Incident.EscalationPath("fallback", new()
    ///     {
    ///         Name = "Fallback",
    ///         Paths = new[]
    ///         {
    ///             new Incident.Inputs.EscalationPathPathArgs
    ///             {
    ///                 Type = "level",
    ///                 Level = new Incident.Inputs.EscalationPathPathLevelArgs
    ///                 {
    ///                     Targets = new[]
    ///                     {
    ///                         new Incident.Inputs.EscalationPathPathLevelTargetArgs
    ///                         {
    ///                             Type = "user",
    ///                             Id = onCall.Apply(getUserResult =&gt; getUserResult.Id),
    ///                             Urgency = "high",
    ///                         },
    ///                     },
    ///                     TimeToAckSeconds = 300,
    ///                 },
    ///             },
    ///         },
    ///     });
    /// 
    ///     // The same escalation path as the incident_escalation_path example, written as a
    ///     // flat map of sequences: if in working hours, page with high urgency; otherwise
    ///     // page with low urgency.
    ///     var urgentSupport = new Incident.EscalationPathBeta("urgent_support", new()
    ///     {
    ///         Name = "Urgent support",
    ///         Start = "main",
    ///         Sequences = 
    ///         {
    ///             { "main", new Incident.Inputs.EscalationPathBetaSequencesArgs
    ///             {
    ///                 Nodes = new[]
    ///                 {
    ///                     new Incident.Inputs.EscalationPathBetaSequencesNodeArgs
    ///                     {
    ///                         Id = "start",
    ///                         Branch = new Incident.Inputs.EscalationPathBetaSequencesNodeBranchArgs
    ///                         {
    ///                             If = new Incident.Inputs.EscalationPathBetaSequencesNodeBranchIfArgs
    ///                             {
    ///                                 WorkingHoursActive = "UK",
    ///                             },
    ///                             Then = "in_hours",
    ///                             Else = "out_of_hours",
    ///                         },
    ///                     },
    ///                 },
    ///             } },
    ///             { "in_hours", new Incident.Inputs.EscalationPathBetaSequencesArgs
    ///             {
    ///                 Nodes = new[]
    ///                 {
    ///                     new Incident.Inputs.EscalationPathBetaSequencesNodeArgs
    ///                     {
    ///                         Level = new Incident.Inputs.EscalationPathBetaSequencesNodeLevelArgs
    ///                         {
    ///                             Targets = new[]
    ///                             {
    ///                                 new Incident.Inputs.EscalationPathBetaSequencesNodeLevelTargetArgs
    ///                                 {
    ///                                     Type = "user",
    ///                                     Id = onCall.Apply(getUserResult =&gt; getUserResult.Id),
    ///                                     Urgency = "high",
    ///                                 },
    ///                             },
    ///                             TimeToAckSeconds = 300,
    ///                         },
    ///                     },
    ///                     new Incident.Inputs.EscalationPathBetaSequencesNodeArgs
    ///                     {
    ///                         Delay = new Incident.Inputs.EscalationPathBetaSequencesNodeDelayArgs
    ///                         {
    ///                             DelaySeconds = 120,
    ///                         },
    ///                     },
    ///                     new Incident.Inputs.EscalationPathBetaSequencesNodeArgs
    ///                     {
    ///                         Loop = new Incident.Inputs.EscalationPathBetaSequencesNodeLoopArgs
    ///                         {
    ///                             BackTo = "start",
    ///                             Times = 3,
    ///                         },
    ///                     },
    ///                 },
    ///             } },
    ///             { "out_of_hours", new Incident.Inputs.EscalationPathBetaSequencesArgs
    ///             {
    ///                 Nodes = new[]
    ///                 {
    ///                     new Incident.Inputs.EscalationPathBetaSequencesNodeArgs
    ///                     {
    ///                         Level = new Incident.Inputs.EscalationPathBetaSequencesNodeLevelArgs
    ///                         {
    ///                             Targets = new[]
    ///                             {
    ///                                 new Incident.Inputs.EscalationPathBetaSequencesNodeLevelTargetArgs
    ///                                 {
    ///                                     Type = "user",
    ///                                     Id = onCall.Apply(getUserResult =&gt; getUserResult.Id),
    ///                                     Urgency = "low",
    ///                                 },
    ///                             },
    ///                             TimeToAckSeconds = 300,
    ///                         },
    ///                     },
    ///                     new Incident.Inputs.EscalationPathBetaSequencesNodeArgs
    ///                     {
    ///                         EscalationPath = new Incident.Inputs.EscalationPathBetaSequencesNodeEscalationPathArgs
    ///                         {
    ///                             EscalationPathId = fallback.Id,
    ///                         },
    ///                     },
    ///                 },
    ///             } },
    ///         },
    ///         WorkingHours = new[]
    ///         {
    ///             new Incident.Inputs.EscalationPathBetaWorkingHourArgs
    ///             {
    ///                 Id = "UK",
    ///                 Name = "UK",
    ///                 Timezone = "Europe/London",
    ///                 WeekdayIntervals = new[]
    ///                 {
    ///                     new Incident.Inputs.EscalationPathBetaWorkingHourWeekdayIntervalArgs
    ///                     {
    ///                         Weekday = "monday",
    ///                         StartTime = "09:00",
    ///                         EndTime = "17:00",
    ///                     },
    ///                 },
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// The `pulumi import` command can be used, for example:
    /// 
    /// !/bin/bash
    /// 
    /// Import an escalation path using its ID
    /// Replace the ID with a real ID from your incident.io organization
    /// 
    /// ```sh
    /// $ pulumi import incident:index/escalationPathBeta:EscalationPathBeta urgent_support 01ABC123DEF456GHI789JKL
    /// ```
    /// </summary>
    [IncidentResourceType("incident:index/escalationPathBeta:EscalationPathBeta")]
    public partial class EscalationPathBeta : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The name of this escalation path, for the user's reference.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Controls if an escalation will repeat after acknowledgement, when the alert is unresolved. When configured, it will repeat after the specified delay.
        /// </summary>
        [Output("repeatConfig")]
        public Output<Outputs.EscalationPathBetaRepeatConfig?> RepeatConfig { get; private set; } = null!;

        /// <summary>
        /// Named sequences of nodes, keyed by a name you choose. Each sequence either ends with a `Branch` node or runs off the end of the escalation path. Branches reference other sequences by key.
        /// </summary>
        [Output("sequences")]
        public Output<ImmutableDictionary<string, Outputs.EscalationPathBetaSequences>> Sequences { get; private set; } = null!;

        /// <summary>
        /// The key of the sequence this escalation path begins with.
        /// </summary>
        [Output("start")]
        public Output<string> Start { get; private set; } = null!;

        /// <summary>
        /// IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required.
        /// </summary>
        [Output("teamIds")]
        public Output<ImmutableArray<string>> TeamIds { get; private set; } = null!;

        /// <summary>
        /// The working hours for this escalation path.
        /// </summary>
        [Output("workingHours")]
        public Output<ImmutableArray<Outputs.EscalationPathBetaWorkingHour>> WorkingHours { get; private set; } = null!;


        /// <summary>
        /// Create a EscalationPathBeta resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public EscalationPathBeta(string name, EscalationPathBetaArgs args, CustomResourceOptions? options = null)
            : base("incident:index/escalationPathBeta:EscalationPathBeta", name, args ?? new EscalationPathBetaArgs(), MakeResourceOptions(options, ""))
        {
        }

        private EscalationPathBeta(string name, Input<string> id, EscalationPathBetaState? state = null, CustomResourceOptions? options = null)
            : base("incident:index/escalationPathBeta:EscalationPathBeta", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/incident-io/pulumi-incident",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing EscalationPathBeta resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static EscalationPathBeta Get(string name, Input<string> id, EscalationPathBetaState? state = null, CustomResourceOptions? options = null)
        {
            return new EscalationPathBeta(name, id, state, options);
        }
    }

    public sealed class EscalationPathBetaArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of this escalation path, for the user's reference.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Controls if an escalation will repeat after acknowledgement, when the alert is unresolved. When configured, it will repeat after the specified delay.
        /// </summary>
        [Input("repeatConfig")]
        public Input<Inputs.EscalationPathBetaRepeatConfigArgs>? RepeatConfig { get; set; }

        [Input("sequences", required: true)]
        private InputMap<Inputs.EscalationPathBetaSequencesArgs>? _sequences;

        /// <summary>
        /// Named sequences of nodes, keyed by a name you choose. Each sequence either ends with a `Branch` node or runs off the end of the escalation path. Branches reference other sequences by key.
        /// </summary>
        public InputMap<Inputs.EscalationPathBetaSequencesArgs> Sequences
        {
            get => _sequences ?? (_sequences = new InputMap<Inputs.EscalationPathBetaSequencesArgs>());
            set => _sequences = value;
        }

        /// <summary>
        /// The key of the sequence this escalation path begins with.
        /// </summary>
        [Input("start", required: true)]
        public Input<string> Start { get; set; } = null!;

        [Input("teamIds")]
        private InputList<string>? _teamIds;

        /// <summary>
        /// IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required.
        /// </summary>
        public InputList<string> TeamIds
        {
            get => _teamIds ?? (_teamIds = new InputList<string>());
            set => _teamIds = value;
        }

        [Input("workingHours")]
        private InputList<Inputs.EscalationPathBetaWorkingHourArgs>? _workingHours;

        /// <summary>
        /// The working hours for this escalation path.
        /// </summary>
        public InputList<Inputs.EscalationPathBetaWorkingHourArgs> WorkingHours
        {
            get => _workingHours ?? (_workingHours = new InputList<Inputs.EscalationPathBetaWorkingHourArgs>());
            set => _workingHours = value;
        }

        public EscalationPathBetaArgs()
        {
        }
        public static new EscalationPathBetaArgs Empty => new EscalationPathBetaArgs();
    }

    public sealed class EscalationPathBetaState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of this escalation path, for the user's reference.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Controls if an escalation will repeat after acknowledgement, when the alert is unresolved. When configured, it will repeat after the specified delay.
        /// </summary>
        [Input("repeatConfig")]
        public Input<Inputs.EscalationPathBetaRepeatConfigGetArgs>? RepeatConfig { get; set; }

        [Input("sequences")]
        private InputMap<Inputs.EscalationPathBetaSequencesGetArgs>? _sequences;

        /// <summary>
        /// Named sequences of nodes, keyed by a name you choose. Each sequence either ends with a `Branch` node or runs off the end of the escalation path. Branches reference other sequences by key.
        /// </summary>
        public InputMap<Inputs.EscalationPathBetaSequencesGetArgs> Sequences
        {
            get => _sequences ?? (_sequences = new InputMap<Inputs.EscalationPathBetaSequencesGetArgs>());
            set => _sequences = value;
        }

        /// <summary>
        /// The key of the sequence this escalation path begins with.
        /// </summary>
        [Input("start")]
        public Input<string>? Start { get; set; }

        [Input("teamIds")]
        private InputList<string>? _teamIds;

        /// <summary>
        /// IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required.
        /// </summary>
        public InputList<string> TeamIds
        {
            get => _teamIds ?? (_teamIds = new InputList<string>());
            set => _teamIds = value;
        }

        [Input("workingHours")]
        private InputList<Inputs.EscalationPathBetaWorkingHourGetArgs>? _workingHours;

        /// <summary>
        /// The working hours for this escalation path.
        /// </summary>
        public InputList<Inputs.EscalationPathBetaWorkingHourGetArgs> WorkingHours
        {
            get => _workingHours ?? (_workingHours = new InputList<Inputs.EscalationPathBetaWorkingHourGetArgs>());
            set => _workingHours = value;
        }

        public EscalationPathBetaState()
        {
        }
        public static new EscalationPathBetaState Empty => new EscalationPathBetaState();
    }
}
