// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident
{
    /// <summary>
    /// Manage incident statuses.
    /// 
    /// Each incident has a status, picked from one of the statuses configured in your
    /// organisations settings.
    /// 
    /// Statuses help communicate where an incident is in its lifecycle. You can use
    /// statuses when filtering incidents in the dashboard, and in workflows and announcement
    /// rules.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Incident = IncidentIO.Incident;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Create an additional closed status called "Clean-up".
    ///     var cleanUp = new Incident.Status("clean_up", new()
    ///     {
    ///         Name = "Clean-up",
    ///         Description = "Not yet fully finished, but isn't a live incident anymore.",
    ///         Category = "closed",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// The `pulumi import` command can be used, for example:
    /// 
    /// !/bin/bash
    /// 
    /// Import a status using its ID
    /// Replace the ID with a real ID from your incident.io organization
    /// 
    /// ```sh
    /// $ pulumi import incident:index/status:Status example 01ABC123DEF456GHI789JKL
    /// ```
    /// </summary>
    [IncidentResourceType("incident:index/status:Status")]
    public partial class Status : global::Pulumi.CustomResource
    {
        /// <summary>
        /// What category of status it is. All statuses apart from live (renamed in the app to Active) and learning (renamed in the app to Post-incident) are managed by incident.io and cannot be configured. Possible values are: `Triage`, `Declined`, `Merged`, `Canceled`, `Live`, `Learning`, `Closed`, `Paused`.
        /// </summary>
        [Output("category")]
        public Output<string> Category { get; private set; } = null!;

        /// <summary>
        /// Rich text description of the incident status
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// Unique name of this status
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;


        /// <summary>
        /// Create a Status resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Status(string name, StatusArgs args, CustomResourceOptions? options = null)
            : base("incident:index/status:Status", name, args ?? new StatusArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Status(string name, Input<string> id, StatusState? state = null, CustomResourceOptions? options = null)
            : base("incident:index/status:Status", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/incident-io/pulumi-incident",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Status resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Status Get(string name, Input<string> id, StatusState? state = null, CustomResourceOptions? options = null)
        {
            return new Status(name, id, state, options);
        }
    }

    public sealed class StatusArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// What category of status it is. All statuses apart from live (renamed in the app to Active) and learning (renamed in the app to Post-incident) are managed by incident.io and cannot be configured. Possible values are: `Triage`, `Declined`, `Merged`, `Canceled`, `Live`, `Learning`, `Closed`, `Paused`.
        /// </summary>
        [Input("category", required: true)]
        public Input<string> Category { get; set; } = null!;

        /// <summary>
        /// Rich text description of the incident status
        /// </summary>
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        /// <summary>
        /// Unique name of this status
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public StatusArgs()
        {
        }
        public static new StatusArgs Empty => new StatusArgs();
    }

    public sealed class StatusState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// What category of status it is. All statuses apart from live (renamed in the app to Active) and learning (renamed in the app to Post-incident) are managed by incident.io and cannot be configured. Possible values are: `Triage`, `Declined`, `Merged`, `Canceled`, `Live`, `Learning`, `Closed`, `Paused`.
        /// </summary>
        [Input("category")]
        public Input<string>? Category { get; set; }

        /// <summary>
        /// Rich text description of the incident status
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Unique name of this status
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public StatusState()
        {
        }
        public static new StatusState Empty => new StatusState();
    }
}
