// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incident

import (
	"context"
	"reflect"

	"errors"
	"github.com/incident-io/pulumi-incident/sdk/go/incident/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manage custom fields.
//
// Custom fields are used to attach metadata to incidents, which you can use when searching
// for incidents in the dashboard, triggering workflows, building announcement rules or for
// your own data needs.
//
// Each field has a type:
//
// - Single-select, single value selected from a predefined list of options (e.g. Detection Method)
// - Multi-select, as above but you can pick more than one option (e.g. Affected Teams)
// - Text, freeform text field (e.g. Customer ID)
// - Link, link URL that is synced to Slack bookmarks on the incident channel (e.g. External Status Page)
// - Number, integer or fractional numbers (e.g. # Customers Affected)
//
// We may add more custom field types in the future - we'd love to hear any other types you'd like to use!
//
// ## Example - Single-select
//
// ```go
// package main
//
// import (
//
//	"github.com/incident-io/pulumi-incident/sdk/go/incident"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Single-select: one value from a predefined list of options (e.g. Detection Method).
//			// Options are managed separately with incident_custom_field_option.
//			_, err := incident.NewCustomField(ctx, "detection_method", &incident.CustomFieldArgs{
//				Name:        pulumi.String("Detection Method"),
//				Description: pulumi.String("How this incident was detected."),
//				FieldType:   pulumi.String("single_select"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Example - Multi-select
//
// ```go
// package main
//
// import (
//
//	"github.com/incident-io/pulumi-incident/sdk/go/incident"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Multi-select: like single-select, but more than one option can be picked
//			// (e.g. Affected Teams). Options are managed separately with
//			// incident_custom_field_option.
//			_, err := incident.NewCustomField(ctx, "affected_teams", &incident.CustomFieldArgs{
//				Name:        pulumi.String("Affected Teams"),
//				Description: pulumi.String("The teams that are affected by this incident."),
//				FieldType:   pulumi.String("multi_select"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Example - Text
//
// ```go
// package main
//
// import (
//
//	"github.com/incident-io/pulumi-incident/sdk/go/incident"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Text: a freeform text field (e.g. Customer ID).
//			_, err := incident.NewCustomField(ctx, "customer_id", &incident.CustomFieldArgs{
//				Name:        pulumi.String("Customer ID"),
//				Description: pulumi.String("The customer identifier associated with this incident."),
//				FieldType:   pulumi.String("text"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Example - Link
//
// ```go
// package main
//
// import (
//
//	"github.com/incident-io/pulumi-incident/sdk/go/incident"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Link: a URL synced to Slack bookmarks on the incident channel
//			// (e.g. External Status Page).
//			_, err := incident.NewCustomField(ctx, "external_status_page", &incident.CustomFieldArgs{
//				Name:        pulumi.String("External Status Page"),
//				Description: pulumi.String("Link to the external status page for this incident."),
//				FieldType:   pulumi.String("link"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Example - Numeric
//
// ```go
// package main
//
// import (
//
//	"github.com/incident-io/pulumi-incident/sdk/go/incident"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Numeric: an integer or fractional number (e.g. Customers Affected).
//			_, err := incident.NewCustomField(ctx, "customers_affected", &incident.CustomFieldArgs{
//				Name:        pulumi.String("Customers Affected"),
//				Description: pulumi.String("How many customers are affected by this incident."),
//				FieldType:   pulumi.String("numeric"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Example - Catalog-backed with a fixed filter
//
// ```go
// package main
//
// import (
//
//	"github.com/incident-io/pulumi-incident/sdk/go/incident"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Catalog-backed fields can offer a restricted set of options, rather than every
//			// entry of their catalog type.
//			service, err := incident.NewCatalogType(ctx, "service", &incident.CatalogTypeArgs{
//				Name:          pulumi.String("Service"),
//				Description:   pulumi.String("All services that we run across our product"),
//				SourceRepoUrl: pulumi.String(""),
//			})
//			if err != nil {
//				return err
//			}
//			serviceTier, err := incident.NewCatalogType(ctx, "service_tier", &incident.CatalogTypeArgs{
//				Name:          pulumi.String("Service Tier"),
//				Description:   pulumi.String("Level of importance for each service"),
//				SourceRepoUrl: pulumi.String(""),
//			})
//			if err != nil {
//				return err
//			}
//			serviceServiceTier, err := incident.NewCatalogTypeAttribute(ctx, "service_service_tier", &incident.CatalogTypeAttributeArgs{
//				CatalogTypeId: service.ID().ToIDOutput().ToStringOutput(),
//				Name:          pulumi.String("Tier"),
//				Type:          serviceTier.TypeName,
//			})
//			if err != nil {
//				return err
//			}
//			tierOne, err := incident.NewCatalogEntry(ctx, "tier_one", &incident.CatalogEntryArgs{
//				CatalogTypeId:   serviceTier.ID().ToIDOutput().ToStringOutput(),
//				Name:            pulumi.String("Tier 1"),
//				AttributeValues: incident.CatalogEntryAttributeValueArray{},
//			})
//			if err != nil {
//				return err
//			}
//			// Offer only our tier 1 services, on every incident. `fixed_filter` restricts the
//			// options to entries whose Tier attribute is one of the listed values - unlike
//			// `filter_by`, which follows another custom field's value on the incident.
//			_, err = incident.NewCustomField(ctx, "affected_tier_one_service", &incident.CustomFieldArgs{
//				Name:          pulumi.String("Affected tier 1 service"),
//				Description:   pulumi.String("The tier 1 service that is affected by this incident."),
//				FieldType:     pulumi.String("single_select"),
//				CatalogTypeId: service.ID().ToIDOutput().ToStringOutput(),
//				FixedFilter: &incident.CustomFieldFixedFilterArgs{
//					CatalogAttributeId: serviceServiceTier.ID().ToIDOutput().ToStringOutput(),
//					Values: pulumi.StringArray{
//						tierOne.ID().ToIDOutput().ToStringOutput(),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type CustomField struct {
	pulumi.CustomResourceState

	// For catalog fields, the ID of the associated catalog type
	CatalogTypeId pulumi.StringPtrOutput `pulumi:"catalogTypeId"`
	// Description of the custom field
	Description pulumi.StringOutput `pulumi:"description"`
	// Type of custom field. Possible values are: `singleSelect`, `multiSelect`, `text`, `link`, `numeric`.
	FieldType pulumi.StringOutput          `pulumi:"fieldType"`
	FilterBy  CustomFieldFilterByPtrOutput `pulumi:"filterBy"`
	// Restrict this catalog-backed field's options to catalog entries whose `catalogAttributeId` attribute references one of `values`. This is the static counterpart to `filterBy`: rather than following whatever another custom field is set to on the incident, the filter is chosen up front and is the same for every incident. Mutually exclusive with `filterBy`.
	FixedFilter CustomFieldFixedFilterPtrOutput `pulumi:"fixedFilter"`
	// For catalog fields, the ID of the attribute used to group catalog entries (if applicable)
	GroupByCatalogAttributeId pulumi.StringPtrOutput `pulumi:"groupByCatalogAttributeId"`
	// Which catalog attribute provides helptext for the options
	HelptextCatalogAttributeId pulumi.StringPtrOutput `pulumi:"helptextCatalogAttributeId"`
	// Human readable name for the custom field
	Name pulumi.StringOutput `pulumi:"name"`
}

// NewCustomField registers a new resource with the given unique name, arguments, and options.
func NewCustomField(ctx *pulumi.Context,
	name string, args *CustomFieldArgs, opts ...pulumi.ResourceOption) (*CustomField, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Description == nil {
		return nil, errors.New("invalid value for required argument 'Description'")
	}
	if args.FieldType == nil {
		return nil, errors.New("invalid value for required argument 'FieldType'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource CustomField
	err := ctx.RegisterResource("incident:index/customField:CustomField", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCustomField gets an existing CustomField resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCustomField(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CustomFieldState, opts ...pulumi.ResourceOption) (*CustomField, error) {
	var resource CustomField
	err := ctx.ReadResource("incident:index/customField:CustomField", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CustomField resources.
type customFieldState struct {
	// For catalog fields, the ID of the associated catalog type
	CatalogTypeId *string `pulumi:"catalogTypeId"`
	// Description of the custom field
	Description *string `pulumi:"description"`
	// Type of custom field. Possible values are: `singleSelect`, `multiSelect`, `text`, `link`, `numeric`.
	FieldType *string              `pulumi:"fieldType"`
	FilterBy  *CustomFieldFilterBy `pulumi:"filterBy"`
	// Restrict this catalog-backed field's options to catalog entries whose `catalogAttributeId` attribute references one of `values`. This is the static counterpart to `filterBy`: rather than following whatever another custom field is set to on the incident, the filter is chosen up front and is the same for every incident. Mutually exclusive with `filterBy`.
	FixedFilter *CustomFieldFixedFilter `pulumi:"fixedFilter"`
	// For catalog fields, the ID of the attribute used to group catalog entries (if applicable)
	GroupByCatalogAttributeId *string `pulumi:"groupByCatalogAttributeId"`
	// Which catalog attribute provides helptext for the options
	HelptextCatalogAttributeId *string `pulumi:"helptextCatalogAttributeId"`
	// Human readable name for the custom field
	Name *string `pulumi:"name"`
}

type CustomFieldState struct {
	// For catalog fields, the ID of the associated catalog type
	CatalogTypeId pulumi.StringPtrInput
	// Description of the custom field
	Description pulumi.StringPtrInput
	// Type of custom field. Possible values are: `singleSelect`, `multiSelect`, `text`, `link`, `numeric`.
	FieldType pulumi.StringPtrInput
	FilterBy  CustomFieldFilterByPtrInput
	// Restrict this catalog-backed field's options to catalog entries whose `catalogAttributeId` attribute references one of `values`. This is the static counterpart to `filterBy`: rather than following whatever another custom field is set to on the incident, the filter is chosen up front and is the same for every incident. Mutually exclusive with `filterBy`.
	FixedFilter CustomFieldFixedFilterPtrInput
	// For catalog fields, the ID of the attribute used to group catalog entries (if applicable)
	GroupByCatalogAttributeId pulumi.StringPtrInput
	// Which catalog attribute provides helptext for the options
	HelptextCatalogAttributeId pulumi.StringPtrInput
	// Human readable name for the custom field
	Name pulumi.StringPtrInput
}

func (CustomFieldState) ElementType() reflect.Type {
	return reflect.TypeOf((*customFieldState)(nil)).Elem()
}

type customFieldArgs struct {
	// For catalog fields, the ID of the associated catalog type
	CatalogTypeId *string `pulumi:"catalogTypeId"`
	// Description of the custom field
	Description string `pulumi:"description"`
	// Type of custom field. Possible values are: `singleSelect`, `multiSelect`, `text`, `link`, `numeric`.
	FieldType string               `pulumi:"fieldType"`
	FilterBy  *CustomFieldFilterBy `pulumi:"filterBy"`
	// Restrict this catalog-backed field's options to catalog entries whose `catalogAttributeId` attribute references one of `values`. This is the static counterpart to `filterBy`: rather than following whatever another custom field is set to on the incident, the filter is chosen up front and is the same for every incident. Mutually exclusive with `filterBy`.
	FixedFilter *CustomFieldFixedFilter `pulumi:"fixedFilter"`
	// For catalog fields, the ID of the attribute used to group catalog entries (if applicable)
	GroupByCatalogAttributeId *string `pulumi:"groupByCatalogAttributeId"`
	// Which catalog attribute provides helptext for the options
	HelptextCatalogAttributeId *string `pulumi:"helptextCatalogAttributeId"`
	// Human readable name for the custom field
	Name *string `pulumi:"name"`
}

// The set of arguments for constructing a CustomField resource.
type CustomFieldArgs struct {
	// For catalog fields, the ID of the associated catalog type
	CatalogTypeId pulumi.StringPtrInput
	// Description of the custom field
	Description pulumi.StringInput
	// Type of custom field. Possible values are: `singleSelect`, `multiSelect`, `text`, `link`, `numeric`.
	FieldType pulumi.StringInput
	FilterBy  CustomFieldFilterByPtrInput
	// Restrict this catalog-backed field's options to catalog entries whose `catalogAttributeId` attribute references one of `values`. This is the static counterpart to `filterBy`: rather than following whatever another custom field is set to on the incident, the filter is chosen up front and is the same for every incident. Mutually exclusive with `filterBy`.
	FixedFilter CustomFieldFixedFilterPtrInput
	// For catalog fields, the ID of the attribute used to group catalog entries (if applicable)
	GroupByCatalogAttributeId pulumi.StringPtrInput
	// Which catalog attribute provides helptext for the options
	HelptextCatalogAttributeId pulumi.StringPtrInput
	// Human readable name for the custom field
	Name pulumi.StringPtrInput
}

func (CustomFieldArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*customFieldArgs)(nil)).Elem()
}

type CustomFieldInput interface {
	pulumi.Input

	ToCustomFieldOutput() CustomFieldOutput
	ToCustomFieldOutputWithContext(ctx context.Context) CustomFieldOutput
}

func (*CustomField) ElementType() reflect.Type {
	return reflect.TypeOf((**CustomField)(nil)).Elem()
}

func (i *CustomField) ToCustomFieldOutput() CustomFieldOutput {
	return i.ToCustomFieldOutputWithContext(context.Background())
}

func (i *CustomField) ToCustomFieldOutputWithContext(ctx context.Context) CustomFieldOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CustomFieldOutput)
}

// CustomFieldArrayInput is an input type that accepts CustomFieldArray and CustomFieldArrayOutput values.
// You can construct a concrete instance of `CustomFieldArrayInput` via:
//
//	CustomFieldArray{ CustomFieldArgs{...} }
type CustomFieldArrayInput interface {
	pulumi.Input

	ToCustomFieldArrayOutput() CustomFieldArrayOutput
	ToCustomFieldArrayOutputWithContext(context.Context) CustomFieldArrayOutput
}

type CustomFieldArray []CustomFieldInput

func (CustomFieldArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CustomField)(nil)).Elem()
}

func (i CustomFieldArray) ToCustomFieldArrayOutput() CustomFieldArrayOutput {
	return i.ToCustomFieldArrayOutputWithContext(context.Background())
}

func (i CustomFieldArray) ToCustomFieldArrayOutputWithContext(ctx context.Context) CustomFieldArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CustomFieldArrayOutput)
}

// CustomFieldMapInput is an input type that accepts CustomFieldMap and CustomFieldMapOutput values.
// You can construct a concrete instance of `CustomFieldMapInput` via:
//
//	CustomFieldMap{ "key": CustomFieldArgs{...} }
type CustomFieldMapInput interface {
	pulumi.Input

	ToCustomFieldMapOutput() CustomFieldMapOutput
	ToCustomFieldMapOutputWithContext(context.Context) CustomFieldMapOutput
}

type CustomFieldMap map[string]CustomFieldInput

func (CustomFieldMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CustomField)(nil)).Elem()
}

func (i CustomFieldMap) ToCustomFieldMapOutput() CustomFieldMapOutput {
	return i.ToCustomFieldMapOutputWithContext(context.Background())
}

func (i CustomFieldMap) ToCustomFieldMapOutputWithContext(ctx context.Context) CustomFieldMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CustomFieldMapOutput)
}

type CustomFieldOutput struct{ *pulumi.OutputState }

func (CustomFieldOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CustomField)(nil)).Elem()
}

func (o CustomFieldOutput) ToCustomFieldOutput() CustomFieldOutput {
	return o
}

func (o CustomFieldOutput) ToCustomFieldOutputWithContext(ctx context.Context) CustomFieldOutput {
	return o
}

// For catalog fields, the ID of the associated catalog type
func (o CustomFieldOutput) CatalogTypeId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CustomField) pulumi.StringPtrOutput { return v.CatalogTypeId }).(pulumi.StringPtrOutput)
}

// Description of the custom field
func (o CustomFieldOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomField) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Type of custom field. Possible values are: `singleSelect`, `multiSelect`, `text`, `link`, `numeric`.
func (o CustomFieldOutput) FieldType() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomField) pulumi.StringOutput { return v.FieldType }).(pulumi.StringOutput)
}

func (o CustomFieldOutput) FilterBy() CustomFieldFilterByPtrOutput {
	return o.ApplyT(func(v *CustomField) CustomFieldFilterByPtrOutput { return v.FilterBy }).(CustomFieldFilterByPtrOutput)
}

// Restrict this catalog-backed field's options to catalog entries whose `catalogAttributeId` attribute references one of `values`. This is the static counterpart to `filterBy`: rather than following whatever another custom field is set to on the incident, the filter is chosen up front and is the same for every incident. Mutually exclusive with `filterBy`.
func (o CustomFieldOutput) FixedFilter() CustomFieldFixedFilterPtrOutput {
	return o.ApplyT(func(v *CustomField) CustomFieldFixedFilterPtrOutput { return v.FixedFilter }).(CustomFieldFixedFilterPtrOutput)
}

// For catalog fields, the ID of the attribute used to group catalog entries (if applicable)
func (o CustomFieldOutput) GroupByCatalogAttributeId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CustomField) pulumi.StringPtrOutput { return v.GroupByCatalogAttributeId }).(pulumi.StringPtrOutput)
}

// Which catalog attribute provides helptext for the options
func (o CustomFieldOutput) HelptextCatalogAttributeId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CustomField) pulumi.StringPtrOutput { return v.HelptextCatalogAttributeId }).(pulumi.StringPtrOutput)
}

// Human readable name for the custom field
func (o CustomFieldOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomField) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

type CustomFieldArrayOutput struct{ *pulumi.OutputState }

func (CustomFieldArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CustomField)(nil)).Elem()
}

func (o CustomFieldArrayOutput) ToCustomFieldArrayOutput() CustomFieldArrayOutput {
	return o
}

func (o CustomFieldArrayOutput) ToCustomFieldArrayOutputWithContext(ctx context.Context) CustomFieldArrayOutput {
	return o
}

func (o CustomFieldArrayOutput) Index(i pulumi.IntInput) CustomFieldOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CustomField {
		return vs[0].([]*CustomField)[vs[1].(int)]
	}).(CustomFieldOutput)
}

type CustomFieldMapOutput struct{ *pulumi.OutputState }

func (CustomFieldMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CustomField)(nil)).Elem()
}

func (o CustomFieldMapOutput) ToCustomFieldMapOutput() CustomFieldMapOutput {
	return o
}

func (o CustomFieldMapOutput) ToCustomFieldMapOutputWithContext(ctx context.Context) CustomFieldMapOutput {
	return o
}

func (o CustomFieldMapOutput) MapIndex(k pulumi.StringInput) CustomFieldOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CustomField {
		return vs[0].(map[string]*CustomField)[vs[1].(string)]
	}).(CustomFieldOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CustomFieldInput)(nil)).Elem(), &CustomField{})
	pulumi.RegisterInputType(reflect.TypeOf((*CustomFieldArrayInput)(nil)).Elem(), CustomFieldArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CustomFieldMapInput)(nil)).Elem(), CustomFieldMap{})
	pulumi.RegisterOutputType(CustomFieldOutput{})
	pulumi.RegisterOutputType(CustomFieldArrayOutput{})
	pulumi.RegisterOutputType(CustomFieldMapOutput{})
}
