// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incident

import (
	"context"
	"reflect"

	"errors"
	"github.com/incident-io/pulumi-incident/sdk/go/incident/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Create and manage escalation paths, written as a flat map of named node sequences.
//
// Each sequence runs its nodes in order and either ends with a `branch`, which names the sequences to continue down, or falls off the end of the escalation path.
//
// We'd generally recommend building escalation paths in our [web dashboard](https://app.incident.io/~/on-call/escalation-paths) and using the 'Export' flow to generate your Terraform.
//
// ## Upgrading from v6
//
// Before v7 this resource nested a branch's nodes inside it, as `if_else.then_path` and
// `if_else.else_path`. Terraform schemas can't recurse indefinitely, so it stopped at five
// levels of branching, and a path that branched more than that couldn't be written at all.
//
// It now names its sequences instead. A `branch` says which sequence to continue down rather
// than holding its nodes, so every sequence sits at the same depth in the config and there's no
// nesting limit. It also swaps `repeat` for `loop`, which names the node to go back to, and
// replaces the raw engine `conditions` on a branch with a `branch.if` block holding one
// attribute per thing an escalation can be tested on.
//
// Your escalation path's state carries over: the `path` it holds is dropped and the rest is
// read back from the API. Rewrite the `path` as `sequences` in your configuration, and note
// that this resource names the sequences itself when it reads them back - the one the path
// starts with is `main`, and the sequences a branch leads to are `mainThen` and
// `mainElse`, after the sequence the branch sits in. A configuration that calls them
// something else plans a change, so run `pulumi preview` before you apply.
//
// Write out each level's `ackMode` while you are there. This resource defaults it to
// `first` where v6 defaulted it to `all`, and a default applies wherever the configuration
// is silent - so a level that never set `ackMode` plans a change from `all` to `first`,
// and applying it changes how the level pages: with `first`, the first person to acknowledge
// cancels everyone else's escalation on that level. Set `ackMode = "all"` on every level
// whose behaviour you mean to keep.
//
// If you were already using `EscalationPathBeta`, none of this applies: that name
// still works in v7, and renaming it to this one is a `moved` block whenever you want to make
// it.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/incident-io/pulumi-incident/sdk/go/incident"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Look up a user to page. Escalation path targets can also be schedules or
//			// Slack/Teams channels; see the `type` attribute on each target.
//			onCall, err := incident.GetUser(ctx, &incident.GetUserArgs{
//				Email: pulumi.StringRef("on-call@example.com"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			// A last resort path, which the path below hands over to out of hours.
//			fallback, err := incident.NewEscalationPath(ctx, "fallback", &incident.EscalationPathArgs{
//				Name: pulumi.String("Fallback"),
//				Path: []map[string]interface{}{
//					map[string]interface{}{
//						"type": "level",
//						"level": map[string]interface{}{
//							"targets": []map[string]interface{}{
//								map[string]interface{}{
//									"type":    "user",
//									"id":      onCall.Id,
//									"urgency": "high",
//								},
//							},
//							"timeToAckSeconds": 300,
//						},
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			// The same escalation path as the incident_escalation_path example, written as a
//			// flat map of sequences: if in working hours, page with high urgency; otherwise
//			// page with low urgency.
//			_, err = incident.NewEscalationPath(ctx, "urgent_support", &incident.EscalationPathArgs{
//				Name:  pulumi.String("Urgent support"),
//				Start: pulumi.String("main"),
//				Sequences: incident.EscalationPathSequencesMap{
//					"main": &incident.EscalationPathSequencesArgs{
//						Nodes: incident.EscalationPathSequencesNodeArray{
//							&incident.EscalationPathSequencesNodeArgs{
//								Id: pulumi.String("start"),
//								Branch: &incident.EscalationPathSequencesNodeBranchArgs{
//									If: &incident.EscalationPathSequencesNodeBranchIfArgs{
//										WorkingHoursActive: pulumi.String("UK"),
//									},
//									Then: pulumi.String("in_hours"),
//									Else: pulumi.String("out_of_hours"),
//								},
//							},
//						},
//					},
//					"in_hours": &incident.EscalationPathSequencesArgs{
//						Nodes: incident.EscalationPathSequencesNodeArray{
//							&incident.EscalationPathSequencesNodeArgs{
//								Level: &incident.EscalationPathSequencesNodeLevelArgs{
//									Targets: incident.EscalationPathSequencesNodeLevelTargetArray{
//										&incident.EscalationPathSequencesNodeLevelTargetArgs{
//											Type:    pulumi.String("user"),
//											Id:      pulumi.String(onCall.Id),
//											Urgency: pulumi.String("high"),
//										},
//									},
//									TimeToAckSeconds: pulumi.Int(300),
//								},
//							},
//							&incident.EscalationPathSequencesNodeArgs{
//								Delay: &incident.EscalationPathSequencesNodeDelayArgs{
//									DelaySeconds: pulumi.Int(120),
//								},
//							},
//							&incident.EscalationPathSequencesNodeArgs{
//								Loop: &incident.EscalationPathSequencesNodeLoopArgs{
//									BackTo: pulumi.String("start"),
//									Times:  pulumi.Int(3),
//								},
//							},
//						},
//					},
//					"out_of_hours": &incident.EscalationPathSequencesArgs{
//						Nodes: incident.EscalationPathSequencesNodeArray{
//							&incident.EscalationPathSequencesNodeArgs{
//								Level: &incident.EscalationPathSequencesNodeLevelArgs{
//									Targets: incident.EscalationPathSequencesNodeLevelTargetArray{
//										&incident.EscalationPathSequencesNodeLevelTargetArgs{
//											Type:    pulumi.String("user"),
//											Id:      pulumi.String(onCall.Id),
//											Urgency: pulumi.String("low"),
//										},
//									},
//									TimeToAckSeconds: pulumi.Int(300),
//								},
//							},
//							&incident.EscalationPathSequencesNodeArgs{
//								EscalationPath: &incident.EscalationPathSequencesNodeEscalationPathArgs{
//									EscalationPathId: fallback.ID().ToIDOutput().ToStringOutput(),
//								},
//							},
//						},
//					},
//				},
//				WorkingHours: incident.EscalationPathWorkingHourArray{
//					&incident.EscalationPathWorkingHourArgs{
//						Id:       pulumi.String("UK"),
//						Name:     pulumi.String("UK"),
//						Timezone: pulumi.String("Europe/London"),
//						WeekdayIntervals: incident.EscalationPathWorkingHourWeekdayIntervalArray{
//							&incident.EscalationPathWorkingHourWeekdayIntervalArgs{
//								Weekday:   pulumi.String("monday"),
//								StartTime: pulumi.String("09:00"),
//								EndTime:   pulumi.String("17:00"),
//							},
//						},
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type EscalationPath struct {
	pulumi.CustomResourceState

	// The name of this escalation path, for the user's reference.
	Name pulumi.StringOutput `pulumi:"name"`
	// Controls if an escalation will repeat after acknowledgement, when the alert is unresolved. When configured, it will repeat after the specified delay.
	RepeatConfig EscalationPathRepeatConfigPtrOutput `pulumi:"repeatConfig"`
	// Named sequences of nodes, keyed by a name you choose. Each sequence either ends with a `branch` node or runs off the end of the escalation path. Branches reference other sequences by key.
	Sequences EscalationPathSequencesMapOutput `pulumi:"sequences"`
	// The key of the sequence this escalation path begins with.
	Start pulumi.StringOutput `pulumi:"start"`
	// IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required.
	TeamIds pulumi.StringArrayOutput `pulumi:"teamIds"`
	// The working hours for this escalation path.
	WorkingHours EscalationPathWorkingHourArrayOutput `pulumi:"workingHours"`
}

// NewEscalationPath registers a new resource with the given unique name, arguments, and options.
func NewEscalationPath(ctx *pulumi.Context,
	name string, args *EscalationPathArgs, opts ...pulumi.ResourceOption) (*EscalationPath, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Sequences == nil {
		return nil, errors.New("invalid value for required argument 'Sequences'")
	}
	if args.Start == nil {
		return nil, errors.New("invalid value for required argument 'Start'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource EscalationPath
	err := ctx.RegisterResource("incident:index/escalationPath:EscalationPath", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetEscalationPath gets an existing EscalationPath resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetEscalationPath(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *EscalationPathState, opts ...pulumi.ResourceOption) (*EscalationPath, error) {
	var resource EscalationPath
	err := ctx.ReadResource("incident:index/escalationPath:EscalationPath", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering EscalationPath resources.
type escalationPathState struct {
	// The name of this escalation path, for the user's reference.
	Name *string `pulumi:"name"`
	// Controls if an escalation will repeat after acknowledgement, when the alert is unresolved. When configured, it will repeat after the specified delay.
	RepeatConfig *EscalationPathRepeatConfig `pulumi:"repeatConfig"`
	// Named sequences of nodes, keyed by a name you choose. Each sequence either ends with a `branch` node or runs off the end of the escalation path. Branches reference other sequences by key.
	Sequences map[string]EscalationPathSequences `pulumi:"sequences"`
	// The key of the sequence this escalation path begins with.
	Start *string `pulumi:"start"`
	// IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required.
	TeamIds []string `pulumi:"teamIds"`
	// The working hours for this escalation path.
	WorkingHours []EscalationPathWorkingHour `pulumi:"workingHours"`
}

type EscalationPathState struct {
	// The name of this escalation path, for the user's reference.
	Name pulumi.StringPtrInput
	// Controls if an escalation will repeat after acknowledgement, when the alert is unresolved. When configured, it will repeat after the specified delay.
	RepeatConfig EscalationPathRepeatConfigPtrInput
	// Named sequences of nodes, keyed by a name you choose. Each sequence either ends with a `branch` node or runs off the end of the escalation path. Branches reference other sequences by key.
	Sequences EscalationPathSequencesMapInput
	// The key of the sequence this escalation path begins with.
	Start pulumi.StringPtrInput
	// IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required.
	TeamIds pulumi.StringArrayInput
	// The working hours for this escalation path.
	WorkingHours EscalationPathWorkingHourArrayInput
}

func (EscalationPathState) ElementType() reflect.Type {
	return reflect.TypeOf((*escalationPathState)(nil)).Elem()
}

type escalationPathArgs struct {
	// The name of this escalation path, for the user's reference.
	Name *string `pulumi:"name"`
	// Controls if an escalation will repeat after acknowledgement, when the alert is unresolved. When configured, it will repeat after the specified delay.
	RepeatConfig *EscalationPathRepeatConfig `pulumi:"repeatConfig"`
	// Named sequences of nodes, keyed by a name you choose. Each sequence either ends with a `branch` node or runs off the end of the escalation path. Branches reference other sequences by key.
	Sequences map[string]EscalationPathSequences `pulumi:"sequences"`
	// The key of the sequence this escalation path begins with.
	Start string `pulumi:"start"`
	// IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required.
	TeamIds []string `pulumi:"teamIds"`
	// The working hours for this escalation path.
	WorkingHours []EscalationPathWorkingHour `pulumi:"workingHours"`
}

// The set of arguments for constructing a EscalationPath resource.
type EscalationPathArgs struct {
	// The name of this escalation path, for the user's reference.
	Name pulumi.StringPtrInput
	// Controls if an escalation will repeat after acknowledgement, when the alert is unresolved. When configured, it will repeat after the specified delay.
	RepeatConfig EscalationPathRepeatConfigPtrInput
	// Named sequences of nodes, keyed by a name you choose. Each sequence either ends with a `branch` node or runs off the end of the escalation path. Branches reference other sequences by key.
	Sequences EscalationPathSequencesMapInput
	// The key of the sequence this escalation path begins with.
	Start pulumi.StringInput
	// IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required.
	TeamIds pulumi.StringArrayInput
	// The working hours for this escalation path.
	WorkingHours EscalationPathWorkingHourArrayInput
}

func (EscalationPathArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*escalationPathArgs)(nil)).Elem()
}

type EscalationPathInput interface {
	pulumi.Input

	ToEscalationPathOutput() EscalationPathOutput
	ToEscalationPathOutputWithContext(ctx context.Context) EscalationPathOutput
}

func (*EscalationPath) ElementType() reflect.Type {
	return reflect.TypeOf((**EscalationPath)(nil)).Elem()
}

func (i *EscalationPath) ToEscalationPathOutput() EscalationPathOutput {
	return i.ToEscalationPathOutputWithContext(context.Background())
}

func (i *EscalationPath) ToEscalationPathOutputWithContext(ctx context.Context) EscalationPathOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EscalationPathOutput)
}

// EscalationPathArrayInput is an input type that accepts EscalationPathArray and EscalationPathArrayOutput values.
// You can construct a concrete instance of `EscalationPathArrayInput` via:
//
//	EscalationPathArray{ EscalationPathArgs{...} }
type EscalationPathArrayInput interface {
	pulumi.Input

	ToEscalationPathArrayOutput() EscalationPathArrayOutput
	ToEscalationPathArrayOutputWithContext(context.Context) EscalationPathArrayOutput
}

type EscalationPathArray []EscalationPathInput

func (EscalationPathArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*EscalationPath)(nil)).Elem()
}

func (i EscalationPathArray) ToEscalationPathArrayOutput() EscalationPathArrayOutput {
	return i.ToEscalationPathArrayOutputWithContext(context.Background())
}

func (i EscalationPathArray) ToEscalationPathArrayOutputWithContext(ctx context.Context) EscalationPathArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EscalationPathArrayOutput)
}

// EscalationPathMapInput is an input type that accepts EscalationPathMap and EscalationPathMapOutput values.
// You can construct a concrete instance of `EscalationPathMapInput` via:
//
//	EscalationPathMap{ "key": EscalationPathArgs{...} }
type EscalationPathMapInput interface {
	pulumi.Input

	ToEscalationPathMapOutput() EscalationPathMapOutput
	ToEscalationPathMapOutputWithContext(context.Context) EscalationPathMapOutput
}

type EscalationPathMap map[string]EscalationPathInput

func (EscalationPathMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*EscalationPath)(nil)).Elem()
}

func (i EscalationPathMap) ToEscalationPathMapOutput() EscalationPathMapOutput {
	return i.ToEscalationPathMapOutputWithContext(context.Background())
}

func (i EscalationPathMap) ToEscalationPathMapOutputWithContext(ctx context.Context) EscalationPathMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EscalationPathMapOutput)
}

type EscalationPathOutput struct{ *pulumi.OutputState }

func (EscalationPathOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**EscalationPath)(nil)).Elem()
}

func (o EscalationPathOutput) ToEscalationPathOutput() EscalationPathOutput {
	return o
}

func (o EscalationPathOutput) ToEscalationPathOutputWithContext(ctx context.Context) EscalationPathOutput {
	return o
}

// The name of this escalation path, for the user's reference.
func (o EscalationPathOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *EscalationPath) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Controls if an escalation will repeat after acknowledgement, when the alert is unresolved. When configured, it will repeat after the specified delay.
func (o EscalationPathOutput) RepeatConfig() EscalationPathRepeatConfigPtrOutput {
	return o.ApplyT(func(v *EscalationPath) EscalationPathRepeatConfigPtrOutput { return v.RepeatConfig }).(EscalationPathRepeatConfigPtrOutput)
}

// Named sequences of nodes, keyed by a name you choose. Each sequence either ends with a `branch` node or runs off the end of the escalation path. Branches reference other sequences by key.
func (o EscalationPathOutput) Sequences() EscalationPathSequencesMapOutput {
	return o.ApplyT(func(v *EscalationPath) EscalationPathSequencesMapOutput { return v.Sequences }).(EscalationPathSequencesMapOutput)
}

// The key of the sequence this escalation path begins with.
func (o EscalationPathOutput) Start() pulumi.StringOutput {
	return o.ApplyT(func(v *EscalationPath) pulumi.StringOutput { return v.Start }).(pulumi.StringOutput)
}

// IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required.
func (o EscalationPathOutput) TeamIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *EscalationPath) pulumi.StringArrayOutput { return v.TeamIds }).(pulumi.StringArrayOutput)
}

// The working hours for this escalation path.
func (o EscalationPathOutput) WorkingHours() EscalationPathWorkingHourArrayOutput {
	return o.ApplyT(func(v *EscalationPath) EscalationPathWorkingHourArrayOutput { return v.WorkingHours }).(EscalationPathWorkingHourArrayOutput)
}

type EscalationPathArrayOutput struct{ *pulumi.OutputState }

func (EscalationPathArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*EscalationPath)(nil)).Elem()
}

func (o EscalationPathArrayOutput) ToEscalationPathArrayOutput() EscalationPathArrayOutput {
	return o
}

func (o EscalationPathArrayOutput) ToEscalationPathArrayOutputWithContext(ctx context.Context) EscalationPathArrayOutput {
	return o
}

func (o EscalationPathArrayOutput) Index(i pulumi.IntInput) EscalationPathOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *EscalationPath {
		return vs[0].([]*EscalationPath)[vs[1].(int)]
	}).(EscalationPathOutput)
}

type EscalationPathMapOutput struct{ *pulumi.OutputState }

func (EscalationPathMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*EscalationPath)(nil)).Elem()
}

func (o EscalationPathMapOutput) ToEscalationPathMapOutput() EscalationPathMapOutput {
	return o
}

func (o EscalationPathMapOutput) ToEscalationPathMapOutputWithContext(ctx context.Context) EscalationPathMapOutput {
	return o
}

func (o EscalationPathMapOutput) MapIndex(k pulumi.StringInput) EscalationPathOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *EscalationPath {
		return vs[0].(map[string]*EscalationPath)[vs[1].(string)]
	}).(EscalationPathOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*EscalationPathInput)(nil)).Elem(), &EscalationPath{})
	pulumi.RegisterInputType(reflect.TypeOf((*EscalationPathArrayInput)(nil)).Elem(), EscalationPathArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*EscalationPathMapInput)(nil)).Elem(), EscalationPathMap{})
	pulumi.RegisterOutputType(EscalationPathOutput{})
	pulumi.RegisterOutputType(EscalationPathArrayOutput{})
	pulumi.RegisterOutputType(EscalationPathMapOutput{})
}
