// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incident

import (
	"context"
	"reflect"

	"github.com/incident-io/pulumi-incident/sdk/go/incident/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Create and manage announcement rules.
//
// An announcement rule posts an announcement of each incident that matches its conditions
// into the channels it lists, rendered with an announcement template.
//
// Use this data source to look up an existing announcement rule, either by `id` or by `name`, without managing it as an `AnnouncementRule` resource. Set exactly one of the two lookup attributes; setting both, or neither, is rejected at plan time.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/incident-io/pulumi-incident/sdk/go/incident"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Look up an existing announcement rule by name, such as one created in the dashboard.
//			critical, err := incident.GetAnnouncementRule(ctx, &incident.LookupAnnouncementRuleArgs{
//				Name: pulumi.StringRef("Critical incidents"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			// Or by ID, to reference a rule another module manages.
//			_, err = incident.GetAnnouncementRule(ctx, &incident.LookupAnnouncementRuleArgs{
//				Id: pulumi.StringRef("01G0J1EXE7AXZ2C93K61WBPYEH"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("criticalSlackChannelIds", critical.SlackChannelIds)
//			return nil
//		})
//	}
//
// ```
func LookupAnnouncementRule(ctx *pulumi.Context, args *LookupAnnouncementRuleArgs, opts ...pulumi.InvokeOption) (*LookupAnnouncementRuleResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupAnnouncementRuleResult
	err := ctx.Invoke("incident:index/getAnnouncementRule:getAnnouncementRule", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAnnouncementRule.
type LookupAnnouncementRuleArgs struct {
	// Unique identifier for this announcement rule
	Id *string `pulumi:"id"`
	// Human readable name for the rule
	Name *string `pulumi:"name"`
}

// A collection of values returned by getAnnouncementRule.
type LookupAnnouncementRuleResult struct {
	// The condition groups to apply in this filter. Only one group needs to be satisfied for the filter to pass.
	ConditionGroups []GetAnnouncementRuleConditionGroup `pulumi:"conditionGroups"`
	// Whether to remove announcement posts when the incident no longer matches this rule's conditions. Possible values are: `leaveInPlace`, `remove`.
	ConditionsNoLongerApplyBehaviour string `pulumi:"conditionsNoLongerApplyBehaviour"`
	// When the rule was created
	CreatedAt string `pulumi:"createdAt"`
	// Unique identifier for this announcement rule
	Id string `pulumi:"id"`
	// Microsoft Teams channels to post announcements into, as team*id/channel*id, when the organisation uses Microsoft Teams
	MicrosoftTeamsChannelIds []string `pulumi:"microsoftTeamsChannelIds"`
	// Which incidents are announced: live incidents only, or triage incidents too. Possible values are: `liveAndClosed`, `includeTriage`, `includeTriageAndMerged`, `includeDeclinedAndMerged`, `includeAll`.
	Mode string `pulumi:"mode"`
	// Human readable name for the rule
	Name string `pulumi:"name"`
	// IDs of the teams that own this rule
	OwningTeamIds []string `pulumi:"owningTeamIds"`
	// Which private incidents this rule announces: every private incident (all), those an owning team can see (owning_teams), or none. Possible values are: `all`, `owningTeams`, `none`.
	PrivateIncidentScope string `pulumi:"privateIncidentScope"`
	// IDs of the Slack channels to post announcements into, when the organisation uses Slack
	SlackChannelIds []string `pulumi:"slackChannelIds"`
	// ID of the announcement template used to render this rule's posts
	TemplateId string `pulumi:"templateId"`
	// Where incident updates are shared once the incident is announced. Possible values are: `none`, `thread`, `threadAndChannel`.
	UpdateSharingMode string `pulumi:"updateSharingMode"`
	// When the rule was last updated
	UpdatedAt string `pulumi:"updatedAt"`
}

func LookupAnnouncementRuleOutput(ctx *pulumi.Context, args LookupAnnouncementRuleOutputArgs, opts ...pulumi.InvokeOption) LookupAnnouncementRuleResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("incident:index/getAnnouncementRule:getAnnouncementRule", args, LookupAnnouncementRuleResultOutput{}, options).(LookupAnnouncementRuleResultOutput)
}

// A collection of arguments for invoking getAnnouncementRule.
type LookupAnnouncementRuleOutputArgs struct {
	// Unique identifier for this announcement rule
	Id pulumi.StringPtrInput `pulumi:"id"`
	// Human readable name for the rule
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (LookupAnnouncementRuleOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAnnouncementRuleArgs)(nil)).Elem()
}

// A collection of values returned by getAnnouncementRule.
type LookupAnnouncementRuleResultOutput struct{ *pulumi.OutputState }

func (LookupAnnouncementRuleResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAnnouncementRuleResult)(nil)).Elem()
}

func (o LookupAnnouncementRuleResultOutput) ToLookupAnnouncementRuleResultOutput() LookupAnnouncementRuleResultOutput {
	return o
}

func (o LookupAnnouncementRuleResultOutput) ToLookupAnnouncementRuleResultOutputWithContext(ctx context.Context) LookupAnnouncementRuleResultOutput {
	return o
}

// The condition groups to apply in this filter. Only one group needs to be satisfied for the filter to pass.
func (o LookupAnnouncementRuleResultOutput) ConditionGroups() GetAnnouncementRuleConditionGroupArrayOutput {
	return o.ApplyT(func(v LookupAnnouncementRuleResult) []GetAnnouncementRuleConditionGroup { return v.ConditionGroups }).(GetAnnouncementRuleConditionGroupArrayOutput)
}

// Whether to remove announcement posts when the incident no longer matches this rule's conditions. Possible values are: `leaveInPlace`, `remove`.
func (o LookupAnnouncementRuleResultOutput) ConditionsNoLongerApplyBehaviour() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAnnouncementRuleResult) string { return v.ConditionsNoLongerApplyBehaviour }).(pulumi.StringOutput)
}

// When the rule was created
func (o LookupAnnouncementRuleResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAnnouncementRuleResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// Unique identifier for this announcement rule
func (o LookupAnnouncementRuleResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAnnouncementRuleResult) string { return v.Id }).(pulumi.StringOutput)
}

// Microsoft Teams channels to post announcements into, as team*id/channel*id, when the organisation uses Microsoft Teams
func (o LookupAnnouncementRuleResultOutput) MicrosoftTeamsChannelIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupAnnouncementRuleResult) []string { return v.MicrosoftTeamsChannelIds }).(pulumi.StringArrayOutput)
}

// Which incidents are announced: live incidents only, or triage incidents too. Possible values are: `liveAndClosed`, `includeTriage`, `includeTriageAndMerged`, `includeDeclinedAndMerged`, `includeAll`.
func (o LookupAnnouncementRuleResultOutput) Mode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAnnouncementRuleResult) string { return v.Mode }).(pulumi.StringOutput)
}

// Human readable name for the rule
func (o LookupAnnouncementRuleResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAnnouncementRuleResult) string { return v.Name }).(pulumi.StringOutput)
}

// IDs of the teams that own this rule
func (o LookupAnnouncementRuleResultOutput) OwningTeamIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupAnnouncementRuleResult) []string { return v.OwningTeamIds }).(pulumi.StringArrayOutput)
}

// Which private incidents this rule announces: every private incident (all), those an owning team can see (owning_teams), or none. Possible values are: `all`, `owningTeams`, `none`.
func (o LookupAnnouncementRuleResultOutput) PrivateIncidentScope() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAnnouncementRuleResult) string { return v.PrivateIncidentScope }).(pulumi.StringOutput)
}

// IDs of the Slack channels to post announcements into, when the organisation uses Slack
func (o LookupAnnouncementRuleResultOutput) SlackChannelIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupAnnouncementRuleResult) []string { return v.SlackChannelIds }).(pulumi.StringArrayOutput)
}

// ID of the announcement template used to render this rule's posts
func (o LookupAnnouncementRuleResultOutput) TemplateId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAnnouncementRuleResult) string { return v.TemplateId }).(pulumi.StringOutput)
}

// Where incident updates are shared once the incident is announced. Possible values are: `none`, `thread`, `threadAndChannel`.
func (o LookupAnnouncementRuleResultOutput) UpdateSharingMode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAnnouncementRuleResult) string { return v.UpdateSharingMode }).(pulumi.StringOutput)
}

// When the rule was last updated
func (o LookupAnnouncementRuleResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAnnouncementRuleResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAnnouncementRuleResultOutput{})
}
