// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incident

import (
	"context"
	"reflect"

	"github.com/incident-io/pulumi-incident/sdk/go/incident/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides information about a catalog type attribute.
func LookupCatalogTypeAttribute(ctx *pulumi.Context, args *LookupCatalogTypeAttributeArgs, opts ...pulumi.InvokeOption) (*LookupCatalogTypeAttributeResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupCatalogTypeAttributeResult
	err := ctx.Invoke("incident:index/getCatalogTypeAttribute:getCatalogTypeAttribute", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCatalogTypeAttribute.
type LookupCatalogTypeAttributeArgs struct {
	// ID of this catalog type
	CatalogTypeId string `pulumi:"catalogTypeId"`
	// The name of this attribute.
	Name string `pulumi:"name"`
}

// A collection of values returned by getCatalogTypeAttribute.
type LookupCatalogTypeAttributeResult struct {
	// Whether this attribute is an array or scalar.
	Array bool `pulumi:"array"`
	// If this is a backlink, the id of the attribute that it's linked from
	BacklinkAttribute string `pulumi:"backlinkAttribute"`
	// ID of this catalog type
	CatalogTypeId string `pulumi:"catalogTypeId"`
	// The ID of the catalog type attribute
	Id string `pulumi:"id"`
	// The name of this attribute.
	Name string `pulumi:"name"`
	// If this is a path attribute, the path that we should use to pull the data
	Paths []string `pulumi:"paths"`
	// If true, Terraform will only manage the schema of the attribute. Values for this attribute can be managed from the incident.io web dashboard.
	SchemaOnly bool `pulumi:"schemaOnly"`
	// The type of this attribute.
	Type string `pulumi:"type"`
}

func LookupCatalogTypeAttributeOutput(ctx *pulumi.Context, args LookupCatalogTypeAttributeOutputArgs, opts ...pulumi.InvokeOption) LookupCatalogTypeAttributeResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("incident:index/getCatalogTypeAttribute:getCatalogTypeAttribute", args, LookupCatalogTypeAttributeResultOutput{}, options).(LookupCatalogTypeAttributeResultOutput)
}

// A collection of arguments for invoking getCatalogTypeAttribute.
type LookupCatalogTypeAttributeOutputArgs struct {
	// ID of this catalog type
	CatalogTypeId pulumi.StringInput `pulumi:"catalogTypeId"`
	// The name of this attribute.
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupCatalogTypeAttributeOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCatalogTypeAttributeArgs)(nil)).Elem()
}

// A collection of values returned by getCatalogTypeAttribute.
type LookupCatalogTypeAttributeResultOutput struct{ *pulumi.OutputState }

func (LookupCatalogTypeAttributeResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCatalogTypeAttributeResult)(nil)).Elem()
}

func (o LookupCatalogTypeAttributeResultOutput) ToLookupCatalogTypeAttributeResultOutput() LookupCatalogTypeAttributeResultOutput {
	return o
}

func (o LookupCatalogTypeAttributeResultOutput) ToLookupCatalogTypeAttributeResultOutputWithContext(ctx context.Context) LookupCatalogTypeAttributeResultOutput {
	return o
}

// Whether this attribute is an array or scalar.
func (o LookupCatalogTypeAttributeResultOutput) Array() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupCatalogTypeAttributeResult) bool { return v.Array }).(pulumi.BoolOutput)
}

// If this is a backlink, the id of the attribute that it's linked from
func (o LookupCatalogTypeAttributeResultOutput) BacklinkAttribute() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCatalogTypeAttributeResult) string { return v.BacklinkAttribute }).(pulumi.StringOutput)
}

// ID of this catalog type
func (o LookupCatalogTypeAttributeResultOutput) CatalogTypeId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCatalogTypeAttributeResult) string { return v.CatalogTypeId }).(pulumi.StringOutput)
}

// The ID of the catalog type attribute
func (o LookupCatalogTypeAttributeResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCatalogTypeAttributeResult) string { return v.Id }).(pulumi.StringOutput)
}

// The name of this attribute.
func (o LookupCatalogTypeAttributeResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCatalogTypeAttributeResult) string { return v.Name }).(pulumi.StringOutput)
}

// If this is a path attribute, the path that we should use to pull the data
func (o LookupCatalogTypeAttributeResultOutput) Paths() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupCatalogTypeAttributeResult) []string { return v.Paths }).(pulumi.StringArrayOutput)
}

// If true, Terraform will only manage the schema of the attribute. Values for this attribute can be managed from the incident.io web dashboard.
func (o LookupCatalogTypeAttributeResultOutput) SchemaOnly() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupCatalogTypeAttributeResult) bool { return v.SchemaOnly }).(pulumi.BoolOutput)
}

// The type of this attribute.
func (o LookupCatalogTypeAttributeResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCatalogTypeAttributeResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupCatalogTypeAttributeResultOutput{})
}
