// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incident

import (
	"context"
	"reflect"

	"github.com/incident-io/pulumi-incident/sdk/go/incident/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides a list of catalog entries for a specific catalog type.
//
// ## Example Usage
func LookupCatalogEntries(ctx *pulumi.Context, args *LookupCatalogEntriesArgs, opts ...pulumi.InvokeOption) (*LookupCatalogEntriesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupCatalogEntriesResult
	err := ctx.Invoke("incident:index/getCatalogEntries:getCatalogEntries", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCatalogEntries.
type LookupCatalogEntriesArgs struct {
	// The catalog type ID to list entries for.
	CatalogTypeId string `pulumi:"catalogTypeId"`
}

// A collection of values returned by getCatalogEntries.
type LookupCatalogEntriesResult struct {
	// List of catalog entries for the specified catalog type.
	CatalogEntries []GetCatalogEntriesCatalogEntry `pulumi:"catalogEntries"`
	// The catalog type ID to list entries for.
	CatalogTypeId string `pulumi:"catalogTypeId"`
}

func LookupCatalogEntriesOutput(ctx *pulumi.Context, args LookupCatalogEntriesOutputArgs, opts ...pulumi.InvokeOption) LookupCatalogEntriesResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("incident:index/getCatalogEntries:getCatalogEntries", args, LookupCatalogEntriesResultOutput{}, options).(LookupCatalogEntriesResultOutput)
}

// A collection of arguments for invoking getCatalogEntries.
type LookupCatalogEntriesOutputArgs struct {
	// The catalog type ID to list entries for.
	CatalogTypeId pulumi.StringInput `pulumi:"catalogTypeId"`
}

func (LookupCatalogEntriesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCatalogEntriesArgs)(nil)).Elem()
}

// A collection of values returned by getCatalogEntries.
type LookupCatalogEntriesResultOutput struct{ *pulumi.OutputState }

func (LookupCatalogEntriesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCatalogEntriesResult)(nil)).Elem()
}

func (o LookupCatalogEntriesResultOutput) ToLookupCatalogEntriesResultOutput() LookupCatalogEntriesResultOutput {
	return o
}

func (o LookupCatalogEntriesResultOutput) ToLookupCatalogEntriesResultOutputWithContext(ctx context.Context) LookupCatalogEntriesResultOutput {
	return o
}

// List of catalog entries for the specified catalog type.
func (o LookupCatalogEntriesResultOutput) CatalogEntries() GetCatalogEntriesCatalogEntryArrayOutput {
	return o.ApplyT(func(v LookupCatalogEntriesResult) []GetCatalogEntriesCatalogEntry { return v.CatalogEntries }).(GetCatalogEntriesCatalogEntryArrayOutput)
}

// The catalog type ID to list entries for.
func (o LookupCatalogEntriesResultOutput) CatalogTypeId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCatalogEntriesResult) string { return v.CatalogTypeId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupCatalogEntriesResultOutput{})
}
