// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incident

import (
	"context"
	"reflect"

	"errors"
	"github.com/incident-io/pulumi-incident/sdk/go/incident/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manage a rotation on an on-call schedule.
//
// A rotation is a group of people who take turns being on call, and the cadence they
// hand over on. A schedule can hold several, and each is managed independently — so
// changing one never rewrites the others.
//
// Editing a rotation takes effect straight away, unless `rollout` says otherwise.
//
// ## Changing when shifts hand over
//
// `firstIntervalStartsAt` is the point intervals are counted from. With
// `handovers` it fixes the time of day and day of week that shifts change hands —
// the dashboard calls it the handover time.
//
// It can't change in the same apply as `rollout`. Whenever `rollout` is set the
// rotation keeps the interval start it already runs: an immediate rollout copies that
// across so the cadence doesn't move, and a phased one works backwards from the next
// handover so the new line-up slots into the rhythm people are already working. Either
// way a new `firstIntervalStartsAt` is discarded, so the provider stops the apply
// rather than storing a value that won't be kept.
//
// To change both, take it in two applies:
//
//  1. Change `firstIntervalStartsAt` on its own, with `rollout` unset. The new
//     cadence takes effect straight away.
//  2. Then make the line-up change, with `rollout` set.
//
// ## Choosing a scheduling mode
//
// `schedulingMode` decides who takes the next shift.
//
// `fair` shares time on call out evenly, tracking how much each person has already
// done and giving the next shift to whoever is behind. Someone newly added has done
// none, so `fair` tends to bring them on call sooner rather than adding them to
// the back of the queue.
//
// `sequential` goes around the list in order, so the next person on call is always
// the one after the last.
//
// For an even rotation — everyone on for the same length of time, no working hours,
// nobody joining or leaving — the two behave identically. They only diverge once
// shifts differ in length, `workingIntervals` is set, or the list of users
// changes. Reach for `sequential` when it matters that the running order is
// obvious to the people in it.
//
// ## Beta, and what happens next
//
// This resource is in beta. Its schema may still change in ways that are not
// backwards compatible, so pin the provider version if that matters to you.
//
// The plan is for these resources to become the only way to manage schedules. In
// v7.0 they lose the `_beta` suffix and `Schedule`, which declares
// its rotations inline, is removed. Until then both work and neither is deprecated.
// See `ScheduleBeta` for how the two differ and how to migrate.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/incident-io/pulumi-incident/sdk/go/incident"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// A rotation is a group of people who take turns being on call. Each one is managed
//			// on its own, so editing this rotation doesn't touch the others on the schedule.
//			_, err := incident.NewScheduleRotationBeta(ctx, "primary", &incident.ScheduleRotationBetaArgs{
//				ScheduleId: pulumi.Any(platform.Id),
//				Name:       pulumi.String("Primary"),
//				Users: pulumi.StringArray{
//					alice.Id,
//					bob.Id,
//				},
//				FirstIntervalStartsAt: pulumi.String("2024-01-08T09:00:00Z"),
//				Handovers: incident.ScheduleRotationBetaHandoverArray{
//					&incident.ScheduleRotationBetaHandoverArgs{
//						Interval:     pulumi.Int(1),
//						IntervalType: pulumi.String("weekly"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			// A rotation that only covers weekday working hours, with two people on call at
//			// once and a place in the schedule's running order.
//			_, err = incident.NewScheduleRotationBeta(ctx, "business_hours", &incident.ScheduleRotationBetaArgs{
//				ScheduleId: pulumi.Any(platform.Id),
//				Name:       pulumi.String("Business hours"),
//				Rank:       pulumi.Int(2),
//				Users: pulumi.StringArray{
//					alice.Id,
//					bob.Id,
//					carol.Id,
//				},
//				FirstIntervalStartsAt: pulumi.String("2024-01-08T09:00:00Z"),
//				Handovers: incident.ScheduleRotationBetaHandoverArray{
//					&incident.ScheduleRotationBetaHandoverArgs{
//						Interval:     pulumi.Int(1),
//						IntervalType: pulumi.String("daily"),
//					},
//				},
//				ConcurrentShifts: pulumi.Int(2),
//				WorkingIntervals: incident.ScheduleRotationBetaWorkingIntervalArray{
//					&incident.ScheduleRotationBetaWorkingIntervalArgs{
//						Weekday:   pulumi.String("monday"),
//						StartTime: pulumi.String("09:00"),
//						EndTime:   pulumi.String("17:00"),
//					},
//					&incident.ScheduleRotationBetaWorkingIntervalArgs{
//						Weekday:   pulumi.String("tuesday"),
//						StartTime: pulumi.String("09:00"),
//						EndTime:   pulumi.String("17:00"),
//					},
//					&incident.ScheduleRotationBetaWorkingIntervalArgs{
//						Weekday:   pulumi.String("wednesday"),
//						StartTime: pulumi.String("09:00"),
//						EndTime:   pulumi.String("17:00"),
//					},
//					&incident.ScheduleRotationBetaWorkingIntervalArgs{
//						Weekday:   pulumi.String("thursday"),
//						StartTime: pulumi.String("09:00"),
//						EndTime:   pulumi.String("17:00"),
//					},
//					&incident.ScheduleRotationBetaWorkingIntervalArgs{
//						Weekday:   pulumi.String("friday"),
//						StartTime: pulumi.String("09:00"),
//						EndTime:   pulumi.String("17:00"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// !/bin/bash
//
// Import a rotation using its schedule's ID and its own ID, separated by a colon.
// A rotation is only addressable through the schedule that holds it.
// Replace both IDs with real ones from your incident.io organization.
//
// ```sh
// $ pulumi import incident:index/scheduleRotationBeta:ScheduleRotationBeta example 01ABC123DEF456GHI789JKL:01MNO456PQR789STU012VWX
// ```
type ScheduleRotationBeta struct {
	pulumi.CustomResourceState

	// How many shifts run at the same time, which is how many people are on call at once. Defaults to 1, one person on call at a time. Reducing this stops scheduling the last of them, and stops any overrides on those shifts from applying.
	ConcurrentShifts pulumi.IntOutput `pulumi:"concurrentShifts"`
	// When this shape of the rotation took over. Unset when the rotation has only ever had one.
	EffectiveFrom pulumi.StringOutput `pulumi:"effectiveFrom"`
	// When the first handover interval starts being counted from, which fixes the time of day and day of week shifts change hands. The dashboard calls this the handover time.. Can't be changed in the same apply as `rollout` — see the resource description for why, and what to do instead.
	FirstIntervalStartsAt pulumi.StringOutput `pulumi:"firstIntervalStartsAt"`
	// The cadence shifts hand over on, applied in turn
	Handovers ScheduleRotationBetaHandoverArrayOutput `pulumi:"handovers"`
	// Human readable name for the rotation, unique within the schedule
	Name pulumi.StringOutput `pulumi:"name"`
	// Where this rotation sits in the schedule's running order, lowest first. Unset when it has never been ordered.
	Rank pulumi.IntPtrOutput `pulumi:"rank"`
	// How a change to this rotation is introduced: `immediate` replaces the line-up now and can change who is on call this minute, `afterCurrentShift` lets the shift on call finish first, and `afterFullRotation` waits for everyone to have taken a turn. Leave it out to replace the line-up straight away. Creating a rotation ignores it, as there's no shift to protect yet.
	Rollout pulumi.StringPtrOutput `pulumi:"rollout"`
	// ID of the schedule this rotation belongs to. Changing this replaces the rotation, as a rotation can't move between schedules.
	ScheduleId pulumi.StringOutput `pulumi:"scheduleId"`
	// How users are allocated across shifts of differing length. Possible values are: `fair`, `sequential`. Omit it to leave us to pick. For an even rotation the two behave identically — see the resource description for when they diverge.
	SchedulingMode pulumi.StringPtrOutput `pulumi:"schedulingMode"`
	// IDs of the people in the rotation, in the order they take shifts. Use the special ID `NOBODY` for a slot with nobody in it, which schedules the shift without putting anyone on call until an override covers it.
	Users pulumi.StringArrayOutput `pulumi:"users"`
	// If set, restricts on-call to these weekday intervals. Omit it to keep the rotation on call around the clock. An empty list is not valid, and is rejected at plan time — it would leave a rotation nobody is ever on call for.
	WorkingIntervals ScheduleRotationBetaWorkingIntervalArrayOutput `pulumi:"workingIntervals"`
}

// NewScheduleRotationBeta registers a new resource with the given unique name, arguments, and options.
func NewScheduleRotationBeta(ctx *pulumi.Context,
	name string, args *ScheduleRotationBetaArgs, opts ...pulumi.ResourceOption) (*ScheduleRotationBeta, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.FirstIntervalStartsAt == nil {
		return nil, errors.New("invalid value for required argument 'FirstIntervalStartsAt'")
	}
	if args.Handovers == nil {
		return nil, errors.New("invalid value for required argument 'Handovers'")
	}
	if args.ScheduleId == nil {
		return nil, errors.New("invalid value for required argument 'ScheduleId'")
	}
	if args.Users == nil {
		return nil, errors.New("invalid value for required argument 'Users'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ScheduleRotationBeta
	err := ctx.RegisterResource("incident:index/scheduleRotationBeta:ScheduleRotationBeta", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetScheduleRotationBeta gets an existing ScheduleRotationBeta resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetScheduleRotationBeta(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ScheduleRotationBetaState, opts ...pulumi.ResourceOption) (*ScheduleRotationBeta, error) {
	var resource ScheduleRotationBeta
	err := ctx.ReadResource("incident:index/scheduleRotationBeta:ScheduleRotationBeta", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ScheduleRotationBeta resources.
type scheduleRotationBetaState struct {
	// How many shifts run at the same time, which is how many people are on call at once. Defaults to 1, one person on call at a time. Reducing this stops scheduling the last of them, and stops any overrides on those shifts from applying.
	ConcurrentShifts *int `pulumi:"concurrentShifts"`
	// When this shape of the rotation took over. Unset when the rotation has only ever had one.
	EffectiveFrom *string `pulumi:"effectiveFrom"`
	// When the first handover interval starts being counted from, which fixes the time of day and day of week shifts change hands. The dashboard calls this the handover time.. Can't be changed in the same apply as `rollout` — see the resource description for why, and what to do instead.
	FirstIntervalStartsAt *string `pulumi:"firstIntervalStartsAt"`
	// The cadence shifts hand over on, applied in turn
	Handovers []ScheduleRotationBetaHandover `pulumi:"handovers"`
	// Human readable name for the rotation, unique within the schedule
	Name *string `pulumi:"name"`
	// Where this rotation sits in the schedule's running order, lowest first. Unset when it has never been ordered.
	Rank *int `pulumi:"rank"`
	// How a change to this rotation is introduced: `immediate` replaces the line-up now and can change who is on call this minute, `afterCurrentShift` lets the shift on call finish first, and `afterFullRotation` waits for everyone to have taken a turn. Leave it out to replace the line-up straight away. Creating a rotation ignores it, as there's no shift to protect yet.
	Rollout *string `pulumi:"rollout"`
	// ID of the schedule this rotation belongs to. Changing this replaces the rotation, as a rotation can't move between schedules.
	ScheduleId *string `pulumi:"scheduleId"`
	// How users are allocated across shifts of differing length. Possible values are: `fair`, `sequential`. Omit it to leave us to pick. For an even rotation the two behave identically — see the resource description for when they diverge.
	SchedulingMode *string `pulumi:"schedulingMode"`
	// IDs of the people in the rotation, in the order they take shifts. Use the special ID `NOBODY` for a slot with nobody in it, which schedules the shift without putting anyone on call until an override covers it.
	Users []string `pulumi:"users"`
	// If set, restricts on-call to these weekday intervals. Omit it to keep the rotation on call around the clock. An empty list is not valid, and is rejected at plan time — it would leave a rotation nobody is ever on call for.
	WorkingIntervals []ScheduleRotationBetaWorkingInterval `pulumi:"workingIntervals"`
}

type ScheduleRotationBetaState struct {
	// How many shifts run at the same time, which is how many people are on call at once. Defaults to 1, one person on call at a time. Reducing this stops scheduling the last of them, and stops any overrides on those shifts from applying.
	ConcurrentShifts pulumi.IntPtrInput
	// When this shape of the rotation took over. Unset when the rotation has only ever had one.
	EffectiveFrom pulumi.StringPtrInput
	// When the first handover interval starts being counted from, which fixes the time of day and day of week shifts change hands. The dashboard calls this the handover time.. Can't be changed in the same apply as `rollout` — see the resource description for why, and what to do instead.
	FirstIntervalStartsAt pulumi.StringPtrInput
	// The cadence shifts hand over on, applied in turn
	Handovers ScheduleRotationBetaHandoverArrayInput
	// Human readable name for the rotation, unique within the schedule
	Name pulumi.StringPtrInput
	// Where this rotation sits in the schedule's running order, lowest first. Unset when it has never been ordered.
	Rank pulumi.IntPtrInput
	// How a change to this rotation is introduced: `immediate` replaces the line-up now and can change who is on call this minute, `afterCurrentShift` lets the shift on call finish first, and `afterFullRotation` waits for everyone to have taken a turn. Leave it out to replace the line-up straight away. Creating a rotation ignores it, as there's no shift to protect yet.
	Rollout pulumi.StringPtrInput
	// ID of the schedule this rotation belongs to. Changing this replaces the rotation, as a rotation can't move between schedules.
	ScheduleId pulumi.StringPtrInput
	// How users are allocated across shifts of differing length. Possible values are: `fair`, `sequential`. Omit it to leave us to pick. For an even rotation the two behave identically — see the resource description for when they diverge.
	SchedulingMode pulumi.StringPtrInput
	// IDs of the people in the rotation, in the order they take shifts. Use the special ID `NOBODY` for a slot with nobody in it, which schedules the shift without putting anyone on call until an override covers it.
	Users pulumi.StringArrayInput
	// If set, restricts on-call to these weekday intervals. Omit it to keep the rotation on call around the clock. An empty list is not valid, and is rejected at plan time — it would leave a rotation nobody is ever on call for.
	WorkingIntervals ScheduleRotationBetaWorkingIntervalArrayInput
}

func (ScheduleRotationBetaState) ElementType() reflect.Type {
	return reflect.TypeOf((*scheduleRotationBetaState)(nil)).Elem()
}

type scheduleRotationBetaArgs struct {
	// How many shifts run at the same time, which is how many people are on call at once. Defaults to 1, one person on call at a time. Reducing this stops scheduling the last of them, and stops any overrides on those shifts from applying.
	ConcurrentShifts *int `pulumi:"concurrentShifts"`
	// When the first handover interval starts being counted from, which fixes the time of day and day of week shifts change hands. The dashboard calls this the handover time.. Can't be changed in the same apply as `rollout` — see the resource description for why, and what to do instead.
	FirstIntervalStartsAt string `pulumi:"firstIntervalStartsAt"`
	// The cadence shifts hand over on, applied in turn
	Handovers []ScheduleRotationBetaHandover `pulumi:"handovers"`
	// Human readable name for the rotation, unique within the schedule
	Name *string `pulumi:"name"`
	// Where this rotation sits in the schedule's running order, lowest first. Unset when it has never been ordered.
	Rank *int `pulumi:"rank"`
	// How a change to this rotation is introduced: `immediate` replaces the line-up now and can change who is on call this minute, `afterCurrentShift` lets the shift on call finish first, and `afterFullRotation` waits for everyone to have taken a turn. Leave it out to replace the line-up straight away. Creating a rotation ignores it, as there's no shift to protect yet.
	Rollout *string `pulumi:"rollout"`
	// ID of the schedule this rotation belongs to. Changing this replaces the rotation, as a rotation can't move between schedules.
	ScheduleId string `pulumi:"scheduleId"`
	// How users are allocated across shifts of differing length. Possible values are: `fair`, `sequential`. Omit it to leave us to pick. For an even rotation the two behave identically — see the resource description for when they diverge.
	SchedulingMode *string `pulumi:"schedulingMode"`
	// IDs of the people in the rotation, in the order they take shifts. Use the special ID `NOBODY` for a slot with nobody in it, which schedules the shift without putting anyone on call until an override covers it.
	Users []string `pulumi:"users"`
	// If set, restricts on-call to these weekday intervals. Omit it to keep the rotation on call around the clock. An empty list is not valid, and is rejected at plan time — it would leave a rotation nobody is ever on call for.
	WorkingIntervals []ScheduleRotationBetaWorkingInterval `pulumi:"workingIntervals"`
}

// The set of arguments for constructing a ScheduleRotationBeta resource.
type ScheduleRotationBetaArgs struct {
	// How many shifts run at the same time, which is how many people are on call at once. Defaults to 1, one person on call at a time. Reducing this stops scheduling the last of them, and stops any overrides on those shifts from applying.
	ConcurrentShifts pulumi.IntPtrInput
	// When the first handover interval starts being counted from, which fixes the time of day and day of week shifts change hands. The dashboard calls this the handover time.. Can't be changed in the same apply as `rollout` — see the resource description for why, and what to do instead.
	FirstIntervalStartsAt pulumi.StringInput
	// The cadence shifts hand over on, applied in turn
	Handovers ScheduleRotationBetaHandoverArrayInput
	// Human readable name for the rotation, unique within the schedule
	Name pulumi.StringPtrInput
	// Where this rotation sits in the schedule's running order, lowest first. Unset when it has never been ordered.
	Rank pulumi.IntPtrInput
	// How a change to this rotation is introduced: `immediate` replaces the line-up now and can change who is on call this minute, `afterCurrentShift` lets the shift on call finish first, and `afterFullRotation` waits for everyone to have taken a turn. Leave it out to replace the line-up straight away. Creating a rotation ignores it, as there's no shift to protect yet.
	Rollout pulumi.StringPtrInput
	// ID of the schedule this rotation belongs to. Changing this replaces the rotation, as a rotation can't move between schedules.
	ScheduleId pulumi.StringInput
	// How users are allocated across shifts of differing length. Possible values are: `fair`, `sequential`. Omit it to leave us to pick. For an even rotation the two behave identically — see the resource description for when they diverge.
	SchedulingMode pulumi.StringPtrInput
	// IDs of the people in the rotation, in the order they take shifts. Use the special ID `NOBODY` for a slot with nobody in it, which schedules the shift without putting anyone on call until an override covers it.
	Users pulumi.StringArrayInput
	// If set, restricts on-call to these weekday intervals. Omit it to keep the rotation on call around the clock. An empty list is not valid, and is rejected at plan time — it would leave a rotation nobody is ever on call for.
	WorkingIntervals ScheduleRotationBetaWorkingIntervalArrayInput
}

func (ScheduleRotationBetaArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*scheduleRotationBetaArgs)(nil)).Elem()
}

type ScheduleRotationBetaInput interface {
	pulumi.Input

	ToScheduleRotationBetaOutput() ScheduleRotationBetaOutput
	ToScheduleRotationBetaOutputWithContext(ctx context.Context) ScheduleRotationBetaOutput
}

func (*ScheduleRotationBeta) ElementType() reflect.Type {
	return reflect.TypeOf((**ScheduleRotationBeta)(nil)).Elem()
}

func (i *ScheduleRotationBeta) ToScheduleRotationBetaOutput() ScheduleRotationBetaOutput {
	return i.ToScheduleRotationBetaOutputWithContext(context.Background())
}

func (i *ScheduleRotationBeta) ToScheduleRotationBetaOutputWithContext(ctx context.Context) ScheduleRotationBetaOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ScheduleRotationBetaOutput)
}

// ScheduleRotationBetaArrayInput is an input type that accepts ScheduleRotationBetaArray and ScheduleRotationBetaArrayOutput values.
// You can construct a concrete instance of `ScheduleRotationBetaArrayInput` via:
//
//	ScheduleRotationBetaArray{ ScheduleRotationBetaArgs{...} }
type ScheduleRotationBetaArrayInput interface {
	pulumi.Input

	ToScheduleRotationBetaArrayOutput() ScheduleRotationBetaArrayOutput
	ToScheduleRotationBetaArrayOutputWithContext(context.Context) ScheduleRotationBetaArrayOutput
}

type ScheduleRotationBetaArray []ScheduleRotationBetaInput

func (ScheduleRotationBetaArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ScheduleRotationBeta)(nil)).Elem()
}

func (i ScheduleRotationBetaArray) ToScheduleRotationBetaArrayOutput() ScheduleRotationBetaArrayOutput {
	return i.ToScheduleRotationBetaArrayOutputWithContext(context.Background())
}

func (i ScheduleRotationBetaArray) ToScheduleRotationBetaArrayOutputWithContext(ctx context.Context) ScheduleRotationBetaArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ScheduleRotationBetaArrayOutput)
}

// ScheduleRotationBetaMapInput is an input type that accepts ScheduleRotationBetaMap and ScheduleRotationBetaMapOutput values.
// You can construct a concrete instance of `ScheduleRotationBetaMapInput` via:
//
//	ScheduleRotationBetaMap{ "key": ScheduleRotationBetaArgs{...} }
type ScheduleRotationBetaMapInput interface {
	pulumi.Input

	ToScheduleRotationBetaMapOutput() ScheduleRotationBetaMapOutput
	ToScheduleRotationBetaMapOutputWithContext(context.Context) ScheduleRotationBetaMapOutput
}

type ScheduleRotationBetaMap map[string]ScheduleRotationBetaInput

func (ScheduleRotationBetaMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ScheduleRotationBeta)(nil)).Elem()
}

func (i ScheduleRotationBetaMap) ToScheduleRotationBetaMapOutput() ScheduleRotationBetaMapOutput {
	return i.ToScheduleRotationBetaMapOutputWithContext(context.Background())
}

func (i ScheduleRotationBetaMap) ToScheduleRotationBetaMapOutputWithContext(ctx context.Context) ScheduleRotationBetaMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ScheduleRotationBetaMapOutput)
}

type ScheduleRotationBetaOutput struct{ *pulumi.OutputState }

func (ScheduleRotationBetaOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ScheduleRotationBeta)(nil)).Elem()
}

func (o ScheduleRotationBetaOutput) ToScheduleRotationBetaOutput() ScheduleRotationBetaOutput {
	return o
}

func (o ScheduleRotationBetaOutput) ToScheduleRotationBetaOutputWithContext(ctx context.Context) ScheduleRotationBetaOutput {
	return o
}

// How many shifts run at the same time, which is how many people are on call at once. Defaults to 1, one person on call at a time. Reducing this stops scheduling the last of them, and stops any overrides on those shifts from applying.
func (o ScheduleRotationBetaOutput) ConcurrentShifts() pulumi.IntOutput {
	return o.ApplyT(func(v *ScheduleRotationBeta) pulumi.IntOutput { return v.ConcurrentShifts }).(pulumi.IntOutput)
}

// When this shape of the rotation took over. Unset when the rotation has only ever had one.
func (o ScheduleRotationBetaOutput) EffectiveFrom() pulumi.StringOutput {
	return o.ApplyT(func(v *ScheduleRotationBeta) pulumi.StringOutput { return v.EffectiveFrom }).(pulumi.StringOutput)
}

// When the first handover interval starts being counted from, which fixes the time of day and day of week shifts change hands. The dashboard calls this the handover time.. Can't be changed in the same apply as `rollout` — see the resource description for why, and what to do instead.
func (o ScheduleRotationBetaOutput) FirstIntervalStartsAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ScheduleRotationBeta) pulumi.StringOutput { return v.FirstIntervalStartsAt }).(pulumi.StringOutput)
}

// The cadence shifts hand over on, applied in turn
func (o ScheduleRotationBetaOutput) Handovers() ScheduleRotationBetaHandoverArrayOutput {
	return o.ApplyT(func(v *ScheduleRotationBeta) ScheduleRotationBetaHandoverArrayOutput { return v.Handovers }).(ScheduleRotationBetaHandoverArrayOutput)
}

// Human readable name for the rotation, unique within the schedule
func (o ScheduleRotationBetaOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ScheduleRotationBeta) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Where this rotation sits in the schedule's running order, lowest first. Unset when it has never been ordered.
func (o ScheduleRotationBetaOutput) Rank() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ScheduleRotationBeta) pulumi.IntPtrOutput { return v.Rank }).(pulumi.IntPtrOutput)
}

// How a change to this rotation is introduced: `immediate` replaces the line-up now and can change who is on call this minute, `afterCurrentShift` lets the shift on call finish first, and `afterFullRotation` waits for everyone to have taken a turn. Leave it out to replace the line-up straight away. Creating a rotation ignores it, as there's no shift to protect yet.
func (o ScheduleRotationBetaOutput) Rollout() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ScheduleRotationBeta) pulumi.StringPtrOutput { return v.Rollout }).(pulumi.StringPtrOutput)
}

// ID of the schedule this rotation belongs to. Changing this replaces the rotation, as a rotation can't move between schedules.
func (o ScheduleRotationBetaOutput) ScheduleId() pulumi.StringOutput {
	return o.ApplyT(func(v *ScheduleRotationBeta) pulumi.StringOutput { return v.ScheduleId }).(pulumi.StringOutput)
}

// How users are allocated across shifts of differing length. Possible values are: `fair`, `sequential`. Omit it to leave us to pick. For an even rotation the two behave identically — see the resource description for when they diverge.
func (o ScheduleRotationBetaOutput) SchedulingMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ScheduleRotationBeta) pulumi.StringPtrOutput { return v.SchedulingMode }).(pulumi.StringPtrOutput)
}

// IDs of the people in the rotation, in the order they take shifts. Use the special ID `NOBODY` for a slot with nobody in it, which schedules the shift without putting anyone on call until an override covers it.
func (o ScheduleRotationBetaOutput) Users() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ScheduleRotationBeta) pulumi.StringArrayOutput { return v.Users }).(pulumi.StringArrayOutput)
}

// If set, restricts on-call to these weekday intervals. Omit it to keep the rotation on call around the clock. An empty list is not valid, and is rejected at plan time — it would leave a rotation nobody is ever on call for.
func (o ScheduleRotationBetaOutput) WorkingIntervals() ScheduleRotationBetaWorkingIntervalArrayOutput {
	return o.ApplyT(func(v *ScheduleRotationBeta) ScheduleRotationBetaWorkingIntervalArrayOutput {
		return v.WorkingIntervals
	}).(ScheduleRotationBetaWorkingIntervalArrayOutput)
}

type ScheduleRotationBetaArrayOutput struct{ *pulumi.OutputState }

func (ScheduleRotationBetaArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ScheduleRotationBeta)(nil)).Elem()
}

func (o ScheduleRotationBetaArrayOutput) ToScheduleRotationBetaArrayOutput() ScheduleRotationBetaArrayOutput {
	return o
}

func (o ScheduleRotationBetaArrayOutput) ToScheduleRotationBetaArrayOutputWithContext(ctx context.Context) ScheduleRotationBetaArrayOutput {
	return o
}

func (o ScheduleRotationBetaArrayOutput) Index(i pulumi.IntInput) ScheduleRotationBetaOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ScheduleRotationBeta {
		return vs[0].([]*ScheduleRotationBeta)[vs[1].(int)]
	}).(ScheduleRotationBetaOutput)
}

type ScheduleRotationBetaMapOutput struct{ *pulumi.OutputState }

func (ScheduleRotationBetaMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ScheduleRotationBeta)(nil)).Elem()
}

func (o ScheduleRotationBetaMapOutput) ToScheduleRotationBetaMapOutput() ScheduleRotationBetaMapOutput {
	return o
}

func (o ScheduleRotationBetaMapOutput) ToScheduleRotationBetaMapOutputWithContext(ctx context.Context) ScheduleRotationBetaMapOutput {
	return o
}

func (o ScheduleRotationBetaMapOutput) MapIndex(k pulumi.StringInput) ScheduleRotationBetaOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ScheduleRotationBeta {
		return vs[0].(map[string]*ScheduleRotationBeta)[vs[1].(string)]
	}).(ScheduleRotationBetaOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ScheduleRotationBetaInput)(nil)).Elem(), &ScheduleRotationBeta{})
	pulumi.RegisterInputType(reflect.TypeOf((*ScheduleRotationBetaArrayInput)(nil)).Elem(), ScheduleRotationBetaArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ScheduleRotationBetaMapInput)(nil)).Elem(), ScheduleRotationBetaMap{})
	pulumi.RegisterOutputType(ScheduleRotationBetaOutput{})
	pulumi.RegisterOutputType(ScheduleRotationBetaArrayOutput{})
	pulumi.RegisterOutputType(ScheduleRotationBetaMapOutput{})
}
