// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Outputs
{

    [OutputType]
    public sealed class AlertRouteGroupingConfigDefault
    {
        /// <summary>
        /// Whether grouping is enabled
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// Which attributes should this alert route use to group alerts? Only set when grouping is enabled.
        /// </summary>
        public readonly ImmutableArray<Outputs.AlertRouteGroupingConfigDefaultGroupingKey> GroupingKeys;
        /// <summary>
        /// How long the grouping window is, in seconds. Must be between 60 (1 minute) and 172800 (48 hours). Only set when grouping is enabled.
        /// </summary>
        public readonly int? WindowSeconds;
        /// <summary>
        /// Controls how the grouping window behaves. 'rolling' keeps the window open for window*seconds after the most recent alert, so the group stays open as long as alerts keep arriving. 'fixed' opens the window when the first alert arrives and always closes window*seconds later, regardless of any subsequent alerts. Only set when grouping is enabled. Possible values are: `Rolling`, `Fixed`.
        /// </summary>
        public readonly string? WindowType;

        [OutputConstructor]
        private AlertRouteGroupingConfigDefault(
            bool enabled,

            ImmutableArray<Outputs.AlertRouteGroupingConfigDefaultGroupingKey> groupingKeys,

            int? windowSeconds,

            string? windowType)
        {
            Enabled = enabled;
            GroupingKeys = groupingKeys;
            WindowSeconds = windowSeconds;
            WindowType = windowType;
        }
    }
}
