// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Outputs
{

    [OutputType]
    public sealed class AlertSourceAttributeBetaExpressionOperationBranches
    {
        /// <summary>
        /// Whether each branch returns several values rather than one.
        /// </summary>
        public readonly bool? Array;
        /// <summary>
        /// The type every branch result returns. Required when the block is present.
        /// </summary>
        public readonly string? As;
        /// <summary>
        /// Tried in order, after if.
        /// </summary>
        public readonly ImmutableArray<Outputs.AlertSourceAttributeBetaExpressionOperationBranchesElseIf> ElseIfs;
        /// <summary>
        /// The first branch to try.
        /// </summary>
        public readonly Outputs.AlertSourceAttributeBetaExpressionOperationBranchesIf? If;

        [OutputConstructor]
        private AlertSourceAttributeBetaExpressionOperationBranches(
            bool? array,

            string? @as,

            ImmutableArray<Outputs.AlertSourceAttributeBetaExpressionOperationBranchesElseIf> elseIfs,

            Outputs.AlertSourceAttributeBetaExpressionOperationBranchesIf? @if)
        {
            Array = array;
            As = @as;
            ElseIfs = elseIfs;
            If = @if;
        }
    }
}
