// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Outputs
{

    [OutputType]
    public sealed class AlertRouteIncidentTemplateCustomFieldBinding
    {
        /// <summary>
        /// The array of literal or reference parameter values
        /// </summary>
        public readonly ImmutableArray<Outputs.AlertRouteIncidentTemplateCustomFieldBindingArrayValue> ArrayValues;
        /// <summary>
        /// The name of an expression on this resource, whose result becomes the value. Shorthand for referencing `expressions["name"]`.
        /// </summary>
        public readonly string? ExpressionRef;
        /// <summary>
        /// The literal or reference parameter value
        /// </summary>
        public readonly Outputs.AlertRouteIncidentTemplateCustomFieldBindingValue? Value;
        /// <summary>
        /// A fixed value, shorthand for `value = { literal = ... }`. A catalog entry ID is a literal, not a reference.
        /// </summary>
        public readonly string? ValueLiteral;
        /// <summary>
        /// A reference into the scope, shorthand for `value = { reference = ... }`.
        /// </summary>
        public readonly string? ValueReference;
        /// <summary>
        /// Several fixed values, shorthand for an `ArrayValue` of literals. For a mix of literals and references, use `ArrayValue`.
        /// </summary>
        public readonly ImmutableArray<string> Values;

        [OutputConstructor]
        private AlertRouteIncidentTemplateCustomFieldBinding(
            ImmutableArray<Outputs.AlertRouteIncidentTemplateCustomFieldBindingArrayValue> arrayValues,

            string? expressionRef,

            Outputs.AlertRouteIncidentTemplateCustomFieldBindingValue? value,

            string? valueLiteral,

            string? valueReference,

            ImmutableArray<string> values)
        {
            ArrayValues = arrayValues;
            ExpressionRef = expressionRef;
            Value = value;
            ValueLiteral = valueLiteral;
            ValueReference = valueReference;
            Values = values;
        }
    }
}
