// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Outputs
{

    [OutputType]
    public sealed class AlertRouteChannelConfigMsTeamsTargets
    {
        public readonly Outputs.AlertRouteChannelConfigMsTeamsTargetsBinding Binding;
        /// <summary>
        /// The visibility of the channel
        /// </summary>
        public readonly string ChannelVisibility;

        [OutputConstructor]
        private AlertRouteChannelConfigMsTeamsTargets(
            Outputs.AlertRouteChannelConfigMsTeamsTargetsBinding binding,

            string channelVisibility)
        {
            Binding = binding;
            ChannelVisibility = channelVisibility;
        }
    }
}
