// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Outputs
{

    [OutputType]
    public sealed class AlertRouteIncidentConfigTemplateCustomField
    {
        /// <summary>
        /// Binding for the custom field
        /// </summary>
        public readonly Outputs.AlertRouteIncidentConfigTemplateCustomFieldBinding Binding;
        /// <summary>
        /// ID of the custom field
        /// </summary>
        public readonly string CustomFieldId;
        /// <summary>
        /// The strategy to use when multiple alerts match this route. Possible values are: `first-wins`, `last-wins`, `Append`.
        /// </summary>
        public readonly string MergeStrategy;

        [OutputConstructor]
        private AlertRouteIncidentConfigTemplateCustomField(
            Outputs.AlertRouteIncidentConfigTemplateCustomFieldBinding binding,

            string customFieldId,

            string mergeStrategy)
        {
            Binding = binding;
            CustomFieldId = customFieldId;
            MergeStrategy = mergeStrategy;
        }
    }
}
