// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Outputs
{

    [OutputType]
    public sealed class AlertRouteChannelConfigConditionGroup
    {
        /// <summary>
        /// The prerequisite conditions that must all be satisfied
        /// </summary>
        public readonly ImmutableArray<Outputs.AlertRouteChannelConfigConditionGroupCondition> Conditions;

        [OutputConstructor]
        private AlertRouteChannelConfigConditionGroup(ImmutableArray<Outputs.AlertRouteChannelConfigConditionGroupCondition> conditions)
        {
            Conditions = conditions;
        }
    }
}
