// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Outputs
{

    [OutputType]
    public sealed class AlertRouteIncidentConfigTemplateName
    {
        /// <summary>
        /// The array of literal or reference parameter values
        /// </summary>
        public readonly ImmutableArray<Outputs.AlertRouteIncidentConfigTemplateNameArrayValue> ArrayValues;
        /// <summary>
        /// Whether this attribute should be autogenerated using AI
        /// </summary>
        public readonly bool? Autogenerated;
        /// <summary>
        /// The literal or reference parameter value
        /// </summary>
        public readonly Outputs.AlertRouteIncidentConfigTemplateNameValue? Value;

        [OutputConstructor]
        private AlertRouteIncidentConfigTemplateName(
            ImmutableArray<Outputs.AlertRouteIncidentConfigTemplateNameArrayValue> arrayValues,

            bool? autogenerated,

            Outputs.AlertRouteIncidentConfigTemplateNameValue? value)
        {
            ArrayValues = arrayValues;
            Autogenerated = autogenerated;
            Value = value;
        }
    }
}
