// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Outputs
{

    [OutputType]
    public sealed class AlertRouteEscalationConfigWhenAlertJoinsGroup
    {
        /// <summary>
        /// How long to wait before escalating once an alert joins the group, in seconds. Only applies when mode is 'on*each*new_alert'.
        /// </summary>
        public readonly int? GracePeriodSeconds;
        /// <summary>
        /// When a subsequent alert joins an existing group, when should we escalate again? Possible values are: `OnPriorityIncrease`, `OnEachNewAlert`.
        /// </summary>
        public readonly string Mode;

        [OutputConstructor]
        private AlertRouteEscalationConfigWhenAlertJoinsGroup(
            int? gracePeriodSeconds,

            string mode)
        {
            GracePeriodSeconds = gracePeriodSeconds;
            Mode = mode;
        }
    }
}
