// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Outputs
{

    [OutputType]
    public sealed class EscalationPathPathIfElseElsePathIfElseThenPathIfElseElsePathIfElseThenPathIfElseThenPathNotifyChannelTarget
    {
        /// <summary>
        /// Uniquely identifies an entity of this type
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Only set for schedule targets, this specifies which users to fetch from the schedule. Use CurrentlyOnCall to notify whoever is on call right now across the schedule, AllUsers to notify every user attached to the schedule, or AllUsersForRota / CurrentlyOnCallForRota / NextOnCallForRota to scope to a specific rota (in which case SelectedRotaId is required). NextOnCall notifies whoever is next on call across the schedule. Possible values are: `CurrentlyOnCall`, `AllUsersForRota`, `AllUsers`, `CurrentlyOnCallForRota`, `NextOnCallForRota`, `NextOnCall`.
        /// </summary>
        public readonly string? ScheduleMode;
        /// <summary>
        /// For schedule targets, identifies which rota on the schedule the ScheduleMode applies to. Required when ScheduleMode is all_users_for_rota, currently_on_call_for_rota, or next_on_call_for_rota; must be omitted for other ScheduleMode values.
        /// </summary>
        public readonly string? SelectedRotaId;
        /// <summary>
        /// Controls what type of entity this target identifies, such as EscalationPolicy or User. Possible values are: `Schedule`, `User`, `SlackChannel`, `MsteamsChannel`.
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// The urgency of this escalation path target. Possible values are: `High`, `Low`.
        /// </summary>
        public readonly string Urgency;

        [OutputConstructor]
        private EscalationPathPathIfElseElsePathIfElseThenPathIfElseElsePathIfElseThenPathIfElseThenPathNotifyChannelTarget(
            string id,

            string? scheduleMode,

            string? selectedRotaId,

            string type,

            string urgency)
        {
            Id = id;
            ScheduleMode = scheduleMode;
            SelectedRotaId = selectedRotaId;
            Type = type;
            Urgency = urgency;
        }
    }
}
