// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Outputs
{

    [OutputType]
    public sealed class EscalationPathBetaSequencesNodeBranch
    {
        /// <summary>
        /// The key of the sequence to continue down when the condition is not met. Leave unset to end the escalation path instead.
        /// </summary>
        public readonly string? Else;
        /// <summary>
        /// What the branch tests. Set exactly one of these: a branch tests one thing, so combining them means nesting a second branch inside the first.
        /// </summary>
        public readonly Outputs.EscalationPathBetaSequencesNodeBranchIf If;
        /// <summary>
        /// The key of the sequence to continue down when the condition is met.
        /// </summary>
        public readonly string Then;

        [OutputConstructor]
        private EscalationPathBetaSequencesNodeBranch(
            string? @else,

            Outputs.EscalationPathBetaSequencesNodeBranchIf @if,

            string then)
        {
            Else = @else;
            If = @if;
            Then = then;
        }
    }
}
