// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Outputs
{

    [OutputType]
    public sealed class GetEscalationPathPathIfElseElsePathIfElseThenPathIfElseElsePathIfElseElsePathDelayResult
    {
        /// <summary>
        /// If the delay is relative to a time window, this defines whether we advance when the window is active or inactive. Possible values are: `Active`, `Inactive`.
        /// </summary>
        public readonly string DelayIntervalCondition;
        /// <summary>
        /// How long to delay before advancing to the next node in the path, in seconds
        /// </summary>
        public readonly int DelaySeconds;
        /// <summary>
        /// If the delay is relative to a time window, this identifies which window it is relative to
        /// </summary>
        public readonly string DelayWeekdayIntervalConfigId;

        [OutputConstructor]
        private GetEscalationPathPathIfElseElsePathIfElseThenPathIfElseElsePathIfElseElsePathDelayResult(
            string delayIntervalCondition,

            int delaySeconds,

            string delayWeekdayIntervalConfigId)
        {
            DelayIntervalCondition = delayIntervalCondition;
            DelaySeconds = delaySeconds;
            DelayWeekdayIntervalConfigId = delayWeekdayIntervalConfigId;
        }
    }
}
