// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Outputs
{

    [OutputType]
    public sealed class GetEscalationPathPathIfElseElsePathIfElseElsePathIfElseElsePathIfElseElsePathIfElseResult
    {
        /// <summary>
        /// The prerequisite conditions that must all be satisfied
        /// </summary>
        public readonly ImmutableArray<Outputs.GetEscalationPathPathIfElseElsePathIfElseElsePathIfElseElsePathIfElseElsePathIfElseConditionResult> Conditions;
        /// <summary>
        /// The nodes that form the levels if our condition is not met
        /// </summary>
        public readonly ImmutableArray<Outputs.GetEscalationPathPathIfElseElsePathIfElseElsePathIfElseElsePathIfElseElsePathIfElseElsePathResult> ElsePaths;
        /// <summary>
        /// Then path nodes
        /// </summary>
        public readonly ImmutableArray<Outputs.GetEscalationPathPathIfElseElsePathIfElseElsePathIfElseElsePathIfElseElsePathIfElseThenPathResult> ThenPaths;

        [OutputConstructor]
        private GetEscalationPathPathIfElseElsePathIfElseElsePathIfElseElsePathIfElseElsePathIfElseResult(
            ImmutableArray<Outputs.GetEscalationPathPathIfElseElsePathIfElseElsePathIfElseElsePathIfElseElsePathIfElseConditionResult> conditions,

            ImmutableArray<Outputs.GetEscalationPathPathIfElseElsePathIfElseElsePathIfElseElsePathIfElseElsePathIfElseElsePathResult> elsePaths,

            ImmutableArray<Outputs.GetEscalationPathPathIfElseElsePathIfElseElsePathIfElseElsePathIfElseElsePathIfElseThenPathResult> thenPaths)
        {
            Conditions = conditions;
            ElsePaths = elsePaths;
            ThenPaths = thenPaths;
        }
    }
}
