// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Outputs
{

    [OutputType]
    public sealed class WorkflowExpressionOperationFilter
    {
        /// <summary>
        /// Groups of prerequisite conditions. All conditions in at least one group must be satisfied
        /// </summary>
        public readonly ImmutableArray<Outputs.WorkflowExpressionOperationFilterConditionGroup> ConditionGroups;

        [OutputConstructor]
        private WorkflowExpressionOperationFilter(ImmutableArray<Outputs.WorkflowExpressionOperationFilterConditionGroup> conditionGroups)
        {
            ConditionGroups = conditionGroups;
        }
    }
}
