// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Inputs
{

    public sealed class AlertRouteExpressionOperationCastArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The return type of an operation
        /// </summary>
        [Input("returns", required: true)]
        public Input<Inputs.AlertRouteExpressionOperationCastReturnsArgs> Returns { get; set; } = null!;

        public AlertRouteExpressionOperationCastArgs()
        {
        }
        public static new AlertRouteExpressionOperationCastArgs Empty => new AlertRouteExpressionOperationCastArgs();
    }
}
