// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Inputs
{

    public sealed class AlertSourceAttributeBetaNamedExpressionOperationFilterArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditionGroups")]
        private InputList<Inputs.AlertSourceAttributeBetaNamedExpressionOperationFilterConditionGroupArgs>? _conditionGroups;

        /// <summary>
        /// Groups are OR'd; conditions within a group are AND'd.
        /// </summary>
        public InputList<Inputs.AlertSourceAttributeBetaNamedExpressionOperationFilterConditionGroupArgs> ConditionGroups
        {
            get => _conditionGroups ?? (_conditionGroups = new InputList<Inputs.AlertSourceAttributeBetaNamedExpressionOperationFilterConditionGroupArgs>());
            set => _conditionGroups = value;
        }

        [Input("conditions")]
        private InputList<Inputs.AlertSourceAttributeBetaNamedExpressionOperationFilterConditionArgs>? _conditions;

        /// <summary>
        /// All of these must hold. Sugar for a single condition group.
        /// </summary>
        public InputList<Inputs.AlertSourceAttributeBetaNamedExpressionOperationFilterConditionArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Inputs.AlertSourceAttributeBetaNamedExpressionOperationFilterConditionArgs>());
            set => _conditions = value;
        }

        public AlertSourceAttributeBetaNamedExpressionOperationFilterArgs()
        {
        }
        public static new AlertSourceAttributeBetaNamedExpressionOperationFilterArgs Empty => new AlertSourceAttributeBetaNamedExpressionOperationFilterArgs();
    }
}
