// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Inputs
{

    public sealed class AlertSourceBetaNamedExpressionFallbackIfConditionGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// How the subject is tested. The available operations depend on the subject's type.
        /// </summary>
        [Input("operation", required: true)]
        public Input<string> Operation { get; set; } = null!;

        [Input("params")]
        private InputList<Inputs.AlertSourceBetaNamedExpressionFallbackIfConditionParamGetArgs>? _params;

        /// <summary>
        /// Positional parameters for the operation.
        /// </summary>
        public InputList<Inputs.AlertSourceBetaNamedExpressionFallbackIfConditionParamGetArgs> Params
        {
            get => _params ?? (_params = new InputList<Inputs.AlertSourceBetaNamedExpressionFallbackIfConditionParamGetArgs>());
            set => _params = value;
        }

        /// <summary>
        /// The reference this condition tests.
        /// </summary>
        [Input("subject", required: true)]
        public Input<string> Subject { get; set; } = null!;

        public AlertSourceBetaNamedExpressionFallbackIfConditionGetArgs()
        {
        }
        public static new AlertSourceBetaNamedExpressionFallbackIfConditionGetArgs Empty => new AlertSourceBetaNamedExpressionFallbackIfConditionGetArgs();
    }
}
