// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Inputs
{

    public sealed class AlertRouteEscalationConfigGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Should we auto cancel escalations when all alerts are resolved?
        /// </summary>
        [Input("autoCancelEscalations", required: true)]
        public Input<bool> AutoCancelEscalations { get; set; } = null!;

        [Input("escalationTargets", required: true)]
        private InputList<Inputs.AlertRouteEscalationConfigEscalationTargetGetArgs>? _escalationTargets;

        /// <summary>
        /// Targets for escalation
        /// </summary>
        public InputList<Inputs.AlertRouteEscalationConfigEscalationTargetGetArgs> EscalationTargets
        {
            get => _escalationTargets ?? (_escalationTargets = new InputList<Inputs.AlertRouteEscalationConfigEscalationTargetGetArgs>());
            set => _escalationTargets = value;
        }

        [Input("whenAlertJoinsGroup")]
        public Input<Inputs.AlertRouteEscalationConfigWhenAlertJoinsGroupGetArgs>? WhenAlertJoinsGroup { get; set; }

        public AlertRouteEscalationConfigGetArgs()
        {
        }
        public static new AlertRouteEscalationConfigGetArgs Empty => new AlertRouteEscalationConfigGetArgs();
    }
}
