// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Inputs
{

    public sealed class AlertSourceBetaNamedExpressionOperationMaxArgs : global::Pulumi.ResourceArgs
    {
        public AlertSourceBetaNamedExpressionOperationMaxArgs()
        {
        }
        public static new AlertSourceBetaNamedExpressionOperationMaxArgs Empty => new AlertSourceBetaNamedExpressionOperationMaxArgs();
    }
}
