// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Inputs
{

    public sealed class AlertRouteChannelConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditionGroups", required: true)]
        private InputList<Inputs.AlertRouteChannelConfigConditionGroupArgs>? _conditionGroups;

        /// <summary>
        /// Groups of prerequisite conditions. All conditions in at least one group must be satisfied
        /// </summary>
        public InputList<Inputs.AlertRouteChannelConfigConditionGroupArgs> ConditionGroups
        {
            get => _conditionGroups ?? (_conditionGroups = new InputList<Inputs.AlertRouteChannelConfigConditionGroupArgs>());
            set => _conditionGroups = value;
        }

        [Input("msTeamsTargets")]
        public Input<Inputs.AlertRouteChannelConfigMsTeamsTargetsArgs>? MsTeamsTargets { get; set; }

        [Input("slackTargets")]
        public Input<Inputs.AlertRouteChannelConfigSlackTargetsArgs>? SlackTargets { get; set; }

        public AlertRouteChannelConfigArgs()
        {
        }
        public static new AlertRouteChannelConfigArgs Empty => new AlertRouteChannelConfigArgs();
    }
}
