// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Inputs
{

    public sealed class AlertSourceBetaNamedExpressionFallbackIfConditionGroupArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditions", required: true)]
        private InputList<Inputs.AlertSourceBetaNamedExpressionFallbackIfConditionGroupConditionArgs>? _conditions;

        /// <summary>
        /// All of these must hold for the group to hold.
        /// </summary>
        public InputList<Inputs.AlertSourceBetaNamedExpressionFallbackIfConditionGroupConditionArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Inputs.AlertSourceBetaNamedExpressionFallbackIfConditionGroupConditionArgs>());
            set => _conditions = value;
        }

        public AlertSourceBetaNamedExpressionFallbackIfConditionGroupArgs()
        {
        }
        public static new AlertSourceBetaNamedExpressionFallbackIfConditionGroupArgs Empty => new AlertSourceBetaNamedExpressionFallbackIfConditionGroupArgs();
    }
}
