// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Inputs
{

    public sealed class EscalationPathPathIfElseThenPathIfElseElsePathIfElseElsePathIfElseElsePathIfElseThenPathEscalationPathArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the escalation path to reassign to
        /// </summary>
        [Input("escalationPathId", required: true)]
        public Input<string> EscalationPathId { get; set; } = null!;

        public EscalationPathPathIfElseThenPathIfElseElsePathIfElseElsePathIfElseElsePathIfElseThenPathEscalationPathArgs()
        {
        }
        public static new EscalationPathPathIfElseThenPathIfElseElsePathIfElseElsePathIfElseElsePathIfElseThenPathEscalationPathArgs Empty => new EscalationPathPathIfElseThenPathIfElseElsePathIfElseElsePathIfElseElsePathIfElseThenPathEscalationPathArgs();
    }
}
