// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Inputs
{

    public sealed class EscalationPathPathIfElseThenPathIfElseThenPathIfElseThenPathIfElseElsePathLevelRoundRobinConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether round robin is enabled for this level
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        /// <summary>
        /// How long should we wait before rotating to the next target in a round robin, if not set will stick with a single target per level.
        /// </summary>
        [Input("rotateAfterSeconds")]
        public Input<int>? RotateAfterSeconds { get; set; }

        public EscalationPathPathIfElseThenPathIfElseThenPathIfElseThenPathIfElseElsePathLevelRoundRobinConfigArgs()
        {
        }
        public static new EscalationPathPathIfElseThenPathIfElseThenPathIfElseThenPathIfElseElsePathLevelRoundRobinConfigArgs Empty => new EscalationPathPathIfElseThenPathIfElseThenPathIfElseThenPathIfElseElsePathLevelRoundRobinConfigArgs();
    }
}
