// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Inputs
{

    public sealed class EscalationPathBetaSequencesGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("nodes", required: true)]
        private InputList<Inputs.EscalationPathBetaSequencesNodeGetArgs>? _nodes;

        /// <summary>
        /// The nodes in this sequence, in the order they run.
        /// </summary>
        public InputList<Inputs.EscalationPathBetaSequencesNodeGetArgs> Nodes
        {
            get => _nodes ?? (_nodes = new InputList<Inputs.EscalationPathBetaSequencesNodeGetArgs>());
            set => _nodes = value;
        }

        public EscalationPathBetaSequencesGetArgs()
        {
        }
        public static new EscalationPathBetaSequencesGetArgs Empty => new EscalationPathBetaSequencesGetArgs();
    }
}
