// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Inputs
{

    public sealed class EscalationPathPathIfElseElsePathIfElseThenPathIfElseElsePathIfElseThenPathIfElseArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditions", required: true)]
        private InputList<Inputs.EscalationPathPathIfElseElsePathIfElseThenPathIfElseElsePathIfElseThenPathIfElseConditionArgs>? _conditions;

        /// <summary>
        /// The prerequisite conditions that must all be satisfied
        /// </summary>
        public InputList<Inputs.EscalationPathPathIfElseElsePathIfElseThenPathIfElseElsePathIfElseThenPathIfElseConditionArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Inputs.EscalationPathPathIfElseElsePathIfElseThenPathIfElseElsePathIfElseThenPathIfElseConditionArgs>());
            set => _conditions = value;
        }

        [Input("elsePaths")]
        private InputList<Inputs.EscalationPathPathIfElseElsePathIfElseThenPathIfElseElsePathIfElseThenPathIfElseElsePathArgs>? _elsePaths;

        /// <summary>
        /// The nodes that form the levels if our condition is not met
        /// </summary>
        public InputList<Inputs.EscalationPathPathIfElseElsePathIfElseThenPathIfElseElsePathIfElseThenPathIfElseElsePathArgs> ElsePaths
        {
            get => _elsePaths ?? (_elsePaths = new InputList<Inputs.EscalationPathPathIfElseElsePathIfElseThenPathIfElseElsePathIfElseThenPathIfElseElsePathArgs>());
            set => _elsePaths = value;
        }

        [Input("thenPaths", required: true)]
        private InputList<Inputs.EscalationPathPathIfElseElsePathIfElseThenPathIfElseElsePathIfElseThenPathIfElseThenPathArgs>? _thenPaths;

        /// <summary>
        /// Then path nodes
        /// </summary>
        public InputList<Inputs.EscalationPathPathIfElseElsePathIfElseThenPathIfElseElsePathIfElseThenPathIfElseThenPathArgs> ThenPaths
        {
            get => _thenPaths ?? (_thenPaths = new InputList<Inputs.EscalationPathPathIfElseElsePathIfElseThenPathIfElseElsePathIfElseThenPathIfElseThenPathArgs>());
            set => _thenPaths = value;
        }

        public EscalationPathPathIfElseElsePathIfElseThenPathIfElseElsePathIfElseThenPathIfElseArgs()
        {
        }
        public static new EscalationPathPathIfElseElsePathIfElseThenPathIfElseElsePathIfElseThenPathIfElseArgs Empty => new EscalationPathPathIfElseElsePathIfElseThenPathIfElseElsePathIfElseThenPathIfElseArgs();
    }
}
