// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Inputs
{

    public sealed class EscalationPathPathIfElseThenPathIfElseThenPathIfElseElsePathIfElseElsePathDelayGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// If the delay is relative to a time window, this defines whether we advance when the window is active or inactive. Possible values are: `Active`, `Inactive`.
        /// </summary>
        [Input("delayIntervalCondition")]
        public Input<string>? DelayIntervalCondition { get; set; }

        /// <summary>
        /// How long to delay before advancing to the next node in the path, in seconds
        /// </summary>
        [Input("delaySeconds")]
        public Input<int>? DelaySeconds { get; set; }

        /// <summary>
        /// If the delay is relative to a time window, this identifies which window it is relative to
        /// </summary>
        [Input("delayWeekdayIntervalConfigId")]
        public Input<string>? DelayWeekdayIntervalConfigId { get; set; }

        public EscalationPathPathIfElseThenPathIfElseThenPathIfElseElsePathIfElseElsePathDelayGetArgs()
        {
        }
        public static new EscalationPathPathIfElseThenPathIfElseThenPathIfElseElsePathIfElseElsePathDelayGetArgs Empty => new EscalationPathPathIfElseThenPathIfElseThenPathIfElseElsePathIfElseElsePathDelayGetArgs();
    }
}
