// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Inputs
{

    public sealed class EscalationPathPathIfElseElsePathIfElseThenPathIfElseThenPathIfElseThenPathIfElseGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditions", required: true)]
        private InputList<Inputs.EscalationPathPathIfElseElsePathIfElseThenPathIfElseThenPathIfElseThenPathIfElseConditionGetArgs>? _conditions;

        /// <summary>
        /// The prerequisite conditions that must all be satisfied
        /// </summary>
        public InputList<Inputs.EscalationPathPathIfElseElsePathIfElseThenPathIfElseThenPathIfElseThenPathIfElseConditionGetArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Inputs.EscalationPathPathIfElseElsePathIfElseThenPathIfElseThenPathIfElseThenPathIfElseConditionGetArgs>());
            set => _conditions = value;
        }

        [Input("elsePaths")]
        private InputList<Inputs.EscalationPathPathIfElseElsePathIfElseThenPathIfElseThenPathIfElseThenPathIfElseElsePathGetArgs>? _elsePaths;

        /// <summary>
        /// The nodes that form the levels if our condition is not met
        /// </summary>
        public InputList<Inputs.EscalationPathPathIfElseElsePathIfElseThenPathIfElseThenPathIfElseThenPathIfElseElsePathGetArgs> ElsePaths
        {
            get => _elsePaths ?? (_elsePaths = new InputList<Inputs.EscalationPathPathIfElseElsePathIfElseThenPathIfElseThenPathIfElseThenPathIfElseElsePathGetArgs>());
            set => _elsePaths = value;
        }

        [Input("thenPaths", required: true)]
        private InputList<Inputs.EscalationPathPathIfElseElsePathIfElseThenPathIfElseThenPathIfElseThenPathIfElseThenPathGetArgs>? _thenPaths;

        /// <summary>
        /// Then path nodes
        /// </summary>
        public InputList<Inputs.EscalationPathPathIfElseElsePathIfElseThenPathIfElseThenPathIfElseThenPathIfElseThenPathGetArgs> ThenPaths
        {
            get => _thenPaths ?? (_thenPaths = new InputList<Inputs.EscalationPathPathIfElseElsePathIfElseThenPathIfElseThenPathIfElseThenPathIfElseThenPathGetArgs>());
            set => _thenPaths = value;
        }

        public EscalationPathPathIfElseElsePathIfElseThenPathIfElseThenPathIfElseThenPathIfElseGetArgs()
        {
        }
        public static new EscalationPathPathIfElseElsePathIfElseThenPathIfElseThenPathIfElseThenPathIfElseGetArgs Empty => new EscalationPathPathIfElseElsePathIfElseThenPathIfElseThenPathIfElseThenPathIfElseGetArgs();
    }
}
