// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Inputs
{

    public sealed class EscalationPathPathIfElseElsePathIfElseElsePathIfElseThenPathIfElseArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditions", required: true)]
        private InputList<Inputs.EscalationPathPathIfElseElsePathIfElseElsePathIfElseThenPathIfElseConditionArgs>? _conditions;

        /// <summary>
        /// The prerequisite conditions that must all be satisfied
        /// </summary>
        public InputList<Inputs.EscalationPathPathIfElseElsePathIfElseElsePathIfElseThenPathIfElseConditionArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Inputs.EscalationPathPathIfElseElsePathIfElseElsePathIfElseThenPathIfElseConditionArgs>());
            set => _conditions = value;
        }

        [Input("elsePaths")]
        private InputList<Inputs.EscalationPathPathIfElseElsePathIfElseElsePathIfElseThenPathIfElseElsePathArgs>? _elsePaths;

        /// <summary>
        /// The nodes that form the levels if our condition is not met
        /// </summary>
        public InputList<Inputs.EscalationPathPathIfElseElsePathIfElseElsePathIfElseThenPathIfElseElsePathArgs> ElsePaths
        {
            get => _elsePaths ?? (_elsePaths = new InputList<Inputs.EscalationPathPathIfElseElsePathIfElseElsePathIfElseThenPathIfElseElsePathArgs>());
            set => _elsePaths = value;
        }

        [Input("thenPaths", required: true)]
        private InputList<Inputs.EscalationPathPathIfElseElsePathIfElseElsePathIfElseThenPathIfElseThenPathArgs>? _thenPaths;

        /// <summary>
        /// Then path nodes
        /// </summary>
        public InputList<Inputs.EscalationPathPathIfElseElsePathIfElseElsePathIfElseThenPathIfElseThenPathArgs> ThenPaths
        {
            get => _thenPaths ?? (_thenPaths = new InputList<Inputs.EscalationPathPathIfElseElsePathIfElseElsePathIfElseThenPathIfElseThenPathArgs>());
            set => _thenPaths = value;
        }

        public EscalationPathPathIfElseElsePathIfElseElsePathIfElseThenPathIfElseArgs()
        {
        }
        public static new EscalationPathPathIfElseElsePathIfElseElsePathIfElseThenPathIfElseArgs Empty => new EscalationPathPathIfElseElsePathIfElseElsePathIfElseThenPathIfElseArgs();
    }
}
