// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Inputs
{

    public sealed class EscalationPathPathIfElseElsePathIfElseElsePathIfElseElsePathIfElseThenPathIfElseElsePathRepeatGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// How many times to repeat these nodes
        /// </summary>
        [Input("repeatTimes", required: true)]
        public Input<int> RepeatTimes { get; set; } = null!;

        /// <summary>
        /// Which node ID we begin repeating from.
        /// </summary>
        [Input("toNode", required: true)]
        public Input<string> ToNode { get; set; } = null!;

        public EscalationPathPathIfElseElsePathIfElseElsePathIfElseElsePathIfElseThenPathIfElseElsePathRepeatGetArgs()
        {
        }
        public static new EscalationPathPathIfElseElsePathIfElseElsePathIfElseElsePathIfElseThenPathIfElseElsePathRepeatGetArgs Empty => new EscalationPathPathIfElseElsePathIfElseElsePathIfElseElsePathIfElseThenPathIfElseElsePathRepeatGetArgs();
    }
}
