// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Inputs
{

    public sealed class EscalationPathPathIfElseThenPathIfElseThenPathIfElseArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditions", required: true)]
        private InputList<Inputs.EscalationPathPathIfElseThenPathIfElseThenPathIfElseConditionArgs>? _conditions;

        /// <summary>
        /// The prerequisite conditions that must all be satisfied
        /// </summary>
        public InputList<Inputs.EscalationPathPathIfElseThenPathIfElseThenPathIfElseConditionArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Inputs.EscalationPathPathIfElseThenPathIfElseThenPathIfElseConditionArgs>());
            set => _conditions = value;
        }

        [Input("elsePaths")]
        private InputList<Inputs.EscalationPathPathIfElseThenPathIfElseThenPathIfElseElsePathArgs>? _elsePaths;

        /// <summary>
        /// The nodes that form the levels if our condition is not met
        /// </summary>
        public InputList<Inputs.EscalationPathPathIfElseThenPathIfElseThenPathIfElseElsePathArgs> ElsePaths
        {
            get => _elsePaths ?? (_elsePaths = new InputList<Inputs.EscalationPathPathIfElseThenPathIfElseThenPathIfElseElsePathArgs>());
            set => _elsePaths = value;
        }

        [Input("thenPaths", required: true)]
        private InputList<Inputs.EscalationPathPathIfElseThenPathIfElseThenPathIfElseThenPathArgs>? _thenPaths;

        /// <summary>
        /// Then path nodes
        /// </summary>
        public InputList<Inputs.EscalationPathPathIfElseThenPathIfElseThenPathIfElseThenPathArgs> ThenPaths
        {
            get => _thenPaths ?? (_thenPaths = new InputList<Inputs.EscalationPathPathIfElseThenPathIfElseThenPathIfElseThenPathArgs>());
            set => _thenPaths = value;
        }

        public EscalationPathPathIfElseThenPathIfElseThenPathIfElseArgs()
        {
        }
        public static new EscalationPathPathIfElseThenPathIfElseThenPathIfElseArgs Empty => new EscalationPathPathIfElseThenPathIfElseThenPathIfElseArgs();
    }
}
