// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Inputs
{

    public sealed class EscalationPathPathIfElseThenPathIfElseConditionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The logical operation to be applied
        /// </summary>
        [Input("operation", required: true)]
        public Input<string> Operation { get; set; } = null!;

        [Input("paramBindings", required: true)]
        private InputList<Inputs.EscalationPathPathIfElseThenPathIfElseConditionParamBindingArgs>? _paramBindings;

        /// <summary>
        /// Bindings for the operation parameters
        /// </summary>
        public InputList<Inputs.EscalationPathPathIfElseThenPathIfElseConditionParamBindingArgs> ParamBindings
        {
            get => _paramBindings ?? (_paramBindings = new InputList<Inputs.EscalationPathPathIfElseThenPathIfElseConditionParamBindingArgs>());
            set => _paramBindings = value;
        }

        /// <summary>
        /// The subject of the condition, on which the operation is applied
        /// </summary>
        [Input("subject", required: true)]
        public Input<string> Subject { get; set; } = null!;

        public EscalationPathPathIfElseThenPathIfElseConditionArgs()
        {
        }
        public static new EscalationPathPathIfElseThenPathIfElseConditionArgs Empty => new EscalationPathPathIfElseThenPathIfElseConditionArgs();
    }
}
