// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace IncidentIO.Incident.Inputs
{

    public sealed class WorkflowExpressionOperationFilterConditionGroupArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditions", required: true)]
        private InputList<Inputs.WorkflowExpressionOperationFilterConditionGroupConditionArgs>? _conditions;

        /// <summary>
        /// The prerequisite conditions that must all be satisfied
        /// </summary>
        public InputList<Inputs.WorkflowExpressionOperationFilterConditionGroupConditionArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Inputs.WorkflowExpressionOperationFilterConditionGroupConditionArgs>());
            set => _conditions = value;
        }

        public WorkflowExpressionOperationFilterConditionGroupArgs()
        {
        }
        public static new WorkflowExpressionOperationFilterConditionGroupArgs Empty => new WorkflowExpressionOperationFilterConditionGroupArgs();
    }
}
