// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Create and manage announcement templates.
 *
 * An announcement template controls which fields and actions appear on an announcement post.
 * Each announcement rule renders its posts with one template.
 *
 * `fields` and `actions` appear on the post in the order they're listed.
 *
 * Which template is the organisation's default is set in the dashboard, and the default template can't be deleted: import it to manage its fields, but remove it from state rather than destroying it.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as incident from "@incident-io/pulumi";
 *
 * // A template for major incidents: severity and status first, then a note asking people
 * // to join. Fields and actions appear on the post in the order they're listed.
 * const majorIncidents = new incident.AnnouncementTemplate("major_incidents", {
 *     name: "Major incidents",
 *     fields: [
 *         {
 *             fieldType: "announcement_post_fields_severity",
 *             emoji: "fire",
 *         },
 *         {
 *             fieldType: "announcement_post_fields_status",
 *         },
 *         {
 *             fieldType: "announcement_post_fields_rich_text",
 *             richText: {
 *                 type: "markdown",
 *                 contents: "If you can help, please join {{incident.reference}}",
 *             },
 *         },
 *     ],
 *     actions: [
 *         {
 *             actionType: "announcement_post_actions_join_call",
 *         },
 *         {
 *             actionType: "announcement_post_actions_homepage",
 *         },
 *     ],
 * });
 * ```
 *
 * ## Import
 *
 * Import is supported using an `import` block or the `pulumi import` command:
 *
 * The `pulumi import` command can be used, for example:
 *
 * !/bin/bash
 *
 * Import an announcement template using its ID
 * Replace the ID with a real ID from your incident.io organization
 *
 * ```sh
 * $ pulumi import incident:index/announcementTemplate:AnnouncementTemplate example 01ABC123DEF456GHI789JKL
 * ```
 */
export class AnnouncementTemplate extends pulumi.CustomResource {
    /**
     * Get an existing AnnouncementTemplate resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AnnouncementTemplateState, opts?: pulumi.CustomResourceOptions): AnnouncementTemplate {
        return new AnnouncementTemplate(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'incident:index/announcementTemplate:AnnouncementTemplate';

    /**
     * Returns true if the given object is an instance of AnnouncementTemplate.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AnnouncementTemplate {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AnnouncementTemplate.__pulumiType;
    }

    /**
     * Actions shown on the announcement post, in rank order. Set `actions = []` for a post with no actions.
     */
    declare public readonly actions: pulumi.Output<outputs.AnnouncementTemplateAction[]>;
    /**
     * Fields shown on the announcement post, in rank order. Set `fields = []` for a post with no fields.
     */
    declare public readonly fields: pulumi.Output<outputs.AnnouncementTemplateField[]>;
    /**
     * Whether this is the organisation's default template, used by rules that don't choose one
     */
    declare public /*out*/ readonly isDefault: pulumi.Output<boolean>;
    /**
     * Name of this announcement template, unique within the organisation
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * IDs of the teams that own this template
     */
    declare public readonly owningTeamIds: pulumi.Output<string[]>;

    /**
     * Create a AnnouncementTemplate resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AnnouncementTemplateArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AnnouncementTemplateArgs | AnnouncementTemplateState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AnnouncementTemplateState | undefined;
            resourceInputs["actions"] = state?.actions;
            resourceInputs["fields"] = state?.fields;
            resourceInputs["isDefault"] = state?.isDefault;
            resourceInputs["name"] = state?.name;
            resourceInputs["owningTeamIds"] = state?.owningTeamIds;
        } else {
            const args = argsOrState as AnnouncementTemplateArgs | undefined;
            if (args?.actions === undefined && !opts.urn) {
                throw new Error("Missing required property 'actions'");
            }
            if (args?.fields === undefined && !opts.urn) {
                throw new Error("Missing required property 'fields'");
            }
            resourceInputs["actions"] = args?.actions;
            resourceInputs["fields"] = args?.fields;
            resourceInputs["name"] = args?.name;
            resourceInputs["owningTeamIds"] = args?.owningTeamIds;
            resourceInputs["isDefault"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AnnouncementTemplate.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AnnouncementTemplate resources.
 */
export interface AnnouncementTemplateState {
    /**
     * Actions shown on the announcement post, in rank order. Set `actions = []` for a post with no actions.
     */
    actions?: pulumi.Input<pulumi.Input<inputs.AnnouncementTemplateAction>[] | undefined>;
    /**
     * Fields shown on the announcement post, in rank order. Set `fields = []` for a post with no fields.
     */
    fields?: pulumi.Input<pulumi.Input<inputs.AnnouncementTemplateField>[] | undefined>;
    /**
     * Whether this is the organisation's default template, used by rules that don't choose one
     */
    isDefault?: pulumi.Input<boolean | undefined>;
    /**
     * Name of this announcement template, unique within the organisation
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * IDs of the teams that own this template
     */
    owningTeamIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a AnnouncementTemplate resource.
 */
export interface AnnouncementTemplateArgs {
    /**
     * Actions shown on the announcement post, in rank order. Set `actions = []` for a post with no actions.
     */
    actions: pulumi.Input<pulumi.Input<inputs.AnnouncementTemplateAction>[]>;
    /**
     * Fields shown on the announcement post, in rank order. Set `fields = []` for a post with no fields.
     */
    fields: pulumi.Input<pulumi.Input<inputs.AnnouncementTemplateField>[]>;
    /**
     * Name of this announcement template, unique within the organisation
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * IDs of the teams that own this template
     */
    owningTeamIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
