// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Create and manage announcement rules.
 *
 * An announcement rule posts an announcement of each incident that matches its conditions
 * into the channels it lists, rendered with an announcement template.
 *
 * Set `slackChannelIds` when your organisation uses Slack, or `microsoftTeamsChannelIds` when it uses Microsoft Teams.
 *
 * An API key can only manage a rule whose `privateIncidentScope` is `none`: announcing private incidents needs a permission no API key role grants, so a rule scoped to `all` or `owningTeams` has to be managed in the dashboard.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as incident from "@incident-io/pulumi";
 *
 * const critical = incident.getSeverity({
 *     name: "Critical",
 * });
 * // The template the rule's announcements are rendered with: severity and status, then a
 * // button to join the call.
 * const majorIncidents = new incident.AnnouncementTemplate("major_incidents", {
 *     name: "Major incidents",
 *     fields: [
 *         {
 *             fieldType: "announcement_post_fields_severity",
 *         },
 *         {
 *             fieldType: "announcement_post_fields_status",
 *         },
 *     ],
 *     actions: [{
 *         actionType: "announcement_post_actions_join_call",
 *     }],
 * });
 * // Announce every critical incident, triage included, in #major-incidents, rendered with
 * // the major incidents template. Updates are shared in the announcement's thread.
 * const criticalAnnouncementRule = new incident.AnnouncementRule("critical", {
 *     name: "Critical incidents",
 *     slackChannelIds: ["C02AW36C1M5"],
 *     mode: "include_triage",
 *     updateSharingMode: "thread",
 *     templateId: majorIncidents.id,
 *     conditionGroups: [{
 *         conditions: [{
 *             subject: "incident.severity",
 *             operation: "one_of",
 *             paramBindings: [{
 *                 arrayValue: [{
 *                     literal: critical.then(critical => critical.id),
 *                 }],
 *             }],
 *         }],
 *     }],
 * });
 * ```
 *
 * ## Import
 *
 * Import is supported using an `import` block or the `pulumi import` command:
 *
 * The `pulumi import` command can be used, for example:
 *
 * !/bin/bash
 *
 * Import an announcement rule using its ID
 * Replace the ID with a real ID from your incident.io organization
 *
 * ```sh
 * $ pulumi import incident:index/announcementRule:AnnouncementRule example 01ABC123DEF456GHI789JKL
 * ```
 */
export class AnnouncementRule extends pulumi.CustomResource {
    /**
     * Get an existing AnnouncementRule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AnnouncementRuleState, opts?: pulumi.CustomResourceOptions): AnnouncementRule {
        return new AnnouncementRule(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'incident:index/announcementRule:AnnouncementRule';

    /**
     * Returns true if the given object is an instance of AnnouncementRule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AnnouncementRule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AnnouncementRule.__pulumiType;
    }

    /**
     * Groups of prerequisite conditions. All conditions in at least one group must be satisfied
     */
    declare public readonly conditionGroups: pulumi.Output<outputs.AnnouncementRuleConditionGroup[]>;
    /**
     * Whether to remove announcement posts when the incident no longer matches this rule's conditions. Defaults to `leaveInPlace`. Possible values are: `leaveInPlace`, `remove`.
     */
    declare public readonly conditionsNoLongerApplyBehaviour: pulumi.Output<string>;
    /**
     * When the rule was created
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Microsoft Teams channels to post announcements into, as team*id/channel*id. Required when the organisation uses Microsoft Teams.
     */
    declare public readonly microsoftTeamsChannelIds: pulumi.Output<string[]>;
    /**
     * Which incidents are announced: live incidents only, or triage incidents too. Possible values are: `liveAndClosed`, `includeTriage`, `includeTriageAndMerged`, `includeDeclinedAndMerged`, `includeAll`.
     */
    declare public readonly mode: pulumi.Output<string>;
    /**
     * Human readable name for the rule
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * IDs of the teams that own this rule
     */
    declare public readonly owningTeamIds: pulumi.Output<string[]>;
    /**
     * Which private incidents this rule announces: every private incident (all), those an owning team can see (owning_teams), or none. Defaults to `none`. Possible values are: `all`, `owningTeams`, `none`.
     */
    declare public readonly privateIncidentScope: pulumi.Output<string>;
    /**
     * IDs of the Slack channels to post announcements into. Required when the organisation uses Slack.
     */
    declare public readonly slackChannelIds: pulumi.Output<string[]>;
    /**
     * ID of the announcement template used to render this rule's posts. Defaults to the organisation's default template when omitted.
     */
    declare public readonly templateId: pulumi.Output<string>;
    /**
     * Where incident updates are shared once the incident is announced. Possible values are: `none`, `thread`, `threadAndChannel`.
     */
    declare public readonly updateSharingMode: pulumi.Output<string>;
    /**
     * When the rule was last updated
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;

    /**
     * Create a AnnouncementRule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AnnouncementRuleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AnnouncementRuleArgs | AnnouncementRuleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AnnouncementRuleState | undefined;
            resourceInputs["conditionGroups"] = state?.conditionGroups;
            resourceInputs["conditionsNoLongerApplyBehaviour"] = state?.conditionsNoLongerApplyBehaviour;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["microsoftTeamsChannelIds"] = state?.microsoftTeamsChannelIds;
            resourceInputs["mode"] = state?.mode;
            resourceInputs["name"] = state?.name;
            resourceInputs["owningTeamIds"] = state?.owningTeamIds;
            resourceInputs["privateIncidentScope"] = state?.privateIncidentScope;
            resourceInputs["slackChannelIds"] = state?.slackChannelIds;
            resourceInputs["templateId"] = state?.templateId;
            resourceInputs["updateSharingMode"] = state?.updateSharingMode;
            resourceInputs["updatedAt"] = state?.updatedAt;
        } else {
            const args = argsOrState as AnnouncementRuleArgs | undefined;
            if (args?.conditionGroups === undefined && !opts.urn) {
                throw new Error("Missing required property 'conditionGroups'");
            }
            if (args?.mode === undefined && !opts.urn) {
                throw new Error("Missing required property 'mode'");
            }
            if (args?.updateSharingMode === undefined && !opts.urn) {
                throw new Error("Missing required property 'updateSharingMode'");
            }
            resourceInputs["conditionGroups"] = args?.conditionGroups;
            resourceInputs["conditionsNoLongerApplyBehaviour"] = args?.conditionsNoLongerApplyBehaviour;
            resourceInputs["microsoftTeamsChannelIds"] = args?.microsoftTeamsChannelIds;
            resourceInputs["mode"] = args?.mode;
            resourceInputs["name"] = args?.name;
            resourceInputs["owningTeamIds"] = args?.owningTeamIds;
            resourceInputs["privateIncidentScope"] = args?.privateIncidentScope;
            resourceInputs["slackChannelIds"] = args?.slackChannelIds;
            resourceInputs["templateId"] = args?.templateId;
            resourceInputs["updateSharingMode"] = args?.updateSharingMode;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AnnouncementRule.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AnnouncementRule resources.
 */
export interface AnnouncementRuleState {
    /**
     * Groups of prerequisite conditions. All conditions in at least one group must be satisfied
     */
    conditionGroups?: pulumi.Input<pulumi.Input<inputs.AnnouncementRuleConditionGroup>[] | undefined>;
    /**
     * Whether to remove announcement posts when the incident no longer matches this rule's conditions. Defaults to `leaveInPlace`. Possible values are: `leaveInPlace`, `remove`.
     */
    conditionsNoLongerApplyBehaviour?: pulumi.Input<string | undefined>;
    /**
     * When the rule was created
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * Microsoft Teams channels to post announcements into, as team*id/channel*id. Required when the organisation uses Microsoft Teams.
     */
    microsoftTeamsChannelIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Which incidents are announced: live incidents only, or triage incidents too. Possible values are: `liveAndClosed`, `includeTriage`, `includeTriageAndMerged`, `includeDeclinedAndMerged`, `includeAll`.
     */
    mode?: pulumi.Input<string | undefined>;
    /**
     * Human readable name for the rule
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * IDs of the teams that own this rule
     */
    owningTeamIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Which private incidents this rule announces: every private incident (all), those an owning team can see (owning_teams), or none. Defaults to `none`. Possible values are: `all`, `owningTeams`, `none`.
     */
    privateIncidentScope?: pulumi.Input<string | undefined>;
    /**
     * IDs of the Slack channels to post announcements into. Required when the organisation uses Slack.
     */
    slackChannelIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * ID of the announcement template used to render this rule's posts. Defaults to the organisation's default template when omitted.
     */
    templateId?: pulumi.Input<string | undefined>;
    /**
     * Where incident updates are shared once the incident is announced. Possible values are: `none`, `thread`, `threadAndChannel`.
     */
    updateSharingMode?: pulumi.Input<string | undefined>;
    /**
     * When the rule was last updated
     */
    updatedAt?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a AnnouncementRule resource.
 */
export interface AnnouncementRuleArgs {
    /**
     * Groups of prerequisite conditions. All conditions in at least one group must be satisfied
     */
    conditionGroups: pulumi.Input<pulumi.Input<inputs.AnnouncementRuleConditionGroup>[]>;
    /**
     * Whether to remove announcement posts when the incident no longer matches this rule's conditions. Defaults to `leaveInPlace`. Possible values are: `leaveInPlace`, `remove`.
     */
    conditionsNoLongerApplyBehaviour?: pulumi.Input<string | undefined>;
    /**
     * Microsoft Teams channels to post announcements into, as team*id/channel*id. Required when the organisation uses Microsoft Teams.
     */
    microsoftTeamsChannelIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Which incidents are announced: live incidents only, or triage incidents too. Possible values are: `liveAndClosed`, `includeTriage`, `includeTriageAndMerged`, `includeDeclinedAndMerged`, `includeAll`.
     */
    mode: pulumi.Input<string>;
    /**
     * Human readable name for the rule
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * IDs of the teams that own this rule
     */
    owningTeamIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Which private incidents this rule announces: every private incident (all), those an owning team can see (owning_teams), or none. Defaults to `none`. Possible values are: `all`, `owningTeams`, `none`.
     */
    privateIncidentScope?: pulumi.Input<string | undefined>;
    /**
     * IDs of the Slack channels to post announcements into. Required when the organisation uses Slack.
     */
    slackChannelIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * ID of the announcement template used to render this rule's posts. Defaults to the organisation's default template when omitted.
     */
    templateId?: pulumi.Input<string | undefined>;
    /**
     * Where incident updates are shared once the incident is announced. Possible values are: `none`, `thread`, `threadAndChannel`.
     */
    updateSharingMode: pulumi.Input<string>;
}
