// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * This resource manages all entries for a given catalog type and should be used when
 * loading many (>100) catalog entries to ensure fast and reliable plans.
 *
 * Please note that this resource is authoritative, in that it will delete _all_ entries from
 * the catalog type that it doesn't manage, even those created outside of Terraform.
 *
 * If you have a catalog source such as Backstage or some custom catalog you'd like to sync
 * into incident.io, this is the recommended way of achieving that.
 *
 * ## External IDs
 *
 * As this resource loads content from an existing catalog source into the incident.io
 * catalog, it requires that each entry is given a stable identifier that can uniquely
 * identify it in the upstream system.
 *
 * We call this the 'external ID' and it might be something like:
 *
 * - The ID of the entry in a custom catalog, often the primary key of the entry
 * - Any stable human identifier (often called a slug) that uniquely reference the entry
 *
 * This external ID is what we use as a map key for the entries attribute, and how we map
 * changes to one entry to an update to that same entry when the upstream changes.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as incident from "@incident-io/pulumi";
 * import * as std from "@pulumi/std";
 *
 * function tryOutput_(
 * 	...fns: Array<() => pulumi.Input<any>>
 * ): pulumi.Output<any> {
 * 	if (fns.length === 0) {
 * 		throw new Error("try: all parameters failed");
 * 	}
 * 	const [fn, ...rest] = fns;
 * 	try {
 * 		return pulumi.output(fn()).apply(result => result !== undefined ? result : tryOutput_(...rest));
 * 	} catch {
 * 		return tryOutput_(...rest);
 * 	}
 * 	throw new Error("try: all parameters failed");
 * }
 *
 *
 * function try_(
 * 	...fns: Array<() => any>
 * ): any {
 * 	for (const fn of fns) {
 * 		try {
 * 			const result = fn();
 * 			if (result === undefined) {
 * 				continue;
 * 			}
 * 			return result;
 * 		} catch (e) {
 * 			continue;
 * 		}
 * 	}
 * 	throw new Error("try: all parameters failed");
 * }
 *
 *
 * //###############################################################################
 * // Simple Example
 * //###############################################################################
 * const simpleExample = new incident.CatalogType("simple_example", {
 *     name: "Simple Example",
 *     description: "A simple example catalog type",
 *     sourceRepoUrl: "https://example.com/myrepo",
 * });
 * const exampleUrl = new incident.CatalogTypeAttribute("example_url", {
 *     catalogTypeId: simpleExample.id,
 *     name: "url",
 *     type: "String",
 * });
 * const simpleExampleCatalogEntries = new incident.CatalogEntries("simple_example", {
 *     catalogEntriesId: simpleExample.id,
 *     entries: {
 *         foo: {
 *             name: "Foo",
 *             attributeValues: exampleUrl.id.apply(id => {
 *                 [id]: {
 *                     value: "https://example.com/foo",
 *                 },
 *             }),
 *         },
 *         bar: {
 *             name: "Bar",
 *             attributeValues: exampleUrl.id.apply(id => {
 *                 [id]: {
 *                     value: "https://example.com/bar",
 *                 },
 *             }),
 *         },
 *     },
 * });
 * const catalog = .reduce((__obj, entry) => ({ ...__obj, [String(entry.uid)]: entry }), {});
 * // Define the catalog type, creating attributes that map to the values in the
 * // catalog data source.
 * const service = new incident.CatalogType("service", {
 *     name: "Service",
 *     description: "All services that we run at Example Org",
 *     sourceRepoUrl: "",
 * });
 * const serviceOwner = new incident.CatalogTypeAttribute("service_owner", {
 *     catalogTypeId: service.id,
 *     name: "Owner",
 *     type: "String",
 * });
 * const serviceDescription = new incident.CatalogTypeAttribute("service_description", {
 *     catalogTypeId: service.id,
 *     name: "Description",
 *     type: "String",
 * });
 * const serviceTags = new incident.CatalogTypeAttribute("service_tags", {
 *     catalogTypeId: service.id,
 *     name: "Tags",
 *     type: "String",
 *     array: true,
 * });
 * //###############################################################################
 * // Provision the entries
 * //###############################################################################
 * // This is where we create all the entries. If we have any entries in Service
 * // that are not defined in this resource, we will delete them.
 * const services = new incident.CatalogEntries("services", {
 *     catalogEntriesId: service.id,
 *     entries: Object.entries(catalog).sort().reduce((__obj, [externalId, entry]) => ({ ...__obj, [externalId]: {
 *         name: entry.metadata.name,
 *         aliases: [entry.metadata.name],
 *         attributeValues: pulumi.all([serviceOwner.id, tryOutput_(
 *             () => entry.spec.owner,
 *             () => null
 *         ), serviceDescription.id, tryOutput_(
 *             () => entry.metadata.description,
 *             () => null
 *         ), serviceTags.id, tryOutput_(
 *             () => entry.metadata.tags,
 *             () => null
 *         )]).apply(([serviceOwnerId, _try, serviceDescriptionId, _try1, serviceTagsId, _try2]) => Object.entries({
 *             [serviceOwnerId]: {
 *                 value: _try,
 *             },
 *             [serviceDescriptionId]: {
 *                 value: _try1,
 *             },
 *             [serviceTagsId]: {
 *                 arrayValue: _try2,
 *             },
 *         }).sort().filter(([attribute, binding]) => try_(
 *             () => binding.value,
 *             () => binding.arrayValue
 *         ) != null).reduce((__obj, [attribute, binding]) => ({ ...__obj, [attribute]: binding }), {})),
 *     } }), {}),
 * });
 * ```
 */
export class CatalogEntries extends pulumi.CustomResource {
    /**
     * Get an existing CatalogEntries resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CatalogEntriesState, opts?: pulumi.CustomResourceOptions): CatalogEntries {
        return new CatalogEntries(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'incident:index/catalogEntries:CatalogEntries';

    /**
     * Returns true if the given object is an instance of CatalogEntries.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CatalogEntries {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CatalogEntries.__pulumiType;
    }

    /**
     * ID of this catalog type
     */
    declare public readonly catalogEntriesId: pulumi.Output<string>;
    /**
     * Map of external ID to entry in the catalog.
     */
    declare public readonly entries: pulumi.Output<{[key: string]: outputs.CatalogEntriesEntries}>;
    /**
     * The set of attributes that are managed by this resource. By default, all attributes are managed by this resource.
     */
    declare public readonly managedAttributes: pulumi.Output<string[] | undefined>;

    /**
     * Create a CatalogEntries resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CatalogEntriesArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CatalogEntriesArgs | CatalogEntriesState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CatalogEntriesState | undefined;
            resourceInputs["catalogEntriesId"] = state?.catalogEntriesId;
            resourceInputs["entries"] = state?.entries;
            resourceInputs["managedAttributes"] = state?.managedAttributes;
        } else {
            const args = argsOrState as CatalogEntriesArgs | undefined;
            if (args?.catalogEntriesId === undefined && !opts.urn) {
                throw new Error("Missing required property 'catalogEntriesId'");
            }
            if (args?.entries === undefined && !opts.urn) {
                throw new Error("Missing required property 'entries'");
            }
            resourceInputs["catalogEntriesId"] = args?.catalogEntriesId;
            resourceInputs["entries"] = args?.entries;
            resourceInputs["managedAttributes"] = args?.managedAttributes;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CatalogEntries.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CatalogEntries resources.
 */
export interface CatalogEntriesState {
    /**
     * ID of this catalog type
     */
    catalogEntriesId?: pulumi.Input<string | undefined>;
    /**
     * Map of external ID to entry in the catalog.
     */
    entries?: pulumi.Input<{[key: string]: pulumi.Input<inputs.CatalogEntriesEntries>} | undefined>;
    /**
     * The set of attributes that are managed by this resource. By default, all attributes are managed by this resource.
     */
    managedAttributes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a CatalogEntries resource.
 */
export interface CatalogEntriesArgs {
    /**
     * ID of this catalog type
     */
    catalogEntriesId: pulumi.Input<string>;
    /**
     * Map of external ID to entry in the catalog.
     */
    entries: pulumi.Input<{[key: string]: pulumi.Input<inputs.CatalogEntriesEntries>}>;
    /**
     * The set of attributes that are managed by this resource. By default, all attributes are managed by this resource.
     */
    managedAttributes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
