// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage custom field options.
 *
 * Single- and multi-select custom fields have a list of all available options,
 * which have a value, and a sort key. The value must be unique to the custom
 * field. For example, you might have an Incident Type custom field, with options
 * "Data breach", "Performance degradation", "API downtime", etc.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as incident from "@incident-io/pulumi";
 *
 * // Create an Affected Teams custom field that we'll create options against.
 * const affectedTeams = new incident.CustomField("affected_teams", {
 *     name: "Affected Teams",
 *     description: "The teams that are affected by this incident.",
 *     fieldType: "multi_select",
 * });
 * // Create several teams against the parent custom field.
 * const teams: {[key: string]: incident.CustomFieldOption} = {};
 * for (const range of Object.entries([
 *     "Payments",
 *     "Dashboard",
 *     "API",
 * ].reduce((__obj, entry) => ({ ...__obj, [entry]: entry }), {})).sort().map(([k, v]) => ({key: k, value: v}))) {
 *     teams[range.key] = new incident.CustomFieldOption(`teams-${range.key}`, {
 *         customFieldId: affectedTeams.id,
 *         value: range.value,
 *     });
 * }
 * ```
 */
export class CustomFieldOption extends pulumi.CustomResource {
    /**
     * Get an existing CustomFieldOption resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CustomFieldOptionState, opts?: pulumi.CustomResourceOptions): CustomFieldOption {
        return new CustomFieldOption(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'incident:index/customFieldOption:CustomFieldOption';

    /**
     * Returns true if the given object is an instance of CustomFieldOption.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CustomFieldOption {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CustomFieldOption.__pulumiType;
    }

    /**
     * ID of the custom field this option belongs to
     */
    declare public readonly customFieldId: pulumi.Output<string>;
    /**
     * Sort key used to order the custom field options correctly
     */
    declare public readonly sortKey: pulumi.Output<number>;
    /**
     * Human readable name for the custom field option. Values must not start or end with whitespace, or contain tabs or newlines.
     */
    declare public readonly value: pulumi.Output<string>;

    /**
     * Create a CustomFieldOption resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CustomFieldOptionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CustomFieldOptionArgs | CustomFieldOptionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CustomFieldOptionState | undefined;
            resourceInputs["customFieldId"] = state?.customFieldId;
            resourceInputs["sortKey"] = state?.sortKey;
            resourceInputs["value"] = state?.value;
        } else {
            const args = argsOrState as CustomFieldOptionArgs | undefined;
            if (args?.customFieldId === undefined && !opts.urn) {
                throw new Error("Missing required property 'customFieldId'");
            }
            if (args?.value === undefined && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            resourceInputs["customFieldId"] = args?.customFieldId;
            resourceInputs["sortKey"] = args?.sortKey;
            resourceInputs["value"] = args?.value;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CustomFieldOption.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CustomFieldOption resources.
 */
export interface CustomFieldOptionState {
    /**
     * ID of the custom field this option belongs to
     */
    customFieldId?: pulumi.Input<string | undefined>;
    /**
     * Sort key used to order the custom field options correctly
     */
    sortKey?: pulumi.Input<number | undefined>;
    /**
     * Human readable name for the custom field option. Values must not start or end with whitespace, or contain tabs or newlines.
     */
    value?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a CustomFieldOption resource.
 */
export interface CustomFieldOptionArgs {
    /**
     * ID of the custom field this option belongs to
     */
    customFieldId: pulumi.Input<string>;
    /**
     * Sort key used to order the custom field options correctly
     */
    sortKey?: pulumi.Input<number | undefined>;
    /**
     * Human readable name for the custom field option. Values must not start or end with whitespace, or contain tabs or newlines.
     */
    value: pulumi.Input<string>;
}
