// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * `incident.AlertSourceAttributeBeta` was renamed to `incident.AlertSourceAttribute` in v7.0.
 *
 * This name still works and still manages the same thing, so upgrading to v7 needs no change
 * to a configuration that uses it. It is deprecated: every plan naming it warns, and it will
 * be removed in v8.0.
 *
 * To move onto the new name:
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * ```
 *
 * Both names are the same resource, backed by the same schema and the same API, so the move
 * carries your state across and the plan after it is empty. See `incident.AlertSourceAttribute` for the
 * documentation.
 */
export function getAlertSourceAttributeBeta(args: GetAlertSourceAttributeBetaArgs, opts?: pulumi.InvokeOptions): Promise<GetAlertSourceAttributeBetaResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("incident:index/getAlertSourceAttributeBeta:getAlertSourceAttributeBeta", {
        "alertAttributeId": args.alertAttributeId,
        "alertSourceId": args.alertSourceId,
        "expression": args.expression,
        "namedExpressions": args.namedExpressions,
    }, opts);
}

/**
 * A collection of arguments for invoking getAlertSourceAttributeBeta.
 */
export interface GetAlertSourceAttributeBetaArgs {
    /**
     * The alert attribute being bound. This also identifies the binding: an attribute can be bound at most once per source.
     */
    alertAttributeId: string;
    /**
     * The alert source this binding belongs to
     */
    alertSourceId: string;
    /**
     * The expression this field is bound to. Declaring it binds its result.
     */
    expression?: inputs.GetAlertSourceAttributeBetaExpression;
    /**
     * An expression this resource owns, addressed by name.
     */
    namedExpressions?: inputs.GetAlertSourceAttributeBetaNamedExpression[];
}

/**
 * A collection of values returned by getAlertSourceAttributeBeta.
 */
export interface GetAlertSourceAttributeBetaResult {
    /**
     * The alert attribute being bound. This also identifies the binding: an attribute can be bound at most once per source.
     */
    readonly alertAttributeId: string;
    /**
     * The alert source this binding belongs to
     */
    readonly alertSourceId: string;
    /**
     * Several values, spelled out. Needed when they mix fixed values and references.
     */
    readonly arrayValues: outputs.GetAlertSourceAttributeBetaArrayValue[];
    /**
     * The expression this field is bound to. Declaring it binds its result.
     */
    readonly expression?: outputs.GetAlertSourceAttributeBetaExpression;
    /**
     * The name of a namedExpression in this resource, whose result becomes the value.
     */
    readonly expressionRef: string;
    /**
     * How values are combined when an alert is updated. Possible values are: `firstWins`, `lastWins`, `append`, `max`, `min`.
     */
    readonly mergeStrategy: string;
    /**
     * An expression this resource owns, addressed by name.
     */
    readonly namedExpressions?: outputs.GetAlertSourceAttributeBetaNamedExpression[];
    /**
     * One value, spelled out. `valueLiteral` and `valueReference` are shorthand for this.
     */
    readonly value: outputs.GetAlertSourceAttributeBetaValue;
    /**
     * A fixed value. A catalog entry ID is a literal, not a reference.
     */
    readonly valueLiteral: string;
    /**
     * A reference into the scope, such as `payload.team`.
     */
    readonly valueReference: string;
    /**
     * Several fixed values. For a mix of fixed values and references, use array_value.
     */
    readonly values: string[];
}
/**
 * `incident.AlertSourceAttributeBeta` was renamed to `incident.AlertSourceAttribute` in v7.0.
 *
 * This name still works and still manages the same thing, so upgrading to v7 needs no change
 * to a configuration that uses it. It is deprecated: every plan naming it warns, and it will
 * be removed in v8.0.
 *
 * To move onto the new name:
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * ```
 *
 * Both names are the same resource, backed by the same schema and the same API, so the move
 * carries your state across and the plan after it is empty. See `incident.AlertSourceAttribute` for the
 * documentation.
 */
export function getAlertSourceAttributeBetaOutput(args: GetAlertSourceAttributeBetaOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAlertSourceAttributeBetaResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("incident:index/getAlertSourceAttributeBeta:getAlertSourceAttributeBeta", {
        "alertAttributeId": args.alertAttributeId,
        "alertSourceId": args.alertSourceId,
        "expression": args.expression,
        "namedExpressions": args.namedExpressions,
    }, opts);
}

/**
 * A collection of arguments for invoking getAlertSourceAttributeBeta.
 */
export interface GetAlertSourceAttributeBetaOutputArgs {
    /**
     * The alert attribute being bound. This also identifies the binding: an attribute can be bound at most once per source.
     */
    alertAttributeId: pulumi.Input<string>;
    /**
     * The alert source this binding belongs to
     */
    alertSourceId: pulumi.Input<string>;
    /**
     * The expression this field is bound to. Declaring it binds its result.
     */
    expression?: pulumi.Input<inputs.GetAlertSourceAttributeBetaExpressionArgs | undefined>;
    /**
     * An expression this resource owns, addressed by name.
     */
    namedExpressions?: pulumi.Input<pulumi.Input<inputs.GetAlertSourceAttributeBetaNamedExpressionArgs>[] | undefined>;
}
