// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Look up a schedule by `id` or `name`. Exactly one lookup field should be set.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as incident from "@incident-io/pulumi";
 *
 * // Look up a schedule by name...
 * const platform = incident.getScheduleBeta({
 *     name: "Platform on-call",
 * });
 * // ...or by ID, which is what you want if several schedules share a name.
 * const platformById = incident.getScheduleBeta({
 *     id: "01ABC123DEF456GHI789JKL",
 * });
 * ```
 */
export function getScheduleBeta(args?: GetScheduleBetaArgs, opts?: pulumi.InvokeOptions): Promise<GetScheduleBetaResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("incident:index/getScheduleBeta:getScheduleBeta", {
        "id": args.id,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getScheduleBeta.
 */
export interface GetScheduleBetaArgs {
    /**
     * Look up the schedule by ID.
     */
    id?: string;
    /**
     * Look up the schedule by name. Names aren't unique, so this fails if more than one schedule matches.
     */
    name?: string;
}

/**
 * A collection of values returned by getScheduleBeta.
 */
export interface GetScheduleBetaResult {
    /**
     * Look up the schedule by ID.
     */
    readonly id: string;
    /**
     * Look up the schedule by name. Names aren't unique, so this fails if more than one schedule matches.
     */
    readonly name: string;
    /**
     * IDs of teams that own this schedule
     */
    readonly teamIds: string[];
    /**
     * Timezone the schedule's rotations are anchored to, as an IANA name
     */
    readonly timezone: string;
}
/**
 * Look up a schedule by `id` or `name`. Exactly one lookup field should be set.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as incident from "@incident-io/pulumi";
 *
 * // Look up a schedule by name...
 * const platform = incident.getScheduleBeta({
 *     name: "Platform on-call",
 * });
 * // ...or by ID, which is what you want if several schedules share a name.
 * const platformById = incident.getScheduleBeta({
 *     id: "01ABC123DEF456GHI789JKL",
 * });
 * ```
 */
export function getScheduleBetaOutput(args?: GetScheduleBetaOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetScheduleBetaResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("incident:index/getScheduleBeta:getScheduleBeta", {
        "id": args.id,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getScheduleBeta.
 */
export interface GetScheduleBetaOutputArgs {
    /**
     * Look up the schedule by ID.
     */
    id?: pulumi.Input<string | undefined>;
    /**
     * Look up the schedule by name. Names aren't unique, so this fails if more than one schedule matches.
     */
    name?: pulumi.Input<string | undefined>;
}
