// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manages the structure of a standalone status page: which components it shows, in what order, how they are grouped, and how each is displayed. The page itself is created in the incident.io dashboard; look it up with the `incident.getStatusPage` data source. Components come from `incident.StatusPageComponent`.
 *
 * A group keeps its ID across applies as long as its name does, so links to it stay valid. Renaming a group creates a new one. Display settings left out of the configuration keep whatever the page already has, so a structure adopted from the dashboard keeps its hidden components and uptime settings until the configuration says otherwise.
 *
 * Terraform claims the structure, so it cannot be edited in the dashboard; set `unlockInDashboard` to leave it editable there. Destroying this resource leaves the page's structure in place, since a page always has one; it only stops Terraform managing it. The API key needs the "Configure status pages" permission. Parent and customer pages build their structure from the catalog and cannot be managed here.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as incident from "@incident-io/pulumi";
 *
 * // The page itself is created in the dashboard. Its components can be managed here.
 * const _public = incident.getStatusPage({
 *     name: "Our public status page",
 * });
 * const website = new incident.StatusPageComponent("website", {name: "Website"});
 * const api = new incident.StatusPageComponent("api", {name: "API"});
 * const database = new incident.StatusPageComponent("database", {name: "Database"});
 * // The structure is the page's layout: items appear in the order listed, each one either a
 * // single component or a named group of components. Display settings are optional; one left
 * // out keeps whatever the dashboard has.
 * const publicStatusPageStructure = new incident.StatusPageStructure("public", {
 *     statusPageId: _public.then(_public => _public.id),
 *     displayUptimeMode: "chart_and_percentage",
 *     items: [
 *         {
 *             componentId: website.id,
 *         },
 *         {
 *             group: {
 *                 name: "Backend",
 *                 description: "The services behind the website",
 *                 components: [
 *                     {
 *                         componentId: api.id,
 *                     },
 *                     {
 *                         componentId: database.id,
 *                         displayUptime: false,
 *                     },
 *                 ],
 *             },
 *         },
 *     ],
 * });
 * ```
 *
 * ## Import
 *
 * Import is supported using an `import` block or the `pulumi import` command:
 *
 * The `pulumi import` command can be used, for example:
 *
 * !/bin/bash
 *
 * Import a status page's structure using the status page's ID
 * Replace the ID with a real ID from your incident.io organization
 *
 * ```sh
 * $ pulumi import incident:index/statusPageStructure:StatusPageStructure example 01ABC123DEF456GHI789JKL
 * ```
 */
export class StatusPageStructure extends pulumi.CustomResource {
    /**
     * Get an existing StatusPageStructure resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: StatusPageStructureState, opts?: pulumi.CustomResourceOptions): StatusPageStructure {
        return new StatusPageStructure(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'incident:index/statusPageStructure:StatusPageStructure';

    /**
     * Returns true if the given object is an instance of StatusPageStructure.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StatusPageStructure {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StatusPageStructure.__pulumiType;
    }

    /**
     * How the page shows uptime against its components: `chartAndPercentage`, `chartOnly` or `nothing`. Left out, the page keeps its current setting.
     */
    declare public readonly displayUptimeMode: pulumi.Output<string>;
    /**
     * The components and groups the page shows, in display order. Each item is either a single `componentId`, with its own `hidden` and `displayUptime`, or a `group`, not both.
     */
    declare public readonly items: pulumi.Output<outputs.StatusPageStructureItem[]>;
    /**
     * The ID of the status page whose structure this is. Changing it manages a different page's structure.
     */
    declare public readonly statusPageId: pulumi.Output<string>;
    /**
     * Whether to leave this resource unlocked in the incident.io dashboard, so people can edit it there. Defaults to `false`: Terraform claims what it manages, and a claimed resource cannot be edited in the dashboard. Set it to `true` to leave the resource unclaimed — pair that with `lifecycle { ignoreChanges = [...] }` naming the attributes people edit, or the next apply reverts them. Setting it on a resource Terraform already claimed hands that resource back, and someone disconnecting one in the dashboard shows as no change.
     */
    declare public readonly unlockInDashboard: pulumi.Output<boolean | undefined>;

    /**
     * Create a StatusPageStructure resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: StatusPageStructureArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: StatusPageStructureArgs | StatusPageStructureState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as StatusPageStructureState | undefined;
            resourceInputs["displayUptimeMode"] = state?.displayUptimeMode;
            resourceInputs["items"] = state?.items;
            resourceInputs["statusPageId"] = state?.statusPageId;
            resourceInputs["unlockInDashboard"] = state?.unlockInDashboard;
        } else {
            const args = argsOrState as StatusPageStructureArgs | undefined;
            if (args?.items === undefined && !opts.urn) {
                throw new Error("Missing required property 'items'");
            }
            if (args?.statusPageId === undefined && !opts.urn) {
                throw new Error("Missing required property 'statusPageId'");
            }
            resourceInputs["displayUptimeMode"] = args?.displayUptimeMode;
            resourceInputs["items"] = args?.items;
            resourceInputs["statusPageId"] = args?.statusPageId;
            resourceInputs["unlockInDashboard"] = args?.unlockInDashboard;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(StatusPageStructure.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering StatusPageStructure resources.
 */
export interface StatusPageStructureState {
    /**
     * How the page shows uptime against its components: `chartAndPercentage`, `chartOnly` or `nothing`. Left out, the page keeps its current setting.
     */
    displayUptimeMode?: pulumi.Input<string | undefined>;
    /**
     * The components and groups the page shows, in display order. Each item is either a single `componentId`, with its own `hidden` and `displayUptime`, or a `group`, not both.
     */
    items?: pulumi.Input<pulumi.Input<inputs.StatusPageStructureItem>[] | undefined>;
    /**
     * The ID of the status page whose structure this is. Changing it manages a different page's structure.
     */
    statusPageId?: pulumi.Input<string | undefined>;
    /**
     * Whether to leave this resource unlocked in the incident.io dashboard, so people can edit it there. Defaults to `false`: Terraform claims what it manages, and a claimed resource cannot be edited in the dashboard. Set it to `true` to leave the resource unclaimed — pair that with `lifecycle { ignoreChanges = [...] }` naming the attributes people edit, or the next apply reverts them. Setting it on a resource Terraform already claimed hands that resource back, and someone disconnecting one in the dashboard shows as no change.
     */
    unlockInDashboard?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a StatusPageStructure resource.
 */
export interface StatusPageStructureArgs {
    /**
     * How the page shows uptime against its components: `chartAndPercentage`, `chartOnly` or `nothing`. Left out, the page keeps its current setting.
     */
    displayUptimeMode?: pulumi.Input<string | undefined>;
    /**
     * The components and groups the page shows, in display order. Each item is either a single `componentId`, with its own `hidden` and `displayUptime`, or a `group`, not both.
     */
    items: pulumi.Input<pulumi.Input<inputs.StatusPageStructureItem>[]>;
    /**
     * The ID of the status page whose structure this is. Changing it manages a different page's structure.
     */
    statusPageId: pulumi.Input<string>;
    /**
     * Whether to leave this resource unlocked in the incident.io dashboard, so people can edit it there. Defaults to `false`: Terraform claims what it manages, and a claimed resource cannot be edited in the dashboard. Set it to `true` to leave the resource unclaimed — pair that with `lifecycle { ignoreChanges = [...] }` naming the attributes people edit, or the next apply reverts them. Setting it on a resource Terraform already claimed hands that resource back, and someone disconnecting one in the dashboard shows as no change.
     */
    unlockInDashboard?: pulumi.Input<boolean | undefined>;
}
